// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/message.proto

package pt.sharespot.iot.core.buf.model;

public interface AirQualityOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pt.sharespot.iot.core.AirQuality)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float value = 1;</code>
   * @return The value.
   */
  float getValue();
}
