// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/message.proto

package pt.sharespot.iot.core.buf.model;

public interface AlarmOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pt.sharespot.iot.core.Alarm)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool value = 1;</code>
   * @return The value.
   */
  boolean getValue();
}
