// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/message.proto

package pt.sharespot.iot.core.buf.model;

public interface DeviceDomainsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pt.sharespot.iot.core.DeviceDomains)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string read = 1;</code>
   * @return A list containing the read.
   */
  java.util.List<java.lang.String>
      getReadList();
  /**
   * <code>repeated string read = 1;</code>
   * @return The count of read.
   */
  int getReadCount();
  /**
   * <code>repeated string read = 1;</code>
   * @param index The index of the element to return.
   * @return The read at the given index.
   */
  java.lang.String getRead(int index);
  /**
   * <code>repeated string read = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the read at the given index.
   */
  com.google.protobuf.ByteString
      getReadBytes(int index);

  /**
   * <code>repeated string read_write = 2;</code>
   * @return A list containing the readWrite.
   */
  java.util.List<java.lang.String>
      getReadWriteList();
  /**
   * <code>repeated string read_write = 2;</code>
   * @return The count of readWrite.
   */
  int getReadWriteCount();
  /**
   * <code>repeated string read_write = 2;</code>
   * @param index The index of the element to return.
   * @return The readWrite at the given index.
   */
  java.lang.String getReadWrite(int index);
  /**
   * <code>repeated string read_write = 2;</code>
   * @param index The index of the value to return.
   * @return The bytes of the readWrite at the given index.
   */
  com.google.protobuf.ByteString
      getReadWriteBytes(int index);
}
