// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/message.proto

package pt.sharespot.iot.core.buf.model;

/**
 * Protobuf type {@code pt.sharespot.iot.core.Device}
 */
public final class Device extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:pt.sharespot.iot.core.Device)
    DeviceOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Device.newBuilder() to construct.
  private Device(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Device() {
    id_ = "";
    name_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Device();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Device(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            id_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 26: {
            pt.sharespot.iot.core.buf.model.RecordEntry.Builder subBuilder = null;
            if (records_ != null) {
              subBuilder = records_.toBuilder();
            }
            records_ = input.readMessage(pt.sharespot.iot.core.buf.model.RecordEntry.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(records_);
              records_ = subBuilder.buildPartial();
            }

            break;
          }
          case 34: {
            pt.sharespot.iot.core.buf.model.DeviceDomains.Builder subBuilder = null;
            if (domains_ != null) {
              subBuilder = domains_.toBuilder();
            }
            domains_ = input.readMessage(pt.sharespot.iot.core.buf.model.DeviceDomains.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(domains_);
              domains_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return pt.sharespot.iot.core.buf.model.MessageOuterClass.internal_static_pt_sharespot_iot_core_Device_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return pt.sharespot.iot.core.buf.model.MessageOuterClass.internal_static_pt_sharespot_iot_core_Device_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            pt.sharespot.iot.core.buf.model.Device.class, pt.sharespot.iot.core.buf.model.Device.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object id_;
  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object name_;
  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RECORDS_FIELD_NUMBER = 3;
  private pt.sharespot.iot.core.buf.model.RecordEntry records_;
  /**
   * <code>.pt.sharespot.iot.core.RecordEntry records = 3;</code>
   * @return Whether the records field is set.
   */
  @java.lang.Override
  public boolean hasRecords() {
    return records_ != null;
  }
  /**
   * <code>.pt.sharespot.iot.core.RecordEntry records = 3;</code>
   * @return The records.
   */
  @java.lang.Override
  public pt.sharespot.iot.core.buf.model.RecordEntry getRecords() {
    return records_ == null ? pt.sharespot.iot.core.buf.model.RecordEntry.getDefaultInstance() : records_;
  }
  /**
   * <code>.pt.sharespot.iot.core.RecordEntry records = 3;</code>
   */
  @java.lang.Override
  public pt.sharespot.iot.core.buf.model.RecordEntryOrBuilder getRecordsOrBuilder() {
    return getRecords();
  }

  public static final int DOMAINS_FIELD_NUMBER = 4;
  private pt.sharespot.iot.core.buf.model.DeviceDomains domains_;
  /**
   * <code>.pt.sharespot.iot.core.DeviceDomains domains = 4;</code>
   * @return Whether the domains field is set.
   */
  @java.lang.Override
  public boolean hasDomains() {
    return domains_ != null;
  }
  /**
   * <code>.pt.sharespot.iot.core.DeviceDomains domains = 4;</code>
   * @return The domains.
   */
  @java.lang.Override
  public pt.sharespot.iot.core.buf.model.DeviceDomains getDomains() {
    return domains_ == null ? pt.sharespot.iot.core.buf.model.DeviceDomains.getDefaultInstance() : domains_;
  }
  /**
   * <code>.pt.sharespot.iot.core.DeviceDomains domains = 4;</code>
   */
  @java.lang.Override
  public pt.sharespot.iot.core.buf.model.DeviceDomainsOrBuilder getDomainsOrBuilder() {
    return getDomains();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
    }
    if (records_ != null) {
      output.writeMessage(3, getRecords());
    }
    if (domains_ != null) {
      output.writeMessage(4, getDomains());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
    }
    if (records_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getRecords());
    }
    if (domains_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getDomains());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof pt.sharespot.iot.core.buf.model.Device)) {
      return super.equals(obj);
    }
    pt.sharespot.iot.core.buf.model.Device other = (pt.sharespot.iot.core.buf.model.Device) obj;

    if (!getId()
        .equals(other.getId())) return false;
    if (!getName()
        .equals(other.getName())) return false;
    if (hasRecords() != other.hasRecords()) return false;
    if (hasRecords()) {
      if (!getRecords()
          .equals(other.getRecords())) return false;
    }
    if (hasDomains() != other.hasDomains()) return false;
    if (hasDomains()) {
      if (!getDomains()
          .equals(other.getDomains())) return false;
    }
    return unknownFields.equals(other.unknownFields);
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    if (hasRecords()) {
      hash = (37 * hash) + RECORDS_FIELD_NUMBER;
      hash = (53 * hash) + getRecords().hashCode();
    }
    if (hasDomains()) {
      hash = (37 * hash) + DOMAINS_FIELD_NUMBER;
      hash = (53 * hash) + getDomains().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static pt.sharespot.iot.core.buf.model.Device parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static pt.sharespot.iot.core.buf.model.Device parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static pt.sharespot.iot.core.buf.model.Device parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static pt.sharespot.iot.core.buf.model.Device parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static pt.sharespot.iot.core.buf.model.Device parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static pt.sharespot.iot.core.buf.model.Device parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static pt.sharespot.iot.core.buf.model.Device parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static pt.sharespot.iot.core.buf.model.Device parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static pt.sharespot.iot.core.buf.model.Device parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static pt.sharespot.iot.core.buf.model.Device parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static pt.sharespot.iot.core.buf.model.Device parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static pt.sharespot.iot.core.buf.model.Device parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(pt.sharespot.iot.core.buf.model.Device prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code pt.sharespot.iot.core.Device}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:pt.sharespot.iot.core.Device)
      pt.sharespot.iot.core.buf.model.DeviceOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pt.sharespot.iot.core.buf.model.MessageOuterClass.internal_static_pt_sharespot_iot_core_Device_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pt.sharespot.iot.core.buf.model.MessageOuterClass.internal_static_pt_sharespot_iot_core_Device_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pt.sharespot.iot.core.buf.model.Device.class, pt.sharespot.iot.core.buf.model.Device.Builder.class);
    }

    // Construct using pt.sharespot.iot.core.buf.model.Device.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = "";

      name_ = "";

      if (recordsBuilder_ == null) {
        records_ = null;
      } else {
        records_ = null;
        recordsBuilder_ = null;
      }
      if (domainsBuilder_ == null) {
        domains_ = null;
      } else {
        domains_ = null;
        domainsBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return pt.sharespot.iot.core.buf.model.MessageOuterClass.internal_static_pt_sharespot_iot_core_Device_descriptor;
    }

    @java.lang.Override
    public pt.sharespot.iot.core.buf.model.Device getDefaultInstanceForType() {
      return pt.sharespot.iot.core.buf.model.Device.getDefaultInstance();
    }

    @java.lang.Override
    public pt.sharespot.iot.core.buf.model.Device build() {
      pt.sharespot.iot.core.buf.model.Device result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public pt.sharespot.iot.core.buf.model.Device buildPartial() {
      pt.sharespot.iot.core.buf.model.Device result = new pt.sharespot.iot.core.buf.model.Device(this);
      result.id_ = id_;
      result.name_ = name_;
      if (recordsBuilder_ == null) {
        result.records_ = records_;
      } else {
        result.records_ = recordsBuilder_.build();
      }
      if (domainsBuilder_ == null) {
        result.domains_ = domains_;
      } else {
        result.domains_ = domainsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof pt.sharespot.iot.core.buf.model.Device) {
        return mergeFrom((pt.sharespot.iot.core.buf.model.Device)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(pt.sharespot.iot.core.buf.model.Device other) {
      if (other == pt.sharespot.iot.core.buf.model.Device.getDefaultInstance()) return this;
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        onChanged();
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (other.hasRecords()) {
        mergeRecords(other.getRecords());
      }
      if (other.hasDomains()) {
        mergeDomains(other.getDomains());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      pt.sharespot.iot.core.buf.model.Device parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (pt.sharespot.iot.core.buf.model.Device) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object id_ = "";
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = getDefaultInstance().getId();
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      id_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private pt.sharespot.iot.core.buf.model.RecordEntry records_;
    private com.google.protobuf.SingleFieldBuilderV3<
        pt.sharespot.iot.core.buf.model.RecordEntry, pt.sharespot.iot.core.buf.model.RecordEntry.Builder, pt.sharespot.iot.core.buf.model.RecordEntryOrBuilder> recordsBuilder_;
    /**
     * <code>.pt.sharespot.iot.core.RecordEntry records = 3;</code>
     * @return Whether the records field is set.
     */
    public boolean hasRecords() {
      return recordsBuilder_ != null || records_ != null;
    }
    /**
     * <code>.pt.sharespot.iot.core.RecordEntry records = 3;</code>
     * @return The records.
     */
    public pt.sharespot.iot.core.buf.model.RecordEntry getRecords() {
      if (recordsBuilder_ == null) {
        return records_ == null ? pt.sharespot.iot.core.buf.model.RecordEntry.getDefaultInstance() : records_;
      } else {
        return recordsBuilder_.getMessage();
      }
    }
    /**
     * <code>.pt.sharespot.iot.core.RecordEntry records = 3;</code>
     */
    public Builder setRecords(pt.sharespot.iot.core.buf.model.RecordEntry value) {
      if (recordsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        records_ = value;
        onChanged();
      } else {
        recordsBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.pt.sharespot.iot.core.RecordEntry records = 3;</code>
     */
    public Builder setRecords(
        pt.sharespot.iot.core.buf.model.RecordEntry.Builder builderForValue) {
      if (recordsBuilder_ == null) {
        records_ = builderForValue.build();
        onChanged();
      } else {
        recordsBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.pt.sharespot.iot.core.RecordEntry records = 3;</code>
     */
    public Builder mergeRecords(pt.sharespot.iot.core.buf.model.RecordEntry value) {
      if (recordsBuilder_ == null) {
        if (records_ != null) {
          records_ =
            pt.sharespot.iot.core.buf.model.RecordEntry.newBuilder(records_).mergeFrom(value).buildPartial();
        } else {
          records_ = value;
        }
        onChanged();
      } else {
        recordsBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.pt.sharespot.iot.core.RecordEntry records = 3;</code>
     */
    public Builder clearRecords() {
      if (recordsBuilder_ == null) {
        records_ = null;
        onChanged();
      } else {
        records_ = null;
        recordsBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.pt.sharespot.iot.core.RecordEntry records = 3;</code>
     */
    public pt.sharespot.iot.core.buf.model.RecordEntry.Builder getRecordsBuilder() {
      
      onChanged();
      return getRecordsFieldBuilder().getBuilder();
    }
    /**
     * <code>.pt.sharespot.iot.core.RecordEntry records = 3;</code>
     */
    public pt.sharespot.iot.core.buf.model.RecordEntryOrBuilder getRecordsOrBuilder() {
      if (recordsBuilder_ != null) {
        return recordsBuilder_.getMessageOrBuilder();
      } else {
        return records_ == null ?
            pt.sharespot.iot.core.buf.model.RecordEntry.getDefaultInstance() : records_;
      }
    }
    /**
     * <code>.pt.sharespot.iot.core.RecordEntry records = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        pt.sharespot.iot.core.buf.model.RecordEntry, pt.sharespot.iot.core.buf.model.RecordEntry.Builder, pt.sharespot.iot.core.buf.model.RecordEntryOrBuilder> 
        getRecordsFieldBuilder() {
      if (recordsBuilder_ == null) {
        recordsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            pt.sharespot.iot.core.buf.model.RecordEntry, pt.sharespot.iot.core.buf.model.RecordEntry.Builder, pt.sharespot.iot.core.buf.model.RecordEntryOrBuilder>(
                getRecords(),
                getParentForChildren(),
                isClean());
        records_ = null;
      }
      return recordsBuilder_;
    }

    private pt.sharespot.iot.core.buf.model.DeviceDomains domains_;
    private com.google.protobuf.SingleFieldBuilderV3<
        pt.sharespot.iot.core.buf.model.DeviceDomains, pt.sharespot.iot.core.buf.model.DeviceDomains.Builder, pt.sharespot.iot.core.buf.model.DeviceDomainsOrBuilder> domainsBuilder_;
    /**
     * <code>.pt.sharespot.iot.core.DeviceDomains domains = 4;</code>
     * @return Whether the domains field is set.
     */
    public boolean hasDomains() {
      return domainsBuilder_ != null || domains_ != null;
    }
    /**
     * <code>.pt.sharespot.iot.core.DeviceDomains domains = 4;</code>
     * @return The domains.
     */
    public pt.sharespot.iot.core.buf.model.DeviceDomains getDomains() {
      if (domainsBuilder_ == null) {
        return domains_ == null ? pt.sharespot.iot.core.buf.model.DeviceDomains.getDefaultInstance() : domains_;
      } else {
        return domainsBuilder_.getMessage();
      }
    }
    /**
     * <code>.pt.sharespot.iot.core.DeviceDomains domains = 4;</code>
     */
    public Builder setDomains(pt.sharespot.iot.core.buf.model.DeviceDomains value) {
      if (domainsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        domains_ = value;
        onChanged();
      } else {
        domainsBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.pt.sharespot.iot.core.DeviceDomains domains = 4;</code>
     */
    public Builder setDomains(
        pt.sharespot.iot.core.buf.model.DeviceDomains.Builder builderForValue) {
      if (domainsBuilder_ == null) {
        domains_ = builderForValue.build();
        onChanged();
      } else {
        domainsBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.pt.sharespot.iot.core.DeviceDomains domains = 4;</code>
     */
    public Builder mergeDomains(pt.sharespot.iot.core.buf.model.DeviceDomains value) {
      if (domainsBuilder_ == null) {
        if (domains_ != null) {
          domains_ =
            pt.sharespot.iot.core.buf.model.DeviceDomains.newBuilder(domains_).mergeFrom(value).buildPartial();
        } else {
          domains_ = value;
        }
        onChanged();
      } else {
        domainsBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.pt.sharespot.iot.core.DeviceDomains domains = 4;</code>
     */
    public Builder clearDomains() {
      if (domainsBuilder_ == null) {
        domains_ = null;
        onChanged();
      } else {
        domains_ = null;
        domainsBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.pt.sharespot.iot.core.DeviceDomains domains = 4;</code>
     */
    public pt.sharespot.iot.core.buf.model.DeviceDomains.Builder getDomainsBuilder() {
      
      onChanged();
      return getDomainsFieldBuilder().getBuilder();
    }
    /**
     * <code>.pt.sharespot.iot.core.DeviceDomains domains = 4;</code>
     */
    public pt.sharespot.iot.core.buf.model.DeviceDomainsOrBuilder getDomainsOrBuilder() {
      if (domainsBuilder_ != null) {
        return domainsBuilder_.getMessageOrBuilder();
      } else {
        return domains_ == null ?
            pt.sharespot.iot.core.buf.model.DeviceDomains.getDefaultInstance() : domains_;
      }
    }
    /**
     * <code>.pt.sharespot.iot.core.DeviceDomains domains = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        pt.sharespot.iot.core.buf.model.DeviceDomains, pt.sharespot.iot.core.buf.model.DeviceDomains.Builder, pt.sharespot.iot.core.buf.model.DeviceDomainsOrBuilder> 
        getDomainsFieldBuilder() {
      if (domainsBuilder_ == null) {
        domainsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            pt.sharespot.iot.core.buf.model.DeviceDomains, pt.sharespot.iot.core.buf.model.DeviceDomains.Builder, pt.sharespot.iot.core.buf.model.DeviceDomainsOrBuilder>(
                getDomains(),
                getParentForChildren(),
                isClean());
        domains_ = null;
      }
      return domainsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:pt.sharespot.iot.core.Device)
  }

  // @@protoc_insertion_point(class_scope:pt.sharespot.iot.core.Device)
  private static final pt.sharespot.iot.core.buf.model.Device DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new pt.sharespot.iot.core.buf.model.Device();
  }

  public static pt.sharespot.iot.core.buf.model.Device getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Device>
      PARSER = new com.google.protobuf.AbstractParser<Device>() {
    @java.lang.Override
    public Device parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Device(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Device> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Device> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public pt.sharespot.iot.core.buf.model.Device getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

