// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/message.proto

package pt.sharespot.iot.core.buf.model;

public interface DeviceCommandsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pt.sharespot.iot.core.DeviceCommands)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .pt.sharespot.iot.core.DeviceCommand command = 1;</code>
   */
  java.util.List<pt.sharespot.iot.core.buf.model.DeviceCommand> 
      getCommandList();
  /**
   * <code>repeated .pt.sharespot.iot.core.DeviceCommand command = 1;</code>
   */
  pt.sharespot.iot.core.buf.model.DeviceCommand getCommand(int index);
  /**
   * <code>repeated .pt.sharespot.iot.core.DeviceCommand command = 1;</code>
   */
  int getCommandCount();
  /**
   * <code>repeated .pt.sharespot.iot.core.DeviceCommand command = 1;</code>
   */
  java.util.List<? extends pt.sharespot.iot.core.buf.model.DeviceCommandOrBuilder> 
      getCommandOrBuilderList();
  /**
   * <code>repeated .pt.sharespot.iot.core.DeviceCommand command = 1;</code>
   */
  pt.sharespot.iot.core.buf.model.DeviceCommandOrBuilder getCommandOrBuilder(
      int index);
}
