// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/message.proto

package pt.sharespot.iot.core.buf.model;

public interface IlluminanceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pt.sharespot.iot.core.Illuminance)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float lux = 1;</code>
   * @return The lux.
   */
  float getLux();
}
