// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/message.proto

package pt.sharespot.iot.core.buf.model;

public final class MessageOuterClass {
  private MessageOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pt_sharespot_iot_core_UnprocessedMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pt_sharespot_iot_core_UnprocessedMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pt_sharespot_iot_core_Message_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pt_sharespot_iot_core_Message_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pt_sharespot_iot_core_Data_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pt_sharespot_iot_core_Data_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pt_sharespot_iot_core_SensorData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pt_sharespot_iot_core_SensorData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pt_sharespot_iot_core_GPS_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pt_sharespot_iot_core_GPS_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pt_sharespot_iot_core_Motion_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pt_sharespot_iot_core_Motion_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pt_sharespot_iot_core_Temperature_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pt_sharespot_iot_core_Temperature_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pt_sharespot_iot_core_AirQuality_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pt_sharespot_iot_core_AirQuality_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pt_sharespot_iot_core_Velocity_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pt_sharespot_iot_core_Velocity_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pt_sharespot_iot_core_AirHumidity_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pt_sharespot_iot_core_AirHumidity_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pt_sharespot_iot_core_AirPressure_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pt_sharespot_iot_core_AirPressure_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pt_sharespot_iot_core_Battery_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pt_sharespot_iot_core_Battery_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pt_sharespot_iot_core_SoilMoisture_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pt_sharespot_iot_core_SoilMoisture_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pt_sharespot_iot_core_Illuminance_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pt_sharespot_iot_core_Illuminance_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pt_sharespot_iot_core_Trigger_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pt_sharespot_iot_core_Trigger_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pt_sharespot_iot_core_Device_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pt_sharespot_iot_core_Device_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pt_sharespot_iot_core_RecordEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pt_sharespot_iot_core_RecordEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pt_sharespot_iot_core_Entry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pt_sharespot_iot_core_Entry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pt_sharespot_iot_core_DeviceDomains_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pt_sharespot_iot_core_DeviceDomains_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pt_sharespot_iot_core_RoutingKeysBuf_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pt_sharespot_iot_core_RoutingKeysBuf_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n src/main/resources/message.proto\022\025pt.s" +
      "harespot.iot.core\"\206\001\n\022UnprocessedMessage" +
      "\022\013\n\003oid\030\001 \001(\t\022;\n\014routing_keys\030\002 \001(\0132%.pt" +
      ".sharespot.iot.core.RoutingKeysBuf\022\014\n\004ho" +
      "ps\030\003 \001(\005\022\030\n\020unprocessed_data\030\004 \001(\t\"\214\001\n\007M" +
      "essage\022\013\n\003oid\030\001 \001(\t\022;\n\014routing_keys\030\002 \001(" +
      "\0132%.pt.sharespot.iot.core.RoutingKeysBuf" +
      "\022\014\n\004hops\030\003 \001(\005\022)\n\004data\030\004 \001(\0132\033.pt.shares" +
      "pot.iot.core.Data\"\223\001\n\004Data\022\017\n\007data_id\030\001 " +
      "\001(\t\022\023\n\013reported_at\030\002 \001(\003\022-\n\006device\030\003 \001(\013" +
      "2\035.pt.sharespot.iot.core.Device\0226\n\013senso" +
      "r_data\030\004 \001(\0132!.pt.sharespot.iot.core.Sen" +
      "sorData\"\313\004\n\nSensorData\022\'\n\003gps\030\001 \001(\0132\032.pt" +
      ".sharespot.iot.core.GPS\0227\n\013temperature\030\002" +
      " \001(\0132\".pt.sharespot.iot.core.Temperature" +
      "\022-\n\006motion\030\003 \001(\0132\035.pt.sharespot.iot.core" +
      ".Motion\022.\n\003aqi\030\004 \001(\0132!.pt.sharespot.iot." +
      "core.AirQuality\0221\n\010velocity\030\005 \001(\0132\037.pt.s" +
      "harespot.iot.core.Velocity\0228\n\014air_humidi" +
      "ty\030\006 \001(\0132\".pt.sharespot.iot.core.AirHumi" +
      "dity\0228\n\014air_pressure\030\007 \001(\0132\".pt.sharespo" +
      "t.iot.core.AirPressure\022/\n\007battery\030\010 \001(\0132" +
      "\036.pt.sharespot.iot.core.Battery\022:\n\rsoil_" +
      "moisture\030\t \001(\0132#.pt.sharespot.iot.core.S" +
      "oilMoisture\0227\n\013illuminance\030\n \001(\0132\".pt.sh" +
      "arespot.iot.core.Illuminance\022/\n\007trigger\030" +
      "\013 \001(\0132\036.pt.sharespot.iot.core.Trigger\"<\n" +
      "\003GPS\022\020\n\010latitude\030\001 \001(\001\022\021\n\tlongitude\030\002 \001(" +
      "\001\022\020\n\010altitude\030\003 \001(\002\":\n\006Motion\0220\n\005value\030\001" +
      " \001(\0162!.pt.sharespot.iot.core.MotionType\"" +
      "\036\n\013Temperature\022\017\n\007celsius\030\001 \001(\002\"\033\n\nAirQu" +
      "ality\022\r\n\005value\030\001 \001(\002\"\'\n\010Velocity\022\033\n\023kilo" +
      "meters_per_hour\030\001 \001(\002\"I\n\013AirHumidity\022\035\n\025" +
      "grams_per_cubic_meter\030\001 \001(\002\022\033\n\023relative_" +
      "percentage\030\002 \001(\002\"#\n\013AirPressure\022\024\n\014hecto" +
      "_pascal\030\001 \001(\002\",\n\007Battery\022\022\n\npercentage\030\001" +
      " \001(\002\022\r\n\005volts\030\002 \001(\002\"+\n\014SoilMoisture\022\033\n\023r" +
      "elative_percentage\030\001 \001(\002\"\032\n\013Illuminance\022" +
      "\013\n\003lux\030\001 \001(\002\"\030\n\007Trigger\022\r\n\005value\030\001 \001(\010\"\216" +
      "\001\n\006Device\022\n\n\002id\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\0223\n\007r" +
      "ecords\030\003 \001(\0132\".pt.sharespot.iot.core.Rec" +
      "ordEntry\0225\n\007domains\030\004 \001(\0132$.pt.sharespot" +
      ".iot.core.DeviceDomains\"<\n\013RecordEntry\022-" +
      "\n\007entries\030\001 \003(\0132\034.pt.sharespot.iot.core." +
      "Entry\"\'\n\005Entry\022\r\n\005label\030\001 \001(\t\022\017\n\007content" +
      "\030\002 \001(\t\"1\n\rDeviceDomains\022\014\n\004read\030\001 \003(\t\022\022\n" +
      "\nread_write\030\002 \003(\t\"\353\010\n\016RoutingKeysBuf\022\017\n\007" +
      "version\030\001 \001(\t\022F\n\016container_type\030\002 \001(\0162.." +
      "pt.sharespot.iot.core.ContainerTypeOptio" +
      "nsBuf\022<\n\tinfo_type\030\003 \001(\0162).pt.sharespot." +
      "iot.core.InfoTypeOptionsBuf\022\023\n\013sensor_ty" +
      "pe\030\004 \001(\t\022\017\n\007channel\030\005 \001(\t\0229\n\007records\030\006 \001" +
      "(\0162(.pt.sharespot.iot.core.RecordsOption" +
      "sBuf\0225\n\003gps\030\007 \001(\0162(.pt.sharespot.iot.cor" +
      "e.GPSDataOptionsBuf\022E\n\013temperature\030\010 \001(\016" +
      "20.pt.sharespot.iot.core.TemperatureData" +
      "OptionsBuf\022C\n\nlegitimacy\030\t \001(\0162/.pt.shar" +
      "espot.iot.core.DataLegitimacyOptionsBuf\022" +
      "<\n\003aqi\030\n \001(\0162/.pt.sharespot.iot.core.Air" +
      "QualityDataOptionsBuf\022F\n\014air_humidity\030\013 " +
      "\001(\01620.pt.sharespot.iot.core.AirHumidityD" +
      "ataOptionsBuf\022;\n\006motion\030\014 \001(\0162+.pt.share" +
      "spot.iot.core.MotionDataOptionsBuf\022?\n\010ve" +
      "locity\030\r \001(\0162-.pt.sharespot.iot.core.Vel" +
      "ocityDataOptionsBuf\022F\n\014air_pressure\030\016 \001(" +
      "\01620.pt.sharespot.iot.core.AirPressureDat" +
      "aOptionsBuf\022=\n\007battery\030\017 \001(\0162,.pt.shares" +
      "pot.iot.core.BatteryDataOptionsBuf\022H\n\rso" +
      "il_moisture\030\020 \001(\01621.pt.sharespot.iot.cor" +
      "e.SoilMoistureDataOptionsBuf\022E\n\013illumina" +
      "nce\030\021 \001(\01620.pt.sharespot.iot.core.Illumi" +
      "nanceDataOptionsBuf\022C\n\townership\030\022 \001(\01620" +
      ".pt.sharespot.iot.core.DomainOwnershipOp" +
      "tionsBuf\022=\n\007trigger\030\023 \001(\0162,.pt.sharespot" +
      ".iot.core.TriggerDataOptionsBuf*3\n\nMotio" +
      "nType\022\013\n\007UNKNOWN\020\000\022\n\n\006ACTIVE\020\001\022\014\n\010INACTI" +
      "VE\020\002*g\n\025TriggerDataOptionsBuf\022\035\n\031UNIDENT" +
      "IFIED_TRIGGER_DATA\020\000\022\025\n\021WITH_TRIGGER_DAT" +
      "A\020\001\022\030\n\024WITHOUT_TRIGGER_DATA\020\002*w\n\031DomainO" +
      "wnershipOptionsBuf\022!\n\035UNIDENTIFIED_DOMAI" +
      "N_OWNERSHIP\020\000\022\031\n\025WITH_DOMAIN_OWNERSHIP\020\001" +
      "\022\034\n\030WITHOUT_DOMAIN_OWNERSHIP\020\002*w\n\031Illumi" +
      "nanceDataOptionsBuf\022!\n\035UNIDENTIFIED_ILLU" +
      "MINANCE_DATA\020\000\022\031\n\025WITH_ILLUMINANCE_DATA\020" +
      "\001\022\034\n\030WITHOUT_ILLUMINANCE_DATA\020\002*~\n\032SoilM" +
      "oistureDataOptionsBuf\022#\n\037UNIDENTIFIED_SO" +
      "IL_MOISTURE_DATA\020\000\022\033\n\027WITH_SOIL_MOISTURE" +
      "_DATA\020\001\022\036\n\032WITHOUT_SOIL_MOISTURE_DATA\020\002*" +
      "g\n\025BatteryDataOptionsBuf\022\035\n\031UNIDENTIFIED" +
      "_BATTERY_DATA\020\000\022\025\n\021WITH_BATTERY_DATA\020\001\022\030" +
      "\n\024WITHOUT_BATTERY_DATA\020\002*z\n\031AirPressureD" +
      "ataOptionsBuf\022\"\n\036UNIDENTIFIED_AIR_PRESSU" +
      "RE_DATA\020\000\022\032\n\026WITH_AIR_PRESSURE_DATA\020\001\022\035\n" +
      "\031WITHOUT_AIR_PRESSURE_DATA\020\002*k\n\026Velocity" +
      "DataOptionsBuf\022\036\n\032UNIDENTIFIED_VELOCITY_" +
      "DATA\020\000\022\026\n\022WITH_VELOCITY_DATA\020\001\022\031\n\025WITHOU" +
      "T_VELOCITY_DATA\020\002*c\n\024MotionDataOptionsBu" +
      "f\022\034\n\030UNIDENTIFIED_MOTION_DATA\020\000\022\024\n\020WITH_" +
      "MOTION_DATA\020\001\022\027\n\023WITHOUT_MOTION_DATA\020\002*z" +
      "\n\031AirHumidityDataOptionsBuf\022\"\n\036UNIDENTIF" +
      "IED_AIR_HUMIDITY_DATA\020\000\022\032\n\026WITH_AIR_HUMI" +
      "DITY_DATA\020\001\022\035\n\031WITHOUT_AIR_HUMIDITY_DATA" +
      "\020\002*^\n\030AirQualityDataOptionsBuf\022\031\n\025UNIDEN" +
      "TIFIED_AQI_DATA\020\000\022\021\n\rWITH_AQI_DATA\020\001\022\024\n\020" +
      "WITHOUT_AQI_DATA\020\002*\201\001\n\030DataLegitimacyOpt" +
      "ionsBuf\022\026\n\022UNKNOWN_LEGITIMACY\020\000\022\026\n\022CORRE" +
      "CT_LEGITIMACY\020\001\022\030\n\024INCORRECT_LEGITIMACY\020" +
      "\002\022\033\n\027UNDETERMINED_LEGITIMACY\020\003*w\n\031Temper" +
      "atureDataOptionsBuf\022!\n\035UNIDENTIFIED_TEMP" +
      "ERATURE_DATA\020\000\022\031\n\025WITH_TEMPERATURE_DATA\020" +
      "\001\022\034\n\030WITHOUT_TEMPERATURE_DATA\020\002*W\n\021GPSDa" +
      "taOptionsBuf\022\031\n\025UNIDENTIFIED_GPS_DATA\020\000\022" +
      "\021\n\rWITH_GPS_DATA\020\001\022\024\n\020WITHOUT_GPS_DATA\020\002" +
      "*T\n\021RecordsOptionsBuf\022\030\n\024UNIDENTIFIED_RE" +
      "CORDS\020\000\022\020\n\014WITH_RECORDS\020\001\022\023\n\017WITHOUT_REC" +
      "ORDS\020\002*=\n\022InfoTypeOptionsBuf\022\013\n\007ENCODED\020" +
      "\000\022\013\n\007DECODED\020\001\022\r\n\tPROCESSED\020\002*\331\001\n\027Contai" +
      "nerTypeOptionsBuf\022\t\n\005OTHER\020\000\022\020\n\014DATA_GAT" +
      "EWAY\020\001\022\022\n\016DATA_PROCESSOR\020\002\022\020\n\014DATA_DECOD" +
      "ER\020\003\022\022\n\016DATA_VALIDATOR\020\004\022\016\n\nDATA_STORE\020\005" +
      "\022\027\n\023IDENTITY_MANAGEMENT\020\006\022\022\n\016DEVICE_RECO" +
      "RDS\020\007\022\024\n\020FLEET_MANAGEMENT\020\010\022\024\n\020SMART_IRR" +
      "IGATION\020\tB#\n\037pt.sharespot.iot.core.buf.m" +
      "odelP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_pt_sharespot_iot_core_UnprocessedMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_pt_sharespot_iot_core_UnprocessedMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pt_sharespot_iot_core_UnprocessedMessage_descriptor,
        new java.lang.String[] { "Oid", "RoutingKeys", "Hops", "UnprocessedData", });
    internal_static_pt_sharespot_iot_core_Message_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_pt_sharespot_iot_core_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pt_sharespot_iot_core_Message_descriptor,
        new java.lang.String[] { "Oid", "RoutingKeys", "Hops", "Data", });
    internal_static_pt_sharespot_iot_core_Data_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_pt_sharespot_iot_core_Data_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pt_sharespot_iot_core_Data_descriptor,
        new java.lang.String[] { "DataId", "ReportedAt", "Device", "SensorData", });
    internal_static_pt_sharespot_iot_core_SensorData_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_pt_sharespot_iot_core_SensorData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pt_sharespot_iot_core_SensorData_descriptor,
        new java.lang.String[] { "Gps", "Temperature", "Motion", "Aqi", "Velocity", "AirHumidity", "AirPressure", "Battery", "SoilMoisture", "Illuminance", "Trigger", });
    internal_static_pt_sharespot_iot_core_GPS_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_pt_sharespot_iot_core_GPS_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pt_sharespot_iot_core_GPS_descriptor,
        new java.lang.String[] { "Latitude", "Longitude", "Altitude", });
    internal_static_pt_sharespot_iot_core_Motion_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_pt_sharespot_iot_core_Motion_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pt_sharespot_iot_core_Motion_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_pt_sharespot_iot_core_Temperature_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_pt_sharespot_iot_core_Temperature_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pt_sharespot_iot_core_Temperature_descriptor,
        new java.lang.String[] { "Celsius", });
    internal_static_pt_sharespot_iot_core_AirQuality_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_pt_sharespot_iot_core_AirQuality_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pt_sharespot_iot_core_AirQuality_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_pt_sharespot_iot_core_Velocity_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_pt_sharespot_iot_core_Velocity_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pt_sharespot_iot_core_Velocity_descriptor,
        new java.lang.String[] { "KilometersPerHour", });
    internal_static_pt_sharespot_iot_core_AirHumidity_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_pt_sharespot_iot_core_AirHumidity_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pt_sharespot_iot_core_AirHumidity_descriptor,
        new java.lang.String[] { "GramsPerCubicMeter", "RelativePercentage", });
    internal_static_pt_sharespot_iot_core_AirPressure_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_pt_sharespot_iot_core_AirPressure_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pt_sharespot_iot_core_AirPressure_descriptor,
        new java.lang.String[] { "HectoPascal", });
    internal_static_pt_sharespot_iot_core_Battery_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_pt_sharespot_iot_core_Battery_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pt_sharespot_iot_core_Battery_descriptor,
        new java.lang.String[] { "Percentage", "Volts", });
    internal_static_pt_sharespot_iot_core_SoilMoisture_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_pt_sharespot_iot_core_SoilMoisture_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pt_sharespot_iot_core_SoilMoisture_descriptor,
        new java.lang.String[] { "RelativePercentage", });
    internal_static_pt_sharespot_iot_core_Illuminance_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_pt_sharespot_iot_core_Illuminance_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pt_sharespot_iot_core_Illuminance_descriptor,
        new java.lang.String[] { "Lux", });
    internal_static_pt_sharespot_iot_core_Trigger_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_pt_sharespot_iot_core_Trigger_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pt_sharespot_iot_core_Trigger_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_pt_sharespot_iot_core_Device_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_pt_sharespot_iot_core_Device_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pt_sharespot_iot_core_Device_descriptor,
        new java.lang.String[] { "Id", "Name", "Records", "Domains", });
    internal_static_pt_sharespot_iot_core_RecordEntry_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_pt_sharespot_iot_core_RecordEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pt_sharespot_iot_core_RecordEntry_descriptor,
        new java.lang.String[] { "Entries", });
    internal_static_pt_sharespot_iot_core_Entry_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_pt_sharespot_iot_core_Entry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pt_sharespot_iot_core_Entry_descriptor,
        new java.lang.String[] { "Label", "Content", });
    internal_static_pt_sharespot_iot_core_DeviceDomains_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_pt_sharespot_iot_core_DeviceDomains_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pt_sharespot_iot_core_DeviceDomains_descriptor,
        new java.lang.String[] { "Read", "ReadWrite", });
    internal_static_pt_sharespot_iot_core_RoutingKeysBuf_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_pt_sharespot_iot_core_RoutingKeysBuf_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pt_sharespot_iot_core_RoutingKeysBuf_descriptor,
        new java.lang.String[] { "Version", "ContainerType", "InfoType", "SensorType", "Channel", "Records", "Gps", "Temperature", "Legitimacy", "Aqi", "AirHumidity", "Motion", "Velocity", "AirPressure", "Battery", "SoilMoisture", "Illuminance", "Ownership", "Trigger", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
