// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/message.proto

package pt.sharespot.iot.core.buf.model;

/**
 * Protobuf enum {@code pt.sharespot.iot.core.RecordsOptionsBuf}
 */
public enum RecordsOptionsBuf
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>UNIDENTIFIED_RECORDS = 0;</code>
   */
  UNIDENTIFIED_RECORDS(0),
  /**
   * <code>WITH_RECORDS = 1;</code>
   */
  WITH_RECORDS(1),
  /**
   * <code>WITHOUT_RECORDS = 2;</code>
   */
  WITHOUT_RECORDS(2),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>UNIDENTIFIED_RECORDS = 0;</code>
   */
  public static final int UNIDENTIFIED_RECORDS_VALUE = 0;
  /**
   * <code>WITH_RECORDS = 1;</code>
   */
  public static final int WITH_RECORDS_VALUE = 1;
  /**
   * <code>WITHOUT_RECORDS = 2;</code>
   */
  public static final int WITHOUT_RECORDS_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static RecordsOptionsBuf valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static RecordsOptionsBuf forNumber(int value) {
    switch (value) {
      case 0: return UNIDENTIFIED_RECORDS;
      case 1: return WITH_RECORDS;
      case 2: return WITHOUT_RECORDS;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<RecordsOptionsBuf>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      RecordsOptionsBuf> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<RecordsOptionsBuf>() {
          public RecordsOptionsBuf findValueByNumber(int number) {
            return RecordsOptionsBuf.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return pt.sharespot.iot.core.buf.model.MessageOuterClass.getDescriptor().getEnumTypes().get(25);
  }

  private static final RecordsOptionsBuf[] VALUES = values();

  public static RecordsOptionsBuf valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private RecordsOptionsBuf(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:pt.sharespot.iot.core.RecordsOptionsBuf)
}

