// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/message.proto

package pt.sharespot.iot.core.buf.model;

/**
 * Protobuf type {@code pt.sharespot.iot.core.RoutingKeysBuf}
 */
public final class RoutingKeysBuf extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:pt.sharespot.iot.core.RoutingKeysBuf)
    RoutingKeysBufOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RoutingKeysBuf.newBuilder() to construct.
  private RoutingKeysBuf(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RoutingKeysBuf() {
    version_ = "";
    containerType_ = 0;
    infoType_ = 0;
    sensorType_ = "";
    channel_ = "";
    records_ = 0;
    gps_ = 0;
    temperature_ = 0;
    legitimacy_ = 0;
    aqi_ = 0;
    airHumidity_ = 0;
    motion_ = 0;
    velocity_ = 0;
    airPressure_ = 0;
    battery_ = 0;
    soilMoisture_ = 0;
    illuminance_ = 0;
    ownership_ = 0;
    trigger_ = 0;
    waterPressure_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new RoutingKeysBuf();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private RoutingKeysBuf(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            version_ = s;
            break;
          }
          case 16: {
            int rawValue = input.readEnum();

            containerType_ = rawValue;
            break;
          }
          case 24: {
            int rawValue = input.readEnum();

            infoType_ = rawValue;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            sensorType_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            channel_ = s;
            break;
          }
          case 48: {
            int rawValue = input.readEnum();

            records_ = rawValue;
            break;
          }
          case 56: {
            int rawValue = input.readEnum();

            gps_ = rawValue;
            break;
          }
          case 64: {
            int rawValue = input.readEnum();

            temperature_ = rawValue;
            break;
          }
          case 72: {
            int rawValue = input.readEnum();

            legitimacy_ = rawValue;
            break;
          }
          case 80: {
            int rawValue = input.readEnum();

            aqi_ = rawValue;
            break;
          }
          case 88: {
            int rawValue = input.readEnum();

            airHumidity_ = rawValue;
            break;
          }
          case 96: {
            int rawValue = input.readEnum();

            motion_ = rawValue;
            break;
          }
          case 104: {
            int rawValue = input.readEnum();

            velocity_ = rawValue;
            break;
          }
          case 112: {
            int rawValue = input.readEnum();

            airPressure_ = rawValue;
            break;
          }
          case 120: {
            int rawValue = input.readEnum();

            battery_ = rawValue;
            break;
          }
          case 128: {
            int rawValue = input.readEnum();

            soilMoisture_ = rawValue;
            break;
          }
          case 136: {
            int rawValue = input.readEnum();

            illuminance_ = rawValue;
            break;
          }
          case 144: {
            int rawValue = input.readEnum();

            ownership_ = rawValue;
            break;
          }
          case 152: {
            int rawValue = input.readEnum();

            trigger_ = rawValue;
            break;
          }
          case 160: {
            int rawValue = input.readEnum();

            waterPressure_ = rawValue;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return pt.sharespot.iot.core.buf.model.MessageOuterClass.internal_static_pt_sharespot_iot_core_RoutingKeysBuf_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return pt.sharespot.iot.core.buf.model.MessageOuterClass.internal_static_pt_sharespot_iot_core_RoutingKeysBuf_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            pt.sharespot.iot.core.buf.model.RoutingKeysBuf.class, pt.sharespot.iot.core.buf.model.RoutingKeysBuf.Builder.class);
  }

  public static final int VERSION_FIELD_NUMBER = 1;
  private volatile java.lang.Object version_;
  /**
   * <code>string version = 1;</code>
   * @return The version.
   */
  @java.lang.Override
  public java.lang.String getVersion() {
    java.lang.Object ref = version_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      version_ = s;
      return s;
    }
  }
  /**
   * <code>string version = 1;</code>
   * @return The bytes for version.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getVersionBytes() {
    java.lang.Object ref = version_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      version_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CONTAINER_TYPE_FIELD_NUMBER = 2;
  private int containerType_;
  /**
   * <code>.pt.sharespot.iot.core.ContainerTypeOptionsBuf container_type = 2;</code>
   * @return The enum numeric value on the wire for containerType.
   */
  @java.lang.Override public int getContainerTypeValue() {
    return containerType_;
  }
  /**
   * <code>.pt.sharespot.iot.core.ContainerTypeOptionsBuf container_type = 2;</code>
   * @return The containerType.
   */
  @java.lang.Override public pt.sharespot.iot.core.buf.model.ContainerTypeOptionsBuf getContainerType() {
    @SuppressWarnings("deprecation")
    pt.sharespot.iot.core.buf.model.ContainerTypeOptionsBuf result = pt.sharespot.iot.core.buf.model.ContainerTypeOptionsBuf.valueOf(containerType_);
    return result == null ? pt.sharespot.iot.core.buf.model.ContainerTypeOptionsBuf.UNRECOGNIZED : result;
  }

  public static final int INFO_TYPE_FIELD_NUMBER = 3;
  private int infoType_;
  /**
   * <code>.pt.sharespot.iot.core.InfoTypeOptionsBuf info_type = 3;</code>
   * @return The enum numeric value on the wire for infoType.
   */
  @java.lang.Override public int getInfoTypeValue() {
    return infoType_;
  }
  /**
   * <code>.pt.sharespot.iot.core.InfoTypeOptionsBuf info_type = 3;</code>
   * @return The infoType.
   */
  @java.lang.Override public pt.sharespot.iot.core.buf.model.InfoTypeOptionsBuf getInfoType() {
    @SuppressWarnings("deprecation")
    pt.sharespot.iot.core.buf.model.InfoTypeOptionsBuf result = pt.sharespot.iot.core.buf.model.InfoTypeOptionsBuf.valueOf(infoType_);
    return result == null ? pt.sharespot.iot.core.buf.model.InfoTypeOptionsBuf.UNRECOGNIZED : result;
  }

  public static final int SENSOR_TYPE_FIELD_NUMBER = 4;
  private volatile java.lang.Object sensorType_;
  /**
   * <code>string sensor_type = 4;</code>
   * @return The sensorType.
   */
  @java.lang.Override
  public java.lang.String getSensorType() {
    java.lang.Object ref = sensorType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sensorType_ = s;
      return s;
    }
  }
  /**
   * <code>string sensor_type = 4;</code>
   * @return The bytes for sensorType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSensorTypeBytes() {
    java.lang.Object ref = sensorType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sensorType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CHANNEL_FIELD_NUMBER = 5;
  private volatile java.lang.Object channel_;
  /**
   * <code>string channel = 5;</code>
   * @return The channel.
   */
  @java.lang.Override
  public java.lang.String getChannel() {
    java.lang.Object ref = channel_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      channel_ = s;
      return s;
    }
  }
  /**
   * <code>string channel = 5;</code>
   * @return The bytes for channel.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getChannelBytes() {
    java.lang.Object ref = channel_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      channel_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RECORDS_FIELD_NUMBER = 6;
  private int records_;
  /**
   * <code>.pt.sharespot.iot.core.RecordsOptionsBuf records = 6;</code>
   * @return The enum numeric value on the wire for records.
   */
  @java.lang.Override public int getRecordsValue() {
    return records_;
  }
  /**
   * <code>.pt.sharespot.iot.core.RecordsOptionsBuf records = 6;</code>
   * @return The records.
   */
  @java.lang.Override public pt.sharespot.iot.core.buf.model.RecordsOptionsBuf getRecords() {
    @SuppressWarnings("deprecation")
    pt.sharespot.iot.core.buf.model.RecordsOptionsBuf result = pt.sharespot.iot.core.buf.model.RecordsOptionsBuf.valueOf(records_);
    return result == null ? pt.sharespot.iot.core.buf.model.RecordsOptionsBuf.UNRECOGNIZED : result;
  }

  public static final int GPS_FIELD_NUMBER = 7;
  private int gps_;
  /**
   * <code>.pt.sharespot.iot.core.GPSDataOptionsBuf gps = 7;</code>
   * @return The enum numeric value on the wire for gps.
   */
  @java.lang.Override public int getGpsValue() {
    return gps_;
  }
  /**
   * <code>.pt.sharespot.iot.core.GPSDataOptionsBuf gps = 7;</code>
   * @return The gps.
   */
  @java.lang.Override public pt.sharespot.iot.core.buf.model.GPSDataOptionsBuf getGps() {
    @SuppressWarnings("deprecation")
    pt.sharespot.iot.core.buf.model.GPSDataOptionsBuf result = pt.sharespot.iot.core.buf.model.GPSDataOptionsBuf.valueOf(gps_);
    return result == null ? pt.sharespot.iot.core.buf.model.GPSDataOptionsBuf.UNRECOGNIZED : result;
  }

  public static final int TEMPERATURE_FIELD_NUMBER = 8;
  private int temperature_;
  /**
   * <code>.pt.sharespot.iot.core.TemperatureDataOptionsBuf temperature = 8;</code>
   * @return The enum numeric value on the wire for temperature.
   */
  @java.lang.Override public int getTemperatureValue() {
    return temperature_;
  }
  /**
   * <code>.pt.sharespot.iot.core.TemperatureDataOptionsBuf temperature = 8;</code>
   * @return The temperature.
   */
  @java.lang.Override public pt.sharespot.iot.core.buf.model.TemperatureDataOptionsBuf getTemperature() {
    @SuppressWarnings("deprecation")
    pt.sharespot.iot.core.buf.model.TemperatureDataOptionsBuf result = pt.sharespot.iot.core.buf.model.TemperatureDataOptionsBuf.valueOf(temperature_);
    return result == null ? pt.sharespot.iot.core.buf.model.TemperatureDataOptionsBuf.UNRECOGNIZED : result;
  }

  public static final int LEGITIMACY_FIELD_NUMBER = 9;
  private int legitimacy_;
  /**
   * <code>.pt.sharespot.iot.core.DataLegitimacyOptionsBuf legitimacy = 9;</code>
   * @return The enum numeric value on the wire for legitimacy.
   */
  @java.lang.Override public int getLegitimacyValue() {
    return legitimacy_;
  }
  /**
   * <code>.pt.sharespot.iot.core.DataLegitimacyOptionsBuf legitimacy = 9;</code>
   * @return The legitimacy.
   */
  @java.lang.Override public pt.sharespot.iot.core.buf.model.DataLegitimacyOptionsBuf getLegitimacy() {
    @SuppressWarnings("deprecation")
    pt.sharespot.iot.core.buf.model.DataLegitimacyOptionsBuf result = pt.sharespot.iot.core.buf.model.DataLegitimacyOptionsBuf.valueOf(legitimacy_);
    return result == null ? pt.sharespot.iot.core.buf.model.DataLegitimacyOptionsBuf.UNRECOGNIZED : result;
  }

  public static final int AQI_FIELD_NUMBER = 10;
  private int aqi_;
  /**
   * <code>.pt.sharespot.iot.core.AirQualityDataOptionsBuf aqi = 10;</code>
   * @return The enum numeric value on the wire for aqi.
   */
  @java.lang.Override public int getAqiValue() {
    return aqi_;
  }
  /**
   * <code>.pt.sharespot.iot.core.AirQualityDataOptionsBuf aqi = 10;</code>
   * @return The aqi.
   */
  @java.lang.Override public pt.sharespot.iot.core.buf.model.AirQualityDataOptionsBuf getAqi() {
    @SuppressWarnings("deprecation")
    pt.sharespot.iot.core.buf.model.AirQualityDataOptionsBuf result = pt.sharespot.iot.core.buf.model.AirQualityDataOptionsBuf.valueOf(aqi_);
    return result == null ? pt.sharespot.iot.core.buf.model.AirQualityDataOptionsBuf.UNRECOGNIZED : result;
  }

  public static final int AIR_HUMIDITY_FIELD_NUMBER = 11;
  private int airHumidity_;
  /**
   * <code>.pt.sharespot.iot.core.AirHumidityDataOptionsBuf air_humidity = 11;</code>
   * @return The enum numeric value on the wire for airHumidity.
   */
  @java.lang.Override public int getAirHumidityValue() {
    return airHumidity_;
  }
  /**
   * <code>.pt.sharespot.iot.core.AirHumidityDataOptionsBuf air_humidity = 11;</code>
   * @return The airHumidity.
   */
  @java.lang.Override public pt.sharespot.iot.core.buf.model.AirHumidityDataOptionsBuf getAirHumidity() {
    @SuppressWarnings("deprecation")
    pt.sharespot.iot.core.buf.model.AirHumidityDataOptionsBuf result = pt.sharespot.iot.core.buf.model.AirHumidityDataOptionsBuf.valueOf(airHumidity_);
    return result == null ? pt.sharespot.iot.core.buf.model.AirHumidityDataOptionsBuf.UNRECOGNIZED : result;
  }

  public static final int MOTION_FIELD_NUMBER = 12;
  private int motion_;
  /**
   * <code>.pt.sharespot.iot.core.MotionDataOptionsBuf motion = 12;</code>
   * @return The enum numeric value on the wire for motion.
   */
  @java.lang.Override public int getMotionValue() {
    return motion_;
  }
  /**
   * <code>.pt.sharespot.iot.core.MotionDataOptionsBuf motion = 12;</code>
   * @return The motion.
   */
  @java.lang.Override public pt.sharespot.iot.core.buf.model.MotionDataOptionsBuf getMotion() {
    @SuppressWarnings("deprecation")
    pt.sharespot.iot.core.buf.model.MotionDataOptionsBuf result = pt.sharespot.iot.core.buf.model.MotionDataOptionsBuf.valueOf(motion_);
    return result == null ? pt.sharespot.iot.core.buf.model.MotionDataOptionsBuf.UNRECOGNIZED : result;
  }

  public static final int VELOCITY_FIELD_NUMBER = 13;
  private int velocity_;
  /**
   * <code>.pt.sharespot.iot.core.VelocityDataOptionsBuf velocity = 13;</code>
   * @return The enum numeric value on the wire for velocity.
   */
  @java.lang.Override public int getVelocityValue() {
    return velocity_;
  }
  /**
   * <code>.pt.sharespot.iot.core.VelocityDataOptionsBuf velocity = 13;</code>
   * @return The velocity.
   */
  @java.lang.Override public pt.sharespot.iot.core.buf.model.VelocityDataOptionsBuf getVelocity() {
    @SuppressWarnings("deprecation")
    pt.sharespot.iot.core.buf.model.VelocityDataOptionsBuf result = pt.sharespot.iot.core.buf.model.VelocityDataOptionsBuf.valueOf(velocity_);
    return result == null ? pt.sharespot.iot.core.buf.model.VelocityDataOptionsBuf.UNRECOGNIZED : result;
  }

  public static final int AIR_PRESSURE_FIELD_NUMBER = 14;
  private int airPressure_;
  /**
   * <code>.pt.sharespot.iot.core.AirPressureDataOptionsBuf air_pressure = 14;</code>
   * @return The enum numeric value on the wire for airPressure.
   */
  @java.lang.Override public int getAirPressureValue() {
    return airPressure_;
  }
  /**
   * <code>.pt.sharespot.iot.core.AirPressureDataOptionsBuf air_pressure = 14;</code>
   * @return The airPressure.
   */
  @java.lang.Override public pt.sharespot.iot.core.buf.model.AirPressureDataOptionsBuf getAirPressure() {
    @SuppressWarnings("deprecation")
    pt.sharespot.iot.core.buf.model.AirPressureDataOptionsBuf result = pt.sharespot.iot.core.buf.model.AirPressureDataOptionsBuf.valueOf(airPressure_);
    return result == null ? pt.sharespot.iot.core.buf.model.AirPressureDataOptionsBuf.UNRECOGNIZED : result;
  }

  public static final int BATTERY_FIELD_NUMBER = 15;
  private int battery_;
  /**
   * <code>.pt.sharespot.iot.core.BatteryDataOptionsBuf battery = 15;</code>
   * @return The enum numeric value on the wire for battery.
   */
  @java.lang.Override public int getBatteryValue() {
    return battery_;
  }
  /**
   * <code>.pt.sharespot.iot.core.BatteryDataOptionsBuf battery = 15;</code>
   * @return The battery.
   */
  @java.lang.Override public pt.sharespot.iot.core.buf.model.BatteryDataOptionsBuf getBattery() {
    @SuppressWarnings("deprecation")
    pt.sharespot.iot.core.buf.model.BatteryDataOptionsBuf result = pt.sharespot.iot.core.buf.model.BatteryDataOptionsBuf.valueOf(battery_);
    return result == null ? pt.sharespot.iot.core.buf.model.BatteryDataOptionsBuf.UNRECOGNIZED : result;
  }

  public static final int SOIL_MOISTURE_FIELD_NUMBER = 16;
  private int soilMoisture_;
  /**
   * <code>.pt.sharespot.iot.core.SoilMoistureDataOptionsBuf soil_moisture = 16;</code>
   * @return The enum numeric value on the wire for soilMoisture.
   */
  @java.lang.Override public int getSoilMoistureValue() {
    return soilMoisture_;
  }
  /**
   * <code>.pt.sharespot.iot.core.SoilMoistureDataOptionsBuf soil_moisture = 16;</code>
   * @return The soilMoisture.
   */
  @java.lang.Override public pt.sharespot.iot.core.buf.model.SoilMoistureDataOptionsBuf getSoilMoisture() {
    @SuppressWarnings("deprecation")
    pt.sharespot.iot.core.buf.model.SoilMoistureDataOptionsBuf result = pt.sharespot.iot.core.buf.model.SoilMoistureDataOptionsBuf.valueOf(soilMoisture_);
    return result == null ? pt.sharespot.iot.core.buf.model.SoilMoistureDataOptionsBuf.UNRECOGNIZED : result;
  }

  public static final int ILLUMINANCE_FIELD_NUMBER = 17;
  private int illuminance_;
  /**
   * <code>.pt.sharespot.iot.core.IlluminanceDataOptionsBuf illuminance = 17;</code>
   * @return The enum numeric value on the wire for illuminance.
   */
  @java.lang.Override public int getIlluminanceValue() {
    return illuminance_;
  }
  /**
   * <code>.pt.sharespot.iot.core.IlluminanceDataOptionsBuf illuminance = 17;</code>
   * @return The illuminance.
   */
  @java.lang.Override public pt.sharespot.iot.core.buf.model.IlluminanceDataOptionsBuf getIlluminance() {
    @SuppressWarnings("deprecation")
    pt.sharespot.iot.core.buf.model.IlluminanceDataOptionsBuf result = pt.sharespot.iot.core.buf.model.IlluminanceDataOptionsBuf.valueOf(illuminance_);
    return result == null ? pt.sharespot.iot.core.buf.model.IlluminanceDataOptionsBuf.UNRECOGNIZED : result;
  }

  public static final int OWNERSHIP_FIELD_NUMBER = 18;
  private int ownership_;
  /**
   * <code>.pt.sharespot.iot.core.DomainOwnershipOptionsBuf ownership = 18;</code>
   * @return The enum numeric value on the wire for ownership.
   */
  @java.lang.Override public int getOwnershipValue() {
    return ownership_;
  }
  /**
   * <code>.pt.sharespot.iot.core.DomainOwnershipOptionsBuf ownership = 18;</code>
   * @return The ownership.
   */
  @java.lang.Override public pt.sharespot.iot.core.buf.model.DomainOwnershipOptionsBuf getOwnership() {
    @SuppressWarnings("deprecation")
    pt.sharespot.iot.core.buf.model.DomainOwnershipOptionsBuf result = pt.sharespot.iot.core.buf.model.DomainOwnershipOptionsBuf.valueOf(ownership_);
    return result == null ? pt.sharespot.iot.core.buf.model.DomainOwnershipOptionsBuf.UNRECOGNIZED : result;
  }

  public static final int TRIGGER_FIELD_NUMBER = 19;
  private int trigger_;
  /**
   * <code>.pt.sharespot.iot.core.TriggerDataOptionsBuf trigger = 19;</code>
   * @return The enum numeric value on the wire for trigger.
   */
  @java.lang.Override public int getTriggerValue() {
    return trigger_;
  }
  /**
   * <code>.pt.sharespot.iot.core.TriggerDataOptionsBuf trigger = 19;</code>
   * @return The trigger.
   */
  @java.lang.Override public pt.sharespot.iot.core.buf.model.TriggerDataOptionsBuf getTrigger() {
    @SuppressWarnings("deprecation")
    pt.sharespot.iot.core.buf.model.TriggerDataOptionsBuf result = pt.sharespot.iot.core.buf.model.TriggerDataOptionsBuf.valueOf(trigger_);
    return result == null ? pt.sharespot.iot.core.buf.model.TriggerDataOptionsBuf.UNRECOGNIZED : result;
  }

  public static final int WATER_PRESSURE_FIELD_NUMBER = 20;
  private int waterPressure_;
  /**
   * <code>.pt.sharespot.iot.core.WaterPressureDataOptions water_pressure = 20;</code>
   * @return The enum numeric value on the wire for waterPressure.
   */
  @java.lang.Override public int getWaterPressureValue() {
    return waterPressure_;
  }
  /**
   * <code>.pt.sharespot.iot.core.WaterPressureDataOptions water_pressure = 20;</code>
   * @return The waterPressure.
   */
  @java.lang.Override public pt.sharespot.iot.core.buf.model.WaterPressureDataOptions getWaterPressure() {
    @SuppressWarnings("deprecation")
    pt.sharespot.iot.core.buf.model.WaterPressureDataOptions result = pt.sharespot.iot.core.buf.model.WaterPressureDataOptions.valueOf(waterPressure_);
    return result == null ? pt.sharespot.iot.core.buf.model.WaterPressureDataOptions.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(version_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, version_);
    }
    if (containerType_ != pt.sharespot.iot.core.buf.model.ContainerTypeOptionsBuf.OTHER.getNumber()) {
      output.writeEnum(2, containerType_);
    }
    if (infoType_ != pt.sharespot.iot.core.buf.model.InfoTypeOptionsBuf.ENCODED.getNumber()) {
      output.writeEnum(3, infoType_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sensorType_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, sensorType_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(channel_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, channel_);
    }
    if (records_ != pt.sharespot.iot.core.buf.model.RecordsOptionsBuf.UNIDENTIFIED_RECORDS.getNumber()) {
      output.writeEnum(6, records_);
    }
    if (gps_ != pt.sharespot.iot.core.buf.model.GPSDataOptionsBuf.UNIDENTIFIED_GPS_DATA.getNumber()) {
      output.writeEnum(7, gps_);
    }
    if (temperature_ != pt.sharespot.iot.core.buf.model.TemperatureDataOptionsBuf.UNIDENTIFIED_TEMPERATURE_DATA.getNumber()) {
      output.writeEnum(8, temperature_);
    }
    if (legitimacy_ != pt.sharespot.iot.core.buf.model.DataLegitimacyOptionsBuf.UNKNOWN_LEGITIMACY.getNumber()) {
      output.writeEnum(9, legitimacy_);
    }
    if (aqi_ != pt.sharespot.iot.core.buf.model.AirQualityDataOptionsBuf.UNIDENTIFIED_AQI_DATA.getNumber()) {
      output.writeEnum(10, aqi_);
    }
    if (airHumidity_ != pt.sharespot.iot.core.buf.model.AirHumidityDataOptionsBuf.UNIDENTIFIED_AIR_HUMIDITY_DATA.getNumber()) {
      output.writeEnum(11, airHumidity_);
    }
    if (motion_ != pt.sharespot.iot.core.buf.model.MotionDataOptionsBuf.UNIDENTIFIED_MOTION_DATA.getNumber()) {
      output.writeEnum(12, motion_);
    }
    if (velocity_ != pt.sharespot.iot.core.buf.model.VelocityDataOptionsBuf.UNIDENTIFIED_VELOCITY_DATA.getNumber()) {
      output.writeEnum(13, velocity_);
    }
    if (airPressure_ != pt.sharespot.iot.core.buf.model.AirPressureDataOptionsBuf.UNIDENTIFIED_AIR_PRESSURE_DATA.getNumber()) {
      output.writeEnum(14, airPressure_);
    }
    if (battery_ != pt.sharespot.iot.core.buf.model.BatteryDataOptionsBuf.UNIDENTIFIED_BATTERY_DATA.getNumber()) {
      output.writeEnum(15, battery_);
    }
    if (soilMoisture_ != pt.sharespot.iot.core.buf.model.SoilMoistureDataOptionsBuf.UNIDENTIFIED_SOIL_MOISTURE_DATA.getNumber()) {
      output.writeEnum(16, soilMoisture_);
    }
    if (illuminance_ != pt.sharespot.iot.core.buf.model.IlluminanceDataOptionsBuf.UNIDENTIFIED_ILLUMINANCE_DATA.getNumber()) {
      output.writeEnum(17, illuminance_);
    }
    if (ownership_ != pt.sharespot.iot.core.buf.model.DomainOwnershipOptionsBuf.UNIDENTIFIED_DOMAIN_OWNERSHIP.getNumber()) {
      output.writeEnum(18, ownership_);
    }
    if (trigger_ != pt.sharespot.iot.core.buf.model.TriggerDataOptionsBuf.UNIDENTIFIED_TRIGGER_DATA.getNumber()) {
      output.writeEnum(19, trigger_);
    }
    if (waterPressure_ != pt.sharespot.iot.core.buf.model.WaterPressureDataOptions.UNIDENTIFIED_WATER_PRESSURE_DATA.getNumber()) {
      output.writeEnum(20, waterPressure_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(version_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, version_);
    }
    if (containerType_ != pt.sharespot.iot.core.buf.model.ContainerTypeOptionsBuf.OTHER.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, containerType_);
    }
    if (infoType_ != pt.sharespot.iot.core.buf.model.InfoTypeOptionsBuf.ENCODED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, infoType_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sensorType_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, sensorType_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(channel_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, channel_);
    }
    if (records_ != pt.sharespot.iot.core.buf.model.RecordsOptionsBuf.UNIDENTIFIED_RECORDS.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(6, records_);
    }
    if (gps_ != pt.sharespot.iot.core.buf.model.GPSDataOptionsBuf.UNIDENTIFIED_GPS_DATA.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(7, gps_);
    }
    if (temperature_ != pt.sharespot.iot.core.buf.model.TemperatureDataOptionsBuf.UNIDENTIFIED_TEMPERATURE_DATA.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(8, temperature_);
    }
    if (legitimacy_ != pt.sharespot.iot.core.buf.model.DataLegitimacyOptionsBuf.UNKNOWN_LEGITIMACY.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(9, legitimacy_);
    }
    if (aqi_ != pt.sharespot.iot.core.buf.model.AirQualityDataOptionsBuf.UNIDENTIFIED_AQI_DATA.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(10, aqi_);
    }
    if (airHumidity_ != pt.sharespot.iot.core.buf.model.AirHumidityDataOptionsBuf.UNIDENTIFIED_AIR_HUMIDITY_DATA.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(11, airHumidity_);
    }
    if (motion_ != pt.sharespot.iot.core.buf.model.MotionDataOptionsBuf.UNIDENTIFIED_MOTION_DATA.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(12, motion_);
    }
    if (velocity_ != pt.sharespot.iot.core.buf.model.VelocityDataOptionsBuf.UNIDENTIFIED_VELOCITY_DATA.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(13, velocity_);
    }
    if (airPressure_ != pt.sharespot.iot.core.buf.model.AirPressureDataOptionsBuf.UNIDENTIFIED_AIR_PRESSURE_DATA.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(14, airPressure_);
    }
    if (battery_ != pt.sharespot.iot.core.buf.model.BatteryDataOptionsBuf.UNIDENTIFIED_BATTERY_DATA.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(15, battery_);
    }
    if (soilMoisture_ != pt.sharespot.iot.core.buf.model.SoilMoistureDataOptionsBuf.UNIDENTIFIED_SOIL_MOISTURE_DATA.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(16, soilMoisture_);
    }
    if (illuminance_ != pt.sharespot.iot.core.buf.model.IlluminanceDataOptionsBuf.UNIDENTIFIED_ILLUMINANCE_DATA.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(17, illuminance_);
    }
    if (ownership_ != pt.sharespot.iot.core.buf.model.DomainOwnershipOptionsBuf.UNIDENTIFIED_DOMAIN_OWNERSHIP.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(18, ownership_);
    }
    if (trigger_ != pt.sharespot.iot.core.buf.model.TriggerDataOptionsBuf.UNIDENTIFIED_TRIGGER_DATA.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(19, trigger_);
    }
    if (waterPressure_ != pt.sharespot.iot.core.buf.model.WaterPressureDataOptions.UNIDENTIFIED_WATER_PRESSURE_DATA.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(20, waterPressure_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof pt.sharespot.iot.core.buf.model.RoutingKeysBuf)) {
      return super.equals(obj);
    }
    pt.sharespot.iot.core.buf.model.RoutingKeysBuf other = (pt.sharespot.iot.core.buf.model.RoutingKeysBuf) obj;

    if (!getVersion()
        .equals(other.getVersion())) return false;
    if (containerType_ != other.containerType_) return false;
    if (infoType_ != other.infoType_) return false;
    if (!getSensorType()
        .equals(other.getSensorType())) return false;
    if (!getChannel()
        .equals(other.getChannel())) return false;
    if (records_ != other.records_) return false;
    if (gps_ != other.gps_) return false;
    if (temperature_ != other.temperature_) return false;
    if (legitimacy_ != other.legitimacy_) return false;
    if (aqi_ != other.aqi_) return false;
    if (airHumidity_ != other.airHumidity_) return false;
    if (motion_ != other.motion_) return false;
    if (velocity_ != other.velocity_) return false;
    if (airPressure_ != other.airPressure_) return false;
    if (battery_ != other.battery_) return false;
    if (soilMoisture_ != other.soilMoisture_) return false;
    if (illuminance_ != other.illuminance_) return false;
    if (ownership_ != other.ownership_) return false;
    if (trigger_ != other.trigger_) return false;
    if (waterPressure_ != other.waterPressure_) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getVersion().hashCode();
    hash = (37 * hash) + CONTAINER_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + containerType_;
    hash = (37 * hash) + INFO_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + infoType_;
    hash = (37 * hash) + SENSOR_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getSensorType().hashCode();
    hash = (37 * hash) + CHANNEL_FIELD_NUMBER;
    hash = (53 * hash) + getChannel().hashCode();
    hash = (37 * hash) + RECORDS_FIELD_NUMBER;
    hash = (53 * hash) + records_;
    hash = (37 * hash) + GPS_FIELD_NUMBER;
    hash = (53 * hash) + gps_;
    hash = (37 * hash) + TEMPERATURE_FIELD_NUMBER;
    hash = (53 * hash) + temperature_;
    hash = (37 * hash) + LEGITIMACY_FIELD_NUMBER;
    hash = (53 * hash) + legitimacy_;
    hash = (37 * hash) + AQI_FIELD_NUMBER;
    hash = (53 * hash) + aqi_;
    hash = (37 * hash) + AIR_HUMIDITY_FIELD_NUMBER;
    hash = (53 * hash) + airHumidity_;
    hash = (37 * hash) + MOTION_FIELD_NUMBER;
    hash = (53 * hash) + motion_;
    hash = (37 * hash) + VELOCITY_FIELD_NUMBER;
    hash = (53 * hash) + velocity_;
    hash = (37 * hash) + AIR_PRESSURE_FIELD_NUMBER;
    hash = (53 * hash) + airPressure_;
    hash = (37 * hash) + BATTERY_FIELD_NUMBER;
    hash = (53 * hash) + battery_;
    hash = (37 * hash) + SOIL_MOISTURE_FIELD_NUMBER;
    hash = (53 * hash) + soilMoisture_;
    hash = (37 * hash) + ILLUMINANCE_FIELD_NUMBER;
    hash = (53 * hash) + illuminance_;
    hash = (37 * hash) + OWNERSHIP_FIELD_NUMBER;
    hash = (53 * hash) + ownership_;
    hash = (37 * hash) + TRIGGER_FIELD_NUMBER;
    hash = (53 * hash) + trigger_;
    hash = (37 * hash) + WATER_PRESSURE_FIELD_NUMBER;
    hash = (53 * hash) + waterPressure_;
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static pt.sharespot.iot.core.buf.model.RoutingKeysBuf parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static pt.sharespot.iot.core.buf.model.RoutingKeysBuf parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static pt.sharespot.iot.core.buf.model.RoutingKeysBuf parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static pt.sharespot.iot.core.buf.model.RoutingKeysBuf parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static pt.sharespot.iot.core.buf.model.RoutingKeysBuf parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static pt.sharespot.iot.core.buf.model.RoutingKeysBuf parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static pt.sharespot.iot.core.buf.model.RoutingKeysBuf parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static pt.sharespot.iot.core.buf.model.RoutingKeysBuf parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static pt.sharespot.iot.core.buf.model.RoutingKeysBuf parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static pt.sharespot.iot.core.buf.model.RoutingKeysBuf parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static pt.sharespot.iot.core.buf.model.RoutingKeysBuf parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static pt.sharespot.iot.core.buf.model.RoutingKeysBuf parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(pt.sharespot.iot.core.buf.model.RoutingKeysBuf prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code pt.sharespot.iot.core.RoutingKeysBuf}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:pt.sharespot.iot.core.RoutingKeysBuf)
      pt.sharespot.iot.core.buf.model.RoutingKeysBufOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pt.sharespot.iot.core.buf.model.MessageOuterClass.internal_static_pt_sharespot_iot_core_RoutingKeysBuf_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pt.sharespot.iot.core.buf.model.MessageOuterClass.internal_static_pt_sharespot_iot_core_RoutingKeysBuf_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pt.sharespot.iot.core.buf.model.RoutingKeysBuf.class, pt.sharespot.iot.core.buf.model.RoutingKeysBuf.Builder.class);
    }

    // Construct using pt.sharespot.iot.core.buf.model.RoutingKeysBuf.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      version_ = "";

      containerType_ = 0;

      infoType_ = 0;

      sensorType_ = "";

      channel_ = "";

      records_ = 0;

      gps_ = 0;

      temperature_ = 0;

      legitimacy_ = 0;

      aqi_ = 0;

      airHumidity_ = 0;

      motion_ = 0;

      velocity_ = 0;

      airPressure_ = 0;

      battery_ = 0;

      soilMoisture_ = 0;

      illuminance_ = 0;

      ownership_ = 0;

      trigger_ = 0;

      waterPressure_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return pt.sharespot.iot.core.buf.model.MessageOuterClass.internal_static_pt_sharespot_iot_core_RoutingKeysBuf_descriptor;
    }

    @java.lang.Override
    public pt.sharespot.iot.core.buf.model.RoutingKeysBuf getDefaultInstanceForType() {
      return pt.sharespot.iot.core.buf.model.RoutingKeysBuf.getDefaultInstance();
    }

    @java.lang.Override
    public pt.sharespot.iot.core.buf.model.RoutingKeysBuf build() {
      pt.sharespot.iot.core.buf.model.RoutingKeysBuf result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public pt.sharespot.iot.core.buf.model.RoutingKeysBuf buildPartial() {
      pt.sharespot.iot.core.buf.model.RoutingKeysBuf result = new pt.sharespot.iot.core.buf.model.RoutingKeysBuf(this);
      result.version_ = version_;
      result.containerType_ = containerType_;
      result.infoType_ = infoType_;
      result.sensorType_ = sensorType_;
      result.channel_ = channel_;
      result.records_ = records_;
      result.gps_ = gps_;
      result.temperature_ = temperature_;
      result.legitimacy_ = legitimacy_;
      result.aqi_ = aqi_;
      result.airHumidity_ = airHumidity_;
      result.motion_ = motion_;
      result.velocity_ = velocity_;
      result.airPressure_ = airPressure_;
      result.battery_ = battery_;
      result.soilMoisture_ = soilMoisture_;
      result.illuminance_ = illuminance_;
      result.ownership_ = ownership_;
      result.trigger_ = trigger_;
      result.waterPressure_ = waterPressure_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof pt.sharespot.iot.core.buf.model.RoutingKeysBuf) {
        return mergeFrom((pt.sharespot.iot.core.buf.model.RoutingKeysBuf)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(pt.sharespot.iot.core.buf.model.RoutingKeysBuf other) {
      if (other == pt.sharespot.iot.core.buf.model.RoutingKeysBuf.getDefaultInstance()) return this;
      if (!other.getVersion().isEmpty()) {
        version_ = other.version_;
        onChanged();
      }
      if (other.containerType_ != 0) {
        setContainerTypeValue(other.getContainerTypeValue());
      }
      if (other.infoType_ != 0) {
        setInfoTypeValue(other.getInfoTypeValue());
      }
      if (!other.getSensorType().isEmpty()) {
        sensorType_ = other.sensorType_;
        onChanged();
      }
      if (!other.getChannel().isEmpty()) {
        channel_ = other.channel_;
        onChanged();
      }
      if (other.records_ != 0) {
        setRecordsValue(other.getRecordsValue());
      }
      if (other.gps_ != 0) {
        setGpsValue(other.getGpsValue());
      }
      if (other.temperature_ != 0) {
        setTemperatureValue(other.getTemperatureValue());
      }
      if (other.legitimacy_ != 0) {
        setLegitimacyValue(other.getLegitimacyValue());
      }
      if (other.aqi_ != 0) {
        setAqiValue(other.getAqiValue());
      }
      if (other.airHumidity_ != 0) {
        setAirHumidityValue(other.getAirHumidityValue());
      }
      if (other.motion_ != 0) {
        setMotionValue(other.getMotionValue());
      }
      if (other.velocity_ != 0) {
        setVelocityValue(other.getVelocityValue());
      }
      if (other.airPressure_ != 0) {
        setAirPressureValue(other.getAirPressureValue());
      }
      if (other.battery_ != 0) {
        setBatteryValue(other.getBatteryValue());
      }
      if (other.soilMoisture_ != 0) {
        setSoilMoistureValue(other.getSoilMoistureValue());
      }
      if (other.illuminance_ != 0) {
        setIlluminanceValue(other.getIlluminanceValue());
      }
      if (other.ownership_ != 0) {
        setOwnershipValue(other.getOwnershipValue());
      }
      if (other.trigger_ != 0) {
        setTriggerValue(other.getTriggerValue());
      }
      if (other.waterPressure_ != 0) {
        setWaterPressureValue(other.getWaterPressureValue());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      pt.sharespot.iot.core.buf.model.RoutingKeysBuf parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (pt.sharespot.iot.core.buf.model.RoutingKeysBuf) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object version_ = "";
    /**
     * <code>string version = 1;</code>
     * @return The version.
     */
    public java.lang.String getVersion() {
      java.lang.Object ref = version_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        version_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string version = 1;</code>
     * @return The bytes for version.
     */
    public com.google.protobuf.ByteString
        getVersionBytes() {
      java.lang.Object ref = version_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        version_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string version = 1;</code>
     * @param value The version to set.
     * @return This builder for chaining.
     */
    public Builder setVersion(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      version_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string version = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearVersion() {
      
      version_ = getDefaultInstance().getVersion();
      onChanged();
      return this;
    }
    /**
     * <code>string version = 1;</code>
     * @param value The bytes for version to set.
     * @return This builder for chaining.
     */
    public Builder setVersionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      version_ = value;
      onChanged();
      return this;
    }

    private int containerType_ = 0;
    /**
     * <code>.pt.sharespot.iot.core.ContainerTypeOptionsBuf container_type = 2;</code>
     * @return The enum numeric value on the wire for containerType.
     */
    @java.lang.Override public int getContainerTypeValue() {
      return containerType_;
    }
    /**
     * <code>.pt.sharespot.iot.core.ContainerTypeOptionsBuf container_type = 2;</code>
     * @param value The enum numeric value on the wire for containerType to set.
     * @return This builder for chaining.
     */
    public Builder setContainerTypeValue(int value) {
      
      containerType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.pt.sharespot.iot.core.ContainerTypeOptionsBuf container_type = 2;</code>
     * @return The containerType.
     */
    @java.lang.Override
    public pt.sharespot.iot.core.buf.model.ContainerTypeOptionsBuf getContainerType() {
      @SuppressWarnings("deprecation")
      pt.sharespot.iot.core.buf.model.ContainerTypeOptionsBuf result = pt.sharespot.iot.core.buf.model.ContainerTypeOptionsBuf.valueOf(containerType_);
      return result == null ? pt.sharespot.iot.core.buf.model.ContainerTypeOptionsBuf.UNRECOGNIZED : result;
    }
    /**
     * <code>.pt.sharespot.iot.core.ContainerTypeOptionsBuf container_type = 2;</code>
     * @param value The containerType to set.
     * @return This builder for chaining.
     */
    public Builder setContainerType(pt.sharespot.iot.core.buf.model.ContainerTypeOptionsBuf value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      containerType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.pt.sharespot.iot.core.ContainerTypeOptionsBuf container_type = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearContainerType() {
      
      containerType_ = 0;
      onChanged();
      return this;
    }

    private int infoType_ = 0;
    /**
     * <code>.pt.sharespot.iot.core.InfoTypeOptionsBuf info_type = 3;</code>
     * @return The enum numeric value on the wire for infoType.
     */
    @java.lang.Override public int getInfoTypeValue() {
      return infoType_;
    }
    /**
     * <code>.pt.sharespot.iot.core.InfoTypeOptionsBuf info_type = 3;</code>
     * @param value The enum numeric value on the wire for infoType to set.
     * @return This builder for chaining.
     */
    public Builder setInfoTypeValue(int value) {
      
      infoType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.pt.sharespot.iot.core.InfoTypeOptionsBuf info_type = 3;</code>
     * @return The infoType.
     */
    @java.lang.Override
    public pt.sharespot.iot.core.buf.model.InfoTypeOptionsBuf getInfoType() {
      @SuppressWarnings("deprecation")
      pt.sharespot.iot.core.buf.model.InfoTypeOptionsBuf result = pt.sharespot.iot.core.buf.model.InfoTypeOptionsBuf.valueOf(infoType_);
      return result == null ? pt.sharespot.iot.core.buf.model.InfoTypeOptionsBuf.UNRECOGNIZED : result;
    }
    /**
     * <code>.pt.sharespot.iot.core.InfoTypeOptionsBuf info_type = 3;</code>
     * @param value The infoType to set.
     * @return This builder for chaining.
     */
    public Builder setInfoType(pt.sharespot.iot.core.buf.model.InfoTypeOptionsBuf value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      infoType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.pt.sharespot.iot.core.InfoTypeOptionsBuf info_type = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearInfoType() {
      
      infoType_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object sensorType_ = "";
    /**
     * <code>string sensor_type = 4;</code>
     * @return The sensorType.
     */
    public java.lang.String getSensorType() {
      java.lang.Object ref = sensorType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sensorType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string sensor_type = 4;</code>
     * @return The bytes for sensorType.
     */
    public com.google.protobuf.ByteString
        getSensorTypeBytes() {
      java.lang.Object ref = sensorType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sensorType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string sensor_type = 4;</code>
     * @param value The sensorType to set.
     * @return This builder for chaining.
     */
    public Builder setSensorType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      sensorType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string sensor_type = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearSensorType() {
      
      sensorType_ = getDefaultInstance().getSensorType();
      onChanged();
      return this;
    }
    /**
     * <code>string sensor_type = 4;</code>
     * @param value The bytes for sensorType to set.
     * @return This builder for chaining.
     */
    public Builder setSensorTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      sensorType_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object channel_ = "";
    /**
     * <code>string channel = 5;</code>
     * @return The channel.
     */
    public java.lang.String getChannel() {
      java.lang.Object ref = channel_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        channel_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string channel = 5;</code>
     * @return The bytes for channel.
     */
    public com.google.protobuf.ByteString
        getChannelBytes() {
      java.lang.Object ref = channel_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        channel_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string channel = 5;</code>
     * @param value The channel to set.
     * @return This builder for chaining.
     */
    public Builder setChannel(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      channel_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string channel = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearChannel() {
      
      channel_ = getDefaultInstance().getChannel();
      onChanged();
      return this;
    }
    /**
     * <code>string channel = 5;</code>
     * @param value The bytes for channel to set.
     * @return This builder for chaining.
     */
    public Builder setChannelBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      channel_ = value;
      onChanged();
      return this;
    }

    private int records_ = 0;
    /**
     * <code>.pt.sharespot.iot.core.RecordsOptionsBuf records = 6;</code>
     * @return The enum numeric value on the wire for records.
     */
    @java.lang.Override public int getRecordsValue() {
      return records_;
    }
    /**
     * <code>.pt.sharespot.iot.core.RecordsOptionsBuf records = 6;</code>
     * @param value The enum numeric value on the wire for records to set.
     * @return This builder for chaining.
     */
    public Builder setRecordsValue(int value) {
      
      records_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.pt.sharespot.iot.core.RecordsOptionsBuf records = 6;</code>
     * @return The records.
     */
    @java.lang.Override
    public pt.sharespot.iot.core.buf.model.RecordsOptionsBuf getRecords() {
      @SuppressWarnings("deprecation")
      pt.sharespot.iot.core.buf.model.RecordsOptionsBuf result = pt.sharespot.iot.core.buf.model.RecordsOptionsBuf.valueOf(records_);
      return result == null ? pt.sharespot.iot.core.buf.model.RecordsOptionsBuf.UNRECOGNIZED : result;
    }
    /**
     * <code>.pt.sharespot.iot.core.RecordsOptionsBuf records = 6;</code>
     * @param value The records to set.
     * @return This builder for chaining.
     */
    public Builder setRecords(pt.sharespot.iot.core.buf.model.RecordsOptionsBuf value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      records_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.pt.sharespot.iot.core.RecordsOptionsBuf records = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearRecords() {
      
      records_ = 0;
      onChanged();
      return this;
    }

    private int gps_ = 0;
    /**
     * <code>.pt.sharespot.iot.core.GPSDataOptionsBuf gps = 7;</code>
     * @return The enum numeric value on the wire for gps.
     */
    @java.lang.Override public int getGpsValue() {
      return gps_;
    }
    /**
     * <code>.pt.sharespot.iot.core.GPSDataOptionsBuf gps = 7;</code>
     * @param value The enum numeric value on the wire for gps to set.
     * @return This builder for chaining.
     */
    public Builder setGpsValue(int value) {
      
      gps_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.pt.sharespot.iot.core.GPSDataOptionsBuf gps = 7;</code>
     * @return The gps.
     */
    @java.lang.Override
    public pt.sharespot.iot.core.buf.model.GPSDataOptionsBuf getGps() {
      @SuppressWarnings("deprecation")
      pt.sharespot.iot.core.buf.model.GPSDataOptionsBuf result = pt.sharespot.iot.core.buf.model.GPSDataOptionsBuf.valueOf(gps_);
      return result == null ? pt.sharespot.iot.core.buf.model.GPSDataOptionsBuf.UNRECOGNIZED : result;
    }
    /**
     * <code>.pt.sharespot.iot.core.GPSDataOptionsBuf gps = 7;</code>
     * @param value The gps to set.
     * @return This builder for chaining.
     */
    public Builder setGps(pt.sharespot.iot.core.buf.model.GPSDataOptionsBuf value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      gps_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.pt.sharespot.iot.core.GPSDataOptionsBuf gps = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearGps() {
      
      gps_ = 0;
      onChanged();
      return this;
    }

    private int temperature_ = 0;
    /**
     * <code>.pt.sharespot.iot.core.TemperatureDataOptionsBuf temperature = 8;</code>
     * @return The enum numeric value on the wire for temperature.
     */
    @java.lang.Override public int getTemperatureValue() {
      return temperature_;
    }
    /**
     * <code>.pt.sharespot.iot.core.TemperatureDataOptionsBuf temperature = 8;</code>
     * @param value The enum numeric value on the wire for temperature to set.
     * @return This builder for chaining.
     */
    public Builder setTemperatureValue(int value) {
      
      temperature_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.pt.sharespot.iot.core.TemperatureDataOptionsBuf temperature = 8;</code>
     * @return The temperature.
     */
    @java.lang.Override
    public pt.sharespot.iot.core.buf.model.TemperatureDataOptionsBuf getTemperature() {
      @SuppressWarnings("deprecation")
      pt.sharespot.iot.core.buf.model.TemperatureDataOptionsBuf result = pt.sharespot.iot.core.buf.model.TemperatureDataOptionsBuf.valueOf(temperature_);
      return result == null ? pt.sharespot.iot.core.buf.model.TemperatureDataOptionsBuf.UNRECOGNIZED : result;
    }
    /**
     * <code>.pt.sharespot.iot.core.TemperatureDataOptionsBuf temperature = 8;</code>
     * @param value The temperature to set.
     * @return This builder for chaining.
     */
    public Builder setTemperature(pt.sharespot.iot.core.buf.model.TemperatureDataOptionsBuf value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      temperature_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.pt.sharespot.iot.core.TemperatureDataOptionsBuf temperature = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearTemperature() {
      
      temperature_ = 0;
      onChanged();
      return this;
    }

    private int legitimacy_ = 0;
    /**
     * <code>.pt.sharespot.iot.core.DataLegitimacyOptionsBuf legitimacy = 9;</code>
     * @return The enum numeric value on the wire for legitimacy.
     */
    @java.lang.Override public int getLegitimacyValue() {
      return legitimacy_;
    }
    /**
     * <code>.pt.sharespot.iot.core.DataLegitimacyOptionsBuf legitimacy = 9;</code>
     * @param value The enum numeric value on the wire for legitimacy to set.
     * @return This builder for chaining.
     */
    public Builder setLegitimacyValue(int value) {
      
      legitimacy_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.pt.sharespot.iot.core.DataLegitimacyOptionsBuf legitimacy = 9;</code>
     * @return The legitimacy.
     */
    @java.lang.Override
    public pt.sharespot.iot.core.buf.model.DataLegitimacyOptionsBuf getLegitimacy() {
      @SuppressWarnings("deprecation")
      pt.sharespot.iot.core.buf.model.DataLegitimacyOptionsBuf result = pt.sharespot.iot.core.buf.model.DataLegitimacyOptionsBuf.valueOf(legitimacy_);
      return result == null ? pt.sharespot.iot.core.buf.model.DataLegitimacyOptionsBuf.UNRECOGNIZED : result;
    }
    /**
     * <code>.pt.sharespot.iot.core.DataLegitimacyOptionsBuf legitimacy = 9;</code>
     * @param value The legitimacy to set.
     * @return This builder for chaining.
     */
    public Builder setLegitimacy(pt.sharespot.iot.core.buf.model.DataLegitimacyOptionsBuf value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      legitimacy_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.pt.sharespot.iot.core.DataLegitimacyOptionsBuf legitimacy = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearLegitimacy() {
      
      legitimacy_ = 0;
      onChanged();
      return this;
    }

    private int aqi_ = 0;
    /**
     * <code>.pt.sharespot.iot.core.AirQualityDataOptionsBuf aqi = 10;</code>
     * @return The enum numeric value on the wire for aqi.
     */
    @java.lang.Override public int getAqiValue() {
      return aqi_;
    }
    /**
     * <code>.pt.sharespot.iot.core.AirQualityDataOptionsBuf aqi = 10;</code>
     * @param value The enum numeric value on the wire for aqi to set.
     * @return This builder for chaining.
     */
    public Builder setAqiValue(int value) {
      
      aqi_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.pt.sharespot.iot.core.AirQualityDataOptionsBuf aqi = 10;</code>
     * @return The aqi.
     */
    @java.lang.Override
    public pt.sharespot.iot.core.buf.model.AirQualityDataOptionsBuf getAqi() {
      @SuppressWarnings("deprecation")
      pt.sharespot.iot.core.buf.model.AirQualityDataOptionsBuf result = pt.sharespot.iot.core.buf.model.AirQualityDataOptionsBuf.valueOf(aqi_);
      return result == null ? pt.sharespot.iot.core.buf.model.AirQualityDataOptionsBuf.UNRECOGNIZED : result;
    }
    /**
     * <code>.pt.sharespot.iot.core.AirQualityDataOptionsBuf aqi = 10;</code>
     * @param value The aqi to set.
     * @return This builder for chaining.
     */
    public Builder setAqi(pt.sharespot.iot.core.buf.model.AirQualityDataOptionsBuf value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      aqi_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.pt.sharespot.iot.core.AirQualityDataOptionsBuf aqi = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearAqi() {
      
      aqi_ = 0;
      onChanged();
      return this;
    }

    private int airHumidity_ = 0;
    /**
     * <code>.pt.sharespot.iot.core.AirHumidityDataOptionsBuf air_humidity = 11;</code>
     * @return The enum numeric value on the wire for airHumidity.
     */
    @java.lang.Override public int getAirHumidityValue() {
      return airHumidity_;
    }
    /**
     * <code>.pt.sharespot.iot.core.AirHumidityDataOptionsBuf air_humidity = 11;</code>
     * @param value The enum numeric value on the wire for airHumidity to set.
     * @return This builder for chaining.
     */
    public Builder setAirHumidityValue(int value) {
      
      airHumidity_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.pt.sharespot.iot.core.AirHumidityDataOptionsBuf air_humidity = 11;</code>
     * @return The airHumidity.
     */
    @java.lang.Override
    public pt.sharespot.iot.core.buf.model.AirHumidityDataOptionsBuf getAirHumidity() {
      @SuppressWarnings("deprecation")
      pt.sharespot.iot.core.buf.model.AirHumidityDataOptionsBuf result = pt.sharespot.iot.core.buf.model.AirHumidityDataOptionsBuf.valueOf(airHumidity_);
      return result == null ? pt.sharespot.iot.core.buf.model.AirHumidityDataOptionsBuf.UNRECOGNIZED : result;
    }
    /**
     * <code>.pt.sharespot.iot.core.AirHumidityDataOptionsBuf air_humidity = 11;</code>
     * @param value The airHumidity to set.
     * @return This builder for chaining.
     */
    public Builder setAirHumidity(pt.sharespot.iot.core.buf.model.AirHumidityDataOptionsBuf value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      airHumidity_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.pt.sharespot.iot.core.AirHumidityDataOptionsBuf air_humidity = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearAirHumidity() {
      
      airHumidity_ = 0;
      onChanged();
      return this;
    }

    private int motion_ = 0;
    /**
     * <code>.pt.sharespot.iot.core.MotionDataOptionsBuf motion = 12;</code>
     * @return The enum numeric value on the wire for motion.
     */
    @java.lang.Override public int getMotionValue() {
      return motion_;
    }
    /**
     * <code>.pt.sharespot.iot.core.MotionDataOptionsBuf motion = 12;</code>
     * @param value The enum numeric value on the wire for motion to set.
     * @return This builder for chaining.
     */
    public Builder setMotionValue(int value) {
      
      motion_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.pt.sharespot.iot.core.MotionDataOptionsBuf motion = 12;</code>
     * @return The motion.
     */
    @java.lang.Override
    public pt.sharespot.iot.core.buf.model.MotionDataOptionsBuf getMotion() {
      @SuppressWarnings("deprecation")
      pt.sharespot.iot.core.buf.model.MotionDataOptionsBuf result = pt.sharespot.iot.core.buf.model.MotionDataOptionsBuf.valueOf(motion_);
      return result == null ? pt.sharespot.iot.core.buf.model.MotionDataOptionsBuf.UNRECOGNIZED : result;
    }
    /**
     * <code>.pt.sharespot.iot.core.MotionDataOptionsBuf motion = 12;</code>
     * @param value The motion to set.
     * @return This builder for chaining.
     */
    public Builder setMotion(pt.sharespot.iot.core.buf.model.MotionDataOptionsBuf value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      motion_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.pt.sharespot.iot.core.MotionDataOptionsBuf motion = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearMotion() {
      
      motion_ = 0;
      onChanged();
      return this;
    }

    private int velocity_ = 0;
    /**
     * <code>.pt.sharespot.iot.core.VelocityDataOptionsBuf velocity = 13;</code>
     * @return The enum numeric value on the wire for velocity.
     */
    @java.lang.Override public int getVelocityValue() {
      return velocity_;
    }
    /**
     * <code>.pt.sharespot.iot.core.VelocityDataOptionsBuf velocity = 13;</code>
     * @param value The enum numeric value on the wire for velocity to set.
     * @return This builder for chaining.
     */
    public Builder setVelocityValue(int value) {
      
      velocity_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.pt.sharespot.iot.core.VelocityDataOptionsBuf velocity = 13;</code>
     * @return The velocity.
     */
    @java.lang.Override
    public pt.sharespot.iot.core.buf.model.VelocityDataOptionsBuf getVelocity() {
      @SuppressWarnings("deprecation")
      pt.sharespot.iot.core.buf.model.VelocityDataOptionsBuf result = pt.sharespot.iot.core.buf.model.VelocityDataOptionsBuf.valueOf(velocity_);
      return result == null ? pt.sharespot.iot.core.buf.model.VelocityDataOptionsBuf.UNRECOGNIZED : result;
    }
    /**
     * <code>.pt.sharespot.iot.core.VelocityDataOptionsBuf velocity = 13;</code>
     * @param value The velocity to set.
     * @return This builder for chaining.
     */
    public Builder setVelocity(pt.sharespot.iot.core.buf.model.VelocityDataOptionsBuf value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      velocity_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.pt.sharespot.iot.core.VelocityDataOptionsBuf velocity = 13;</code>
     * @return This builder for chaining.
     */
    public Builder clearVelocity() {
      
      velocity_ = 0;
      onChanged();
      return this;
    }

    private int airPressure_ = 0;
    /**
     * <code>.pt.sharespot.iot.core.AirPressureDataOptionsBuf air_pressure = 14;</code>
     * @return The enum numeric value on the wire for airPressure.
     */
    @java.lang.Override public int getAirPressureValue() {
      return airPressure_;
    }
    /**
     * <code>.pt.sharespot.iot.core.AirPressureDataOptionsBuf air_pressure = 14;</code>
     * @param value The enum numeric value on the wire for airPressure to set.
     * @return This builder for chaining.
     */
    public Builder setAirPressureValue(int value) {
      
      airPressure_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.pt.sharespot.iot.core.AirPressureDataOptionsBuf air_pressure = 14;</code>
     * @return The airPressure.
     */
    @java.lang.Override
    public pt.sharespot.iot.core.buf.model.AirPressureDataOptionsBuf getAirPressure() {
      @SuppressWarnings("deprecation")
      pt.sharespot.iot.core.buf.model.AirPressureDataOptionsBuf result = pt.sharespot.iot.core.buf.model.AirPressureDataOptionsBuf.valueOf(airPressure_);
      return result == null ? pt.sharespot.iot.core.buf.model.AirPressureDataOptionsBuf.UNRECOGNIZED : result;
    }
    /**
     * <code>.pt.sharespot.iot.core.AirPressureDataOptionsBuf air_pressure = 14;</code>
     * @param value The airPressure to set.
     * @return This builder for chaining.
     */
    public Builder setAirPressure(pt.sharespot.iot.core.buf.model.AirPressureDataOptionsBuf value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      airPressure_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.pt.sharespot.iot.core.AirPressureDataOptionsBuf air_pressure = 14;</code>
     * @return This builder for chaining.
     */
    public Builder clearAirPressure() {
      
      airPressure_ = 0;
      onChanged();
      return this;
    }

    private int battery_ = 0;
    /**
     * <code>.pt.sharespot.iot.core.BatteryDataOptionsBuf battery = 15;</code>
     * @return The enum numeric value on the wire for battery.
     */
    @java.lang.Override public int getBatteryValue() {
      return battery_;
    }
    /**
     * <code>.pt.sharespot.iot.core.BatteryDataOptionsBuf battery = 15;</code>
     * @param value The enum numeric value on the wire for battery to set.
     * @return This builder for chaining.
     */
    public Builder setBatteryValue(int value) {
      
      battery_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.pt.sharespot.iot.core.BatteryDataOptionsBuf battery = 15;</code>
     * @return The battery.
     */
    @java.lang.Override
    public pt.sharespot.iot.core.buf.model.BatteryDataOptionsBuf getBattery() {
      @SuppressWarnings("deprecation")
      pt.sharespot.iot.core.buf.model.BatteryDataOptionsBuf result = pt.sharespot.iot.core.buf.model.BatteryDataOptionsBuf.valueOf(battery_);
      return result == null ? pt.sharespot.iot.core.buf.model.BatteryDataOptionsBuf.UNRECOGNIZED : result;
    }
    /**
     * <code>.pt.sharespot.iot.core.BatteryDataOptionsBuf battery = 15;</code>
     * @param value The battery to set.
     * @return This builder for chaining.
     */
    public Builder setBattery(pt.sharespot.iot.core.buf.model.BatteryDataOptionsBuf value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      battery_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.pt.sharespot.iot.core.BatteryDataOptionsBuf battery = 15;</code>
     * @return This builder for chaining.
     */
    public Builder clearBattery() {
      
      battery_ = 0;
      onChanged();
      return this;
    }

    private int soilMoisture_ = 0;
    /**
     * <code>.pt.sharespot.iot.core.SoilMoistureDataOptionsBuf soil_moisture = 16;</code>
     * @return The enum numeric value on the wire for soilMoisture.
     */
    @java.lang.Override public int getSoilMoistureValue() {
      return soilMoisture_;
    }
    /**
     * <code>.pt.sharespot.iot.core.SoilMoistureDataOptionsBuf soil_moisture = 16;</code>
     * @param value The enum numeric value on the wire for soilMoisture to set.
     * @return This builder for chaining.
     */
    public Builder setSoilMoistureValue(int value) {
      
      soilMoisture_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.pt.sharespot.iot.core.SoilMoistureDataOptionsBuf soil_moisture = 16;</code>
     * @return The soilMoisture.
     */
    @java.lang.Override
    public pt.sharespot.iot.core.buf.model.SoilMoistureDataOptionsBuf getSoilMoisture() {
      @SuppressWarnings("deprecation")
      pt.sharespot.iot.core.buf.model.SoilMoistureDataOptionsBuf result = pt.sharespot.iot.core.buf.model.SoilMoistureDataOptionsBuf.valueOf(soilMoisture_);
      return result == null ? pt.sharespot.iot.core.buf.model.SoilMoistureDataOptionsBuf.UNRECOGNIZED : result;
    }
    /**
     * <code>.pt.sharespot.iot.core.SoilMoistureDataOptionsBuf soil_moisture = 16;</code>
     * @param value The soilMoisture to set.
     * @return This builder for chaining.
     */
    public Builder setSoilMoisture(pt.sharespot.iot.core.buf.model.SoilMoistureDataOptionsBuf value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      soilMoisture_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.pt.sharespot.iot.core.SoilMoistureDataOptionsBuf soil_moisture = 16;</code>
     * @return This builder for chaining.
     */
    public Builder clearSoilMoisture() {
      
      soilMoisture_ = 0;
      onChanged();
      return this;
    }

    private int illuminance_ = 0;
    /**
     * <code>.pt.sharespot.iot.core.IlluminanceDataOptionsBuf illuminance = 17;</code>
     * @return The enum numeric value on the wire for illuminance.
     */
    @java.lang.Override public int getIlluminanceValue() {
      return illuminance_;
    }
    /**
     * <code>.pt.sharespot.iot.core.IlluminanceDataOptionsBuf illuminance = 17;</code>
     * @param value The enum numeric value on the wire for illuminance to set.
     * @return This builder for chaining.
     */
    public Builder setIlluminanceValue(int value) {
      
      illuminance_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.pt.sharespot.iot.core.IlluminanceDataOptionsBuf illuminance = 17;</code>
     * @return The illuminance.
     */
    @java.lang.Override
    public pt.sharespot.iot.core.buf.model.IlluminanceDataOptionsBuf getIlluminance() {
      @SuppressWarnings("deprecation")
      pt.sharespot.iot.core.buf.model.IlluminanceDataOptionsBuf result = pt.sharespot.iot.core.buf.model.IlluminanceDataOptionsBuf.valueOf(illuminance_);
      return result == null ? pt.sharespot.iot.core.buf.model.IlluminanceDataOptionsBuf.UNRECOGNIZED : result;
    }
    /**
     * <code>.pt.sharespot.iot.core.IlluminanceDataOptionsBuf illuminance = 17;</code>
     * @param value The illuminance to set.
     * @return This builder for chaining.
     */
    public Builder setIlluminance(pt.sharespot.iot.core.buf.model.IlluminanceDataOptionsBuf value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      illuminance_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.pt.sharespot.iot.core.IlluminanceDataOptionsBuf illuminance = 17;</code>
     * @return This builder for chaining.
     */
    public Builder clearIlluminance() {
      
      illuminance_ = 0;
      onChanged();
      return this;
    }

    private int ownership_ = 0;
    /**
     * <code>.pt.sharespot.iot.core.DomainOwnershipOptionsBuf ownership = 18;</code>
     * @return The enum numeric value on the wire for ownership.
     */
    @java.lang.Override public int getOwnershipValue() {
      return ownership_;
    }
    /**
     * <code>.pt.sharespot.iot.core.DomainOwnershipOptionsBuf ownership = 18;</code>
     * @param value The enum numeric value on the wire for ownership to set.
     * @return This builder for chaining.
     */
    public Builder setOwnershipValue(int value) {
      
      ownership_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.pt.sharespot.iot.core.DomainOwnershipOptionsBuf ownership = 18;</code>
     * @return The ownership.
     */
    @java.lang.Override
    public pt.sharespot.iot.core.buf.model.DomainOwnershipOptionsBuf getOwnership() {
      @SuppressWarnings("deprecation")
      pt.sharespot.iot.core.buf.model.DomainOwnershipOptionsBuf result = pt.sharespot.iot.core.buf.model.DomainOwnershipOptionsBuf.valueOf(ownership_);
      return result == null ? pt.sharespot.iot.core.buf.model.DomainOwnershipOptionsBuf.UNRECOGNIZED : result;
    }
    /**
     * <code>.pt.sharespot.iot.core.DomainOwnershipOptionsBuf ownership = 18;</code>
     * @param value The ownership to set.
     * @return This builder for chaining.
     */
    public Builder setOwnership(pt.sharespot.iot.core.buf.model.DomainOwnershipOptionsBuf value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      ownership_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.pt.sharespot.iot.core.DomainOwnershipOptionsBuf ownership = 18;</code>
     * @return This builder for chaining.
     */
    public Builder clearOwnership() {
      
      ownership_ = 0;
      onChanged();
      return this;
    }

    private int trigger_ = 0;
    /**
     * <code>.pt.sharespot.iot.core.TriggerDataOptionsBuf trigger = 19;</code>
     * @return The enum numeric value on the wire for trigger.
     */
    @java.lang.Override public int getTriggerValue() {
      return trigger_;
    }
    /**
     * <code>.pt.sharespot.iot.core.TriggerDataOptionsBuf trigger = 19;</code>
     * @param value The enum numeric value on the wire for trigger to set.
     * @return This builder for chaining.
     */
    public Builder setTriggerValue(int value) {
      
      trigger_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.pt.sharespot.iot.core.TriggerDataOptionsBuf trigger = 19;</code>
     * @return The trigger.
     */
    @java.lang.Override
    public pt.sharespot.iot.core.buf.model.TriggerDataOptionsBuf getTrigger() {
      @SuppressWarnings("deprecation")
      pt.sharespot.iot.core.buf.model.TriggerDataOptionsBuf result = pt.sharespot.iot.core.buf.model.TriggerDataOptionsBuf.valueOf(trigger_);
      return result == null ? pt.sharespot.iot.core.buf.model.TriggerDataOptionsBuf.UNRECOGNIZED : result;
    }
    /**
     * <code>.pt.sharespot.iot.core.TriggerDataOptionsBuf trigger = 19;</code>
     * @param value The trigger to set.
     * @return This builder for chaining.
     */
    public Builder setTrigger(pt.sharespot.iot.core.buf.model.TriggerDataOptionsBuf value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      trigger_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.pt.sharespot.iot.core.TriggerDataOptionsBuf trigger = 19;</code>
     * @return This builder for chaining.
     */
    public Builder clearTrigger() {
      
      trigger_ = 0;
      onChanged();
      return this;
    }

    private int waterPressure_ = 0;
    /**
     * <code>.pt.sharespot.iot.core.WaterPressureDataOptions water_pressure = 20;</code>
     * @return The enum numeric value on the wire for waterPressure.
     */
    @java.lang.Override public int getWaterPressureValue() {
      return waterPressure_;
    }
    /**
     * <code>.pt.sharespot.iot.core.WaterPressureDataOptions water_pressure = 20;</code>
     * @param value The enum numeric value on the wire for waterPressure to set.
     * @return This builder for chaining.
     */
    public Builder setWaterPressureValue(int value) {
      
      waterPressure_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.pt.sharespot.iot.core.WaterPressureDataOptions water_pressure = 20;</code>
     * @return The waterPressure.
     */
    @java.lang.Override
    public pt.sharespot.iot.core.buf.model.WaterPressureDataOptions getWaterPressure() {
      @SuppressWarnings("deprecation")
      pt.sharespot.iot.core.buf.model.WaterPressureDataOptions result = pt.sharespot.iot.core.buf.model.WaterPressureDataOptions.valueOf(waterPressure_);
      return result == null ? pt.sharespot.iot.core.buf.model.WaterPressureDataOptions.UNRECOGNIZED : result;
    }
    /**
     * <code>.pt.sharespot.iot.core.WaterPressureDataOptions water_pressure = 20;</code>
     * @param value The waterPressure to set.
     * @return This builder for chaining.
     */
    public Builder setWaterPressure(pt.sharespot.iot.core.buf.model.WaterPressureDataOptions value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      waterPressure_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.pt.sharespot.iot.core.WaterPressureDataOptions water_pressure = 20;</code>
     * @return This builder for chaining.
     */
    public Builder clearWaterPressure() {
      
      waterPressure_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:pt.sharespot.iot.core.RoutingKeysBuf)
  }

  // @@protoc_insertion_point(class_scope:pt.sharespot.iot.core.RoutingKeysBuf)
  private static final pt.sharespot.iot.core.buf.model.RoutingKeysBuf DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new pt.sharespot.iot.core.buf.model.RoutingKeysBuf();
  }

  public static pt.sharespot.iot.core.buf.model.RoutingKeysBuf getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RoutingKeysBuf>
      PARSER = new com.google.protobuf.AbstractParser<RoutingKeysBuf>() {
    @java.lang.Override
    public RoutingKeysBuf parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new RoutingKeysBuf(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<RoutingKeysBuf> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RoutingKeysBuf> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public pt.sharespot.iot.core.buf.model.RoutingKeysBuf getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

