// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/message.proto

package pt.sharespot.iot.core.buf.model;

public interface SensorDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pt.sharespot.iot.core.SensorData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.pt.sharespot.iot.core.GPS gps = 1;</code>
   * @return Whether the gps field is set.
   */
  boolean hasGps();
  /**
   * <code>.pt.sharespot.iot.core.GPS gps = 1;</code>
   * @return The gps.
   */
  pt.sharespot.iot.core.buf.model.GPS getGps();
  /**
   * <code>.pt.sharespot.iot.core.GPS gps = 1;</code>
   */
  pt.sharespot.iot.core.buf.model.GPSOrBuilder getGpsOrBuilder();

  /**
   * <code>.pt.sharespot.iot.core.Temperature temperature = 2;</code>
   * @return Whether the temperature field is set.
   */
  boolean hasTemperature();
  /**
   * <code>.pt.sharespot.iot.core.Temperature temperature = 2;</code>
   * @return The temperature.
   */
  pt.sharespot.iot.core.buf.model.Temperature getTemperature();
  /**
   * <code>.pt.sharespot.iot.core.Temperature temperature = 2;</code>
   */
  pt.sharespot.iot.core.buf.model.TemperatureOrBuilder getTemperatureOrBuilder();

  /**
   * <code>.pt.sharespot.iot.core.Motion motion = 3;</code>
   * @return Whether the motion field is set.
   */
  boolean hasMotion();
  /**
   * <code>.pt.sharespot.iot.core.Motion motion = 3;</code>
   * @return The motion.
   */
  pt.sharespot.iot.core.buf.model.Motion getMotion();
  /**
   * <code>.pt.sharespot.iot.core.Motion motion = 3;</code>
   */
  pt.sharespot.iot.core.buf.model.MotionOrBuilder getMotionOrBuilder();

  /**
   * <code>.pt.sharespot.iot.core.AirQuality aqi = 4;</code>
   * @return Whether the aqi field is set.
   */
  boolean hasAqi();
  /**
   * <code>.pt.sharespot.iot.core.AirQuality aqi = 4;</code>
   * @return The aqi.
   */
  pt.sharespot.iot.core.buf.model.AirQuality getAqi();
  /**
   * <code>.pt.sharespot.iot.core.AirQuality aqi = 4;</code>
   */
  pt.sharespot.iot.core.buf.model.AirQualityOrBuilder getAqiOrBuilder();

  /**
   * <code>.pt.sharespot.iot.core.Velocity velocity = 5;</code>
   * @return Whether the velocity field is set.
   */
  boolean hasVelocity();
  /**
   * <code>.pt.sharespot.iot.core.Velocity velocity = 5;</code>
   * @return The velocity.
   */
  pt.sharespot.iot.core.buf.model.Velocity getVelocity();
  /**
   * <code>.pt.sharespot.iot.core.Velocity velocity = 5;</code>
   */
  pt.sharespot.iot.core.buf.model.VelocityOrBuilder getVelocityOrBuilder();

  /**
   * <code>.pt.sharespot.iot.core.Humidity humidity = 6;</code>
   * @return Whether the humidity field is set.
   */
  boolean hasHumidity();
  /**
   * <code>.pt.sharespot.iot.core.Humidity humidity = 6;</code>
   * @return The humidity.
   */
  pt.sharespot.iot.core.buf.model.Humidity getHumidity();
  /**
   * <code>.pt.sharespot.iot.core.Humidity humidity = 6;</code>
   */
  pt.sharespot.iot.core.buf.model.HumidityOrBuilder getHumidityOrBuilder();

  /**
   * <code>.pt.sharespot.iot.core.Pressure pressure = 7;</code>
   * @return Whether the pressure field is set.
   */
  boolean hasPressure();
  /**
   * <code>.pt.sharespot.iot.core.Pressure pressure = 7;</code>
   * @return The pressure.
   */
  pt.sharespot.iot.core.buf.model.Pressure getPressure();
  /**
   * <code>.pt.sharespot.iot.core.Pressure pressure = 7;</code>
   */
  pt.sharespot.iot.core.buf.model.PressureOrBuilder getPressureOrBuilder();

  /**
   * <code>.pt.sharespot.iot.core.Battery battery = 8;</code>
   * @return Whether the battery field is set.
   */
  boolean hasBattery();
  /**
   * <code>.pt.sharespot.iot.core.Battery battery = 8;</code>
   * @return The battery.
   */
  pt.sharespot.iot.core.buf.model.Battery getBattery();
  /**
   * <code>.pt.sharespot.iot.core.Battery battery = 8;</code>
   */
  pt.sharespot.iot.core.buf.model.BatteryOrBuilder getBatteryOrBuilder();

  /**
   * <code>.pt.sharespot.iot.core.SoilMoisture moisture = 9;</code>
   * @return Whether the moisture field is set.
   */
  boolean hasMoisture();
  /**
   * <code>.pt.sharespot.iot.core.SoilMoisture moisture = 9;</code>
   * @return The moisture.
   */
  pt.sharespot.iot.core.buf.model.SoilMoisture getMoisture();
  /**
   * <code>.pt.sharespot.iot.core.SoilMoisture moisture = 9;</code>
   */
  pt.sharespot.iot.core.buf.model.SoilMoistureOrBuilder getMoistureOrBuilder();

  /**
   * <code>.pt.sharespot.iot.core.Illuminance illuminance = 10;</code>
   * @return Whether the illuminance field is set.
   */
  boolean hasIlluminance();
  /**
   * <code>.pt.sharespot.iot.core.Illuminance illuminance = 10;</code>
   * @return The illuminance.
   */
  pt.sharespot.iot.core.buf.model.Illuminance getIlluminance();
  /**
   * <code>.pt.sharespot.iot.core.Illuminance illuminance = 10;</code>
   */
  pt.sharespot.iot.core.buf.model.IlluminanceOrBuilder getIlluminanceOrBuilder();

  /**
   * <code>.pt.sharespot.iot.core.Alarm alarm = 11;</code>
   * @return Whether the alarm field is set.
   */
  boolean hasAlarm();
  /**
   * <code>.pt.sharespot.iot.core.Alarm alarm = 11;</code>
   * @return The alarm.
   */
  pt.sharespot.iot.core.buf.model.Alarm getAlarm();
  /**
   * <code>.pt.sharespot.iot.core.Alarm alarm = 11;</code>
   */
  pt.sharespot.iot.core.buf.model.AlarmOrBuilder getAlarmOrBuilder();
}
