// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/message.proto

package pt.sharespot.iot.core.buf.model;

/**
 * Protobuf type {@code pt.sharespot.iot.core.SensorData}
 */
public final class SensorData extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:pt.sharespot.iot.core.SensorData)
    SensorDataOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SensorData.newBuilder() to construct.
  private SensorData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SensorData() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new SensorData();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private SensorData(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            pt.sharespot.iot.core.buf.model.GPS.Builder subBuilder = null;
            if (gps_ != null) {
              subBuilder = gps_.toBuilder();
            }
            gps_ = input.readMessage(pt.sharespot.iot.core.buf.model.GPS.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(gps_);
              gps_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            pt.sharespot.iot.core.buf.model.Temperature.Builder subBuilder = null;
            if (temperature_ != null) {
              subBuilder = temperature_.toBuilder();
            }
            temperature_ = input.readMessage(pt.sharespot.iot.core.buf.model.Temperature.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(temperature_);
              temperature_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            pt.sharespot.iot.core.buf.model.Motion.Builder subBuilder = null;
            if (motion_ != null) {
              subBuilder = motion_.toBuilder();
            }
            motion_ = input.readMessage(pt.sharespot.iot.core.buf.model.Motion.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(motion_);
              motion_ = subBuilder.buildPartial();
            }

            break;
          }
          case 34: {
            pt.sharespot.iot.core.buf.model.AirQuality.Builder subBuilder = null;
            if (aqi_ != null) {
              subBuilder = aqi_.toBuilder();
            }
            aqi_ = input.readMessage(pt.sharespot.iot.core.buf.model.AirQuality.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(aqi_);
              aqi_ = subBuilder.buildPartial();
            }

            break;
          }
          case 42: {
            pt.sharespot.iot.core.buf.model.Velocity.Builder subBuilder = null;
            if (velocity_ != null) {
              subBuilder = velocity_.toBuilder();
            }
            velocity_ = input.readMessage(pt.sharespot.iot.core.buf.model.Velocity.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(velocity_);
              velocity_ = subBuilder.buildPartial();
            }

            break;
          }
          case 50: {
            pt.sharespot.iot.core.buf.model.AirHumidity.Builder subBuilder = null;
            if (airHumidity_ != null) {
              subBuilder = airHumidity_.toBuilder();
            }
            airHumidity_ = input.readMessage(pt.sharespot.iot.core.buf.model.AirHumidity.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(airHumidity_);
              airHumidity_ = subBuilder.buildPartial();
            }

            break;
          }
          case 58: {
            pt.sharespot.iot.core.buf.model.AirPressure.Builder subBuilder = null;
            if (airPressure_ != null) {
              subBuilder = airPressure_.toBuilder();
            }
            airPressure_ = input.readMessage(pt.sharespot.iot.core.buf.model.AirPressure.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(airPressure_);
              airPressure_ = subBuilder.buildPartial();
            }

            break;
          }
          case 66: {
            pt.sharespot.iot.core.buf.model.Battery.Builder subBuilder = null;
            if (battery_ != null) {
              subBuilder = battery_.toBuilder();
            }
            battery_ = input.readMessage(pt.sharespot.iot.core.buf.model.Battery.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(battery_);
              battery_ = subBuilder.buildPartial();
            }

            break;
          }
          case 74: {
            pt.sharespot.iot.core.buf.model.SoilMoisture.Builder subBuilder = null;
            if (soilMoisture_ != null) {
              subBuilder = soilMoisture_.toBuilder();
            }
            soilMoisture_ = input.readMessage(pt.sharespot.iot.core.buf.model.SoilMoisture.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(soilMoisture_);
              soilMoisture_ = subBuilder.buildPartial();
            }

            break;
          }
          case 82: {
            pt.sharespot.iot.core.buf.model.Illuminance.Builder subBuilder = null;
            if (illuminance_ != null) {
              subBuilder = illuminance_.toBuilder();
            }
            illuminance_ = input.readMessage(pt.sharespot.iot.core.buf.model.Illuminance.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(illuminance_);
              illuminance_ = subBuilder.buildPartial();
            }

            break;
          }
          case 90: {
            pt.sharespot.iot.core.buf.model.Trigger.Builder subBuilder = null;
            if (trigger_ != null) {
              subBuilder = trigger_.toBuilder();
            }
            trigger_ = input.readMessage(pt.sharespot.iot.core.buf.model.Trigger.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(trigger_);
              trigger_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return pt.sharespot.iot.core.buf.model.MessageOuterClass.internal_static_pt_sharespot_iot_core_SensorData_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return pt.sharespot.iot.core.buf.model.MessageOuterClass.internal_static_pt_sharespot_iot_core_SensorData_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            pt.sharespot.iot.core.buf.model.SensorData.class, pt.sharespot.iot.core.buf.model.SensorData.Builder.class);
  }

  public static final int GPS_FIELD_NUMBER = 1;
  private pt.sharespot.iot.core.buf.model.GPS gps_;
  /**
   * <code>.pt.sharespot.iot.core.GPS gps = 1;</code>
   * @return Whether the gps field is set.
   */
  @java.lang.Override
  public boolean hasGps() {
    return gps_ != null;
  }
  /**
   * <code>.pt.sharespot.iot.core.GPS gps = 1;</code>
   * @return The gps.
   */
  @java.lang.Override
  public pt.sharespot.iot.core.buf.model.GPS getGps() {
    return gps_ == null ? pt.sharespot.iot.core.buf.model.GPS.getDefaultInstance() : gps_;
  }
  /**
   * <code>.pt.sharespot.iot.core.GPS gps = 1;</code>
   */
  @java.lang.Override
  public pt.sharespot.iot.core.buf.model.GPSOrBuilder getGpsOrBuilder() {
    return getGps();
  }

  public static final int TEMPERATURE_FIELD_NUMBER = 2;
  private pt.sharespot.iot.core.buf.model.Temperature temperature_;
  /**
   * <code>.pt.sharespot.iot.core.Temperature temperature = 2;</code>
   * @return Whether the temperature field is set.
   */
  @java.lang.Override
  public boolean hasTemperature() {
    return temperature_ != null;
  }
  /**
   * <code>.pt.sharespot.iot.core.Temperature temperature = 2;</code>
   * @return The temperature.
   */
  @java.lang.Override
  public pt.sharespot.iot.core.buf.model.Temperature getTemperature() {
    return temperature_ == null ? pt.sharespot.iot.core.buf.model.Temperature.getDefaultInstance() : temperature_;
  }
  /**
   * <code>.pt.sharespot.iot.core.Temperature temperature = 2;</code>
   */
  @java.lang.Override
  public pt.sharespot.iot.core.buf.model.TemperatureOrBuilder getTemperatureOrBuilder() {
    return getTemperature();
  }

  public static final int MOTION_FIELD_NUMBER = 3;
  private pt.sharespot.iot.core.buf.model.Motion motion_;
  /**
   * <code>.pt.sharespot.iot.core.Motion motion = 3;</code>
   * @return Whether the motion field is set.
   */
  @java.lang.Override
  public boolean hasMotion() {
    return motion_ != null;
  }
  /**
   * <code>.pt.sharespot.iot.core.Motion motion = 3;</code>
   * @return The motion.
   */
  @java.lang.Override
  public pt.sharespot.iot.core.buf.model.Motion getMotion() {
    return motion_ == null ? pt.sharespot.iot.core.buf.model.Motion.getDefaultInstance() : motion_;
  }
  /**
   * <code>.pt.sharespot.iot.core.Motion motion = 3;</code>
   */
  @java.lang.Override
  public pt.sharespot.iot.core.buf.model.MotionOrBuilder getMotionOrBuilder() {
    return getMotion();
  }

  public static final int AQI_FIELD_NUMBER = 4;
  private pt.sharespot.iot.core.buf.model.AirQuality aqi_;
  /**
   * <code>.pt.sharespot.iot.core.AirQuality aqi = 4;</code>
   * @return Whether the aqi field is set.
   */
  @java.lang.Override
  public boolean hasAqi() {
    return aqi_ != null;
  }
  /**
   * <code>.pt.sharespot.iot.core.AirQuality aqi = 4;</code>
   * @return The aqi.
   */
  @java.lang.Override
  public pt.sharespot.iot.core.buf.model.AirQuality getAqi() {
    return aqi_ == null ? pt.sharespot.iot.core.buf.model.AirQuality.getDefaultInstance() : aqi_;
  }
  /**
   * <code>.pt.sharespot.iot.core.AirQuality aqi = 4;</code>
   */
  @java.lang.Override
  public pt.sharespot.iot.core.buf.model.AirQualityOrBuilder getAqiOrBuilder() {
    return getAqi();
  }

  public static final int VELOCITY_FIELD_NUMBER = 5;
  private pt.sharespot.iot.core.buf.model.Velocity velocity_;
  /**
   * <code>.pt.sharespot.iot.core.Velocity velocity = 5;</code>
   * @return Whether the velocity field is set.
   */
  @java.lang.Override
  public boolean hasVelocity() {
    return velocity_ != null;
  }
  /**
   * <code>.pt.sharespot.iot.core.Velocity velocity = 5;</code>
   * @return The velocity.
   */
  @java.lang.Override
  public pt.sharespot.iot.core.buf.model.Velocity getVelocity() {
    return velocity_ == null ? pt.sharespot.iot.core.buf.model.Velocity.getDefaultInstance() : velocity_;
  }
  /**
   * <code>.pt.sharespot.iot.core.Velocity velocity = 5;</code>
   */
  @java.lang.Override
  public pt.sharespot.iot.core.buf.model.VelocityOrBuilder getVelocityOrBuilder() {
    return getVelocity();
  }

  public static final int AIR_HUMIDITY_FIELD_NUMBER = 6;
  private pt.sharespot.iot.core.buf.model.AirHumidity airHumidity_;
  /**
   * <code>.pt.sharespot.iot.core.AirHumidity air_humidity = 6;</code>
   * @return Whether the airHumidity field is set.
   */
  @java.lang.Override
  public boolean hasAirHumidity() {
    return airHumidity_ != null;
  }
  /**
   * <code>.pt.sharespot.iot.core.AirHumidity air_humidity = 6;</code>
   * @return The airHumidity.
   */
  @java.lang.Override
  public pt.sharespot.iot.core.buf.model.AirHumidity getAirHumidity() {
    return airHumidity_ == null ? pt.sharespot.iot.core.buf.model.AirHumidity.getDefaultInstance() : airHumidity_;
  }
  /**
   * <code>.pt.sharespot.iot.core.AirHumidity air_humidity = 6;</code>
   */
  @java.lang.Override
  public pt.sharespot.iot.core.buf.model.AirHumidityOrBuilder getAirHumidityOrBuilder() {
    return getAirHumidity();
  }

  public static final int AIR_PRESSURE_FIELD_NUMBER = 7;
  private pt.sharespot.iot.core.buf.model.AirPressure airPressure_;
  /**
   * <code>.pt.sharespot.iot.core.AirPressure air_pressure = 7;</code>
   * @return Whether the airPressure field is set.
   */
  @java.lang.Override
  public boolean hasAirPressure() {
    return airPressure_ != null;
  }
  /**
   * <code>.pt.sharespot.iot.core.AirPressure air_pressure = 7;</code>
   * @return The airPressure.
   */
  @java.lang.Override
  public pt.sharespot.iot.core.buf.model.AirPressure getAirPressure() {
    return airPressure_ == null ? pt.sharespot.iot.core.buf.model.AirPressure.getDefaultInstance() : airPressure_;
  }
  /**
   * <code>.pt.sharespot.iot.core.AirPressure air_pressure = 7;</code>
   */
  @java.lang.Override
  public pt.sharespot.iot.core.buf.model.AirPressureOrBuilder getAirPressureOrBuilder() {
    return getAirPressure();
  }

  public static final int BATTERY_FIELD_NUMBER = 8;
  private pt.sharespot.iot.core.buf.model.Battery battery_;
  /**
   * <code>.pt.sharespot.iot.core.Battery battery = 8;</code>
   * @return Whether the battery field is set.
   */
  @java.lang.Override
  public boolean hasBattery() {
    return battery_ != null;
  }
  /**
   * <code>.pt.sharespot.iot.core.Battery battery = 8;</code>
   * @return The battery.
   */
  @java.lang.Override
  public pt.sharespot.iot.core.buf.model.Battery getBattery() {
    return battery_ == null ? pt.sharespot.iot.core.buf.model.Battery.getDefaultInstance() : battery_;
  }
  /**
   * <code>.pt.sharespot.iot.core.Battery battery = 8;</code>
   */
  @java.lang.Override
  public pt.sharespot.iot.core.buf.model.BatteryOrBuilder getBatteryOrBuilder() {
    return getBattery();
  }

  public static final int SOIL_MOISTURE_FIELD_NUMBER = 9;
  private pt.sharespot.iot.core.buf.model.SoilMoisture soilMoisture_;
  /**
   * <code>.pt.sharespot.iot.core.SoilMoisture soil_moisture = 9;</code>
   * @return Whether the soilMoisture field is set.
   */
  @java.lang.Override
  public boolean hasSoilMoisture() {
    return soilMoisture_ != null;
  }
  /**
   * <code>.pt.sharespot.iot.core.SoilMoisture soil_moisture = 9;</code>
   * @return The soilMoisture.
   */
  @java.lang.Override
  public pt.sharespot.iot.core.buf.model.SoilMoisture getSoilMoisture() {
    return soilMoisture_ == null ? pt.sharespot.iot.core.buf.model.SoilMoisture.getDefaultInstance() : soilMoisture_;
  }
  /**
   * <code>.pt.sharespot.iot.core.SoilMoisture soil_moisture = 9;</code>
   */
  @java.lang.Override
  public pt.sharespot.iot.core.buf.model.SoilMoistureOrBuilder getSoilMoistureOrBuilder() {
    return getSoilMoisture();
  }

  public static final int ILLUMINANCE_FIELD_NUMBER = 10;
  private pt.sharespot.iot.core.buf.model.Illuminance illuminance_;
  /**
   * <code>.pt.sharespot.iot.core.Illuminance illuminance = 10;</code>
   * @return Whether the illuminance field is set.
   */
  @java.lang.Override
  public boolean hasIlluminance() {
    return illuminance_ != null;
  }
  /**
   * <code>.pt.sharespot.iot.core.Illuminance illuminance = 10;</code>
   * @return The illuminance.
   */
  @java.lang.Override
  public pt.sharespot.iot.core.buf.model.Illuminance getIlluminance() {
    return illuminance_ == null ? pt.sharespot.iot.core.buf.model.Illuminance.getDefaultInstance() : illuminance_;
  }
  /**
   * <code>.pt.sharespot.iot.core.Illuminance illuminance = 10;</code>
   */
  @java.lang.Override
  public pt.sharespot.iot.core.buf.model.IlluminanceOrBuilder getIlluminanceOrBuilder() {
    return getIlluminance();
  }

  public static final int TRIGGER_FIELD_NUMBER = 11;
  private pt.sharespot.iot.core.buf.model.Trigger trigger_;
  /**
   * <code>.pt.sharespot.iot.core.Trigger trigger = 11;</code>
   * @return Whether the trigger field is set.
   */
  @java.lang.Override
  public boolean hasTrigger() {
    return trigger_ != null;
  }
  /**
   * <code>.pt.sharespot.iot.core.Trigger trigger = 11;</code>
   * @return The trigger.
   */
  @java.lang.Override
  public pt.sharespot.iot.core.buf.model.Trigger getTrigger() {
    return trigger_ == null ? pt.sharespot.iot.core.buf.model.Trigger.getDefaultInstance() : trigger_;
  }
  /**
   * <code>.pt.sharespot.iot.core.Trigger trigger = 11;</code>
   */
  @java.lang.Override
  public pt.sharespot.iot.core.buf.model.TriggerOrBuilder getTriggerOrBuilder() {
    return getTrigger();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (gps_ != null) {
      output.writeMessage(1, getGps());
    }
    if (temperature_ != null) {
      output.writeMessage(2, getTemperature());
    }
    if (motion_ != null) {
      output.writeMessage(3, getMotion());
    }
    if (aqi_ != null) {
      output.writeMessage(4, getAqi());
    }
    if (velocity_ != null) {
      output.writeMessage(5, getVelocity());
    }
    if (airHumidity_ != null) {
      output.writeMessage(6, getAirHumidity());
    }
    if (airPressure_ != null) {
      output.writeMessage(7, getAirPressure());
    }
    if (battery_ != null) {
      output.writeMessage(8, getBattery());
    }
    if (soilMoisture_ != null) {
      output.writeMessage(9, getSoilMoisture());
    }
    if (illuminance_ != null) {
      output.writeMessage(10, getIlluminance());
    }
    if (trigger_ != null) {
      output.writeMessage(11, getTrigger());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (gps_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getGps());
    }
    if (temperature_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getTemperature());
    }
    if (motion_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getMotion());
    }
    if (aqi_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getAqi());
    }
    if (velocity_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getVelocity());
    }
    if (airHumidity_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getAirHumidity());
    }
    if (airPressure_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, getAirPressure());
    }
    if (battery_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, getBattery());
    }
    if (soilMoisture_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(9, getSoilMoisture());
    }
    if (illuminance_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(10, getIlluminance());
    }
    if (trigger_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(11, getTrigger());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof pt.sharespot.iot.core.buf.model.SensorData)) {
      return super.equals(obj);
    }
    pt.sharespot.iot.core.buf.model.SensorData other = (pt.sharespot.iot.core.buf.model.SensorData) obj;

    if (hasGps() != other.hasGps()) return false;
    if (hasGps()) {
      if (!getGps()
          .equals(other.getGps())) return false;
    }
    if (hasTemperature() != other.hasTemperature()) return false;
    if (hasTemperature()) {
      if (!getTemperature()
          .equals(other.getTemperature())) return false;
    }
    if (hasMotion() != other.hasMotion()) return false;
    if (hasMotion()) {
      if (!getMotion()
          .equals(other.getMotion())) return false;
    }
    if (hasAqi() != other.hasAqi()) return false;
    if (hasAqi()) {
      if (!getAqi()
          .equals(other.getAqi())) return false;
    }
    if (hasVelocity() != other.hasVelocity()) return false;
    if (hasVelocity()) {
      if (!getVelocity()
          .equals(other.getVelocity())) return false;
    }
    if (hasAirHumidity() != other.hasAirHumidity()) return false;
    if (hasAirHumidity()) {
      if (!getAirHumidity()
          .equals(other.getAirHumidity())) return false;
    }
    if (hasAirPressure() != other.hasAirPressure()) return false;
    if (hasAirPressure()) {
      if (!getAirPressure()
          .equals(other.getAirPressure())) return false;
    }
    if (hasBattery() != other.hasBattery()) return false;
    if (hasBattery()) {
      if (!getBattery()
          .equals(other.getBattery())) return false;
    }
    if (hasSoilMoisture() != other.hasSoilMoisture()) return false;
    if (hasSoilMoisture()) {
      if (!getSoilMoisture()
          .equals(other.getSoilMoisture())) return false;
    }
    if (hasIlluminance() != other.hasIlluminance()) return false;
    if (hasIlluminance()) {
      if (!getIlluminance()
          .equals(other.getIlluminance())) return false;
    }
    if (hasTrigger() != other.hasTrigger()) return false;
    if (hasTrigger()) {
      if (!getTrigger()
          .equals(other.getTrigger())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasGps()) {
      hash = (37 * hash) + GPS_FIELD_NUMBER;
      hash = (53 * hash) + getGps().hashCode();
    }
    if (hasTemperature()) {
      hash = (37 * hash) + TEMPERATURE_FIELD_NUMBER;
      hash = (53 * hash) + getTemperature().hashCode();
    }
    if (hasMotion()) {
      hash = (37 * hash) + MOTION_FIELD_NUMBER;
      hash = (53 * hash) + getMotion().hashCode();
    }
    if (hasAqi()) {
      hash = (37 * hash) + AQI_FIELD_NUMBER;
      hash = (53 * hash) + getAqi().hashCode();
    }
    if (hasVelocity()) {
      hash = (37 * hash) + VELOCITY_FIELD_NUMBER;
      hash = (53 * hash) + getVelocity().hashCode();
    }
    if (hasAirHumidity()) {
      hash = (37 * hash) + AIR_HUMIDITY_FIELD_NUMBER;
      hash = (53 * hash) + getAirHumidity().hashCode();
    }
    if (hasAirPressure()) {
      hash = (37 * hash) + AIR_PRESSURE_FIELD_NUMBER;
      hash = (53 * hash) + getAirPressure().hashCode();
    }
    if (hasBattery()) {
      hash = (37 * hash) + BATTERY_FIELD_NUMBER;
      hash = (53 * hash) + getBattery().hashCode();
    }
    if (hasSoilMoisture()) {
      hash = (37 * hash) + SOIL_MOISTURE_FIELD_NUMBER;
      hash = (53 * hash) + getSoilMoisture().hashCode();
    }
    if (hasIlluminance()) {
      hash = (37 * hash) + ILLUMINANCE_FIELD_NUMBER;
      hash = (53 * hash) + getIlluminance().hashCode();
    }
    if (hasTrigger()) {
      hash = (37 * hash) + TRIGGER_FIELD_NUMBER;
      hash = (53 * hash) + getTrigger().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static pt.sharespot.iot.core.buf.model.SensorData parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static pt.sharespot.iot.core.buf.model.SensorData parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static pt.sharespot.iot.core.buf.model.SensorData parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static pt.sharespot.iot.core.buf.model.SensorData parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static pt.sharespot.iot.core.buf.model.SensorData parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static pt.sharespot.iot.core.buf.model.SensorData parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static pt.sharespot.iot.core.buf.model.SensorData parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static pt.sharespot.iot.core.buf.model.SensorData parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static pt.sharespot.iot.core.buf.model.SensorData parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static pt.sharespot.iot.core.buf.model.SensorData parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static pt.sharespot.iot.core.buf.model.SensorData parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static pt.sharespot.iot.core.buf.model.SensorData parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(pt.sharespot.iot.core.buf.model.SensorData prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code pt.sharespot.iot.core.SensorData}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:pt.sharespot.iot.core.SensorData)
      pt.sharespot.iot.core.buf.model.SensorDataOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pt.sharespot.iot.core.buf.model.MessageOuterClass.internal_static_pt_sharespot_iot_core_SensorData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pt.sharespot.iot.core.buf.model.MessageOuterClass.internal_static_pt_sharespot_iot_core_SensorData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pt.sharespot.iot.core.buf.model.SensorData.class, pt.sharespot.iot.core.buf.model.SensorData.Builder.class);
    }

    // Construct using pt.sharespot.iot.core.buf.model.SensorData.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (gpsBuilder_ == null) {
        gps_ = null;
      } else {
        gps_ = null;
        gpsBuilder_ = null;
      }
      if (temperatureBuilder_ == null) {
        temperature_ = null;
      } else {
        temperature_ = null;
        temperatureBuilder_ = null;
      }
      if (motionBuilder_ == null) {
        motion_ = null;
      } else {
        motion_ = null;
        motionBuilder_ = null;
      }
      if (aqiBuilder_ == null) {
        aqi_ = null;
      } else {
        aqi_ = null;
        aqiBuilder_ = null;
      }
      if (velocityBuilder_ == null) {
        velocity_ = null;
      } else {
        velocity_ = null;
        velocityBuilder_ = null;
      }
      if (airHumidityBuilder_ == null) {
        airHumidity_ = null;
      } else {
        airHumidity_ = null;
        airHumidityBuilder_ = null;
      }
      if (airPressureBuilder_ == null) {
        airPressure_ = null;
      } else {
        airPressure_ = null;
        airPressureBuilder_ = null;
      }
      if (batteryBuilder_ == null) {
        battery_ = null;
      } else {
        battery_ = null;
        batteryBuilder_ = null;
      }
      if (soilMoistureBuilder_ == null) {
        soilMoisture_ = null;
      } else {
        soilMoisture_ = null;
        soilMoistureBuilder_ = null;
      }
      if (illuminanceBuilder_ == null) {
        illuminance_ = null;
      } else {
        illuminance_ = null;
        illuminanceBuilder_ = null;
      }
      if (triggerBuilder_ == null) {
        trigger_ = null;
      } else {
        trigger_ = null;
        triggerBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return pt.sharespot.iot.core.buf.model.MessageOuterClass.internal_static_pt_sharespot_iot_core_SensorData_descriptor;
    }

    @java.lang.Override
    public pt.sharespot.iot.core.buf.model.SensorData getDefaultInstanceForType() {
      return pt.sharespot.iot.core.buf.model.SensorData.getDefaultInstance();
    }

    @java.lang.Override
    public pt.sharespot.iot.core.buf.model.SensorData build() {
      pt.sharespot.iot.core.buf.model.SensorData result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public pt.sharespot.iot.core.buf.model.SensorData buildPartial() {
      pt.sharespot.iot.core.buf.model.SensorData result = new pt.sharespot.iot.core.buf.model.SensorData(this);
      if (gpsBuilder_ == null) {
        result.gps_ = gps_;
      } else {
        result.gps_ = gpsBuilder_.build();
      }
      if (temperatureBuilder_ == null) {
        result.temperature_ = temperature_;
      } else {
        result.temperature_ = temperatureBuilder_.build();
      }
      if (motionBuilder_ == null) {
        result.motion_ = motion_;
      } else {
        result.motion_ = motionBuilder_.build();
      }
      if (aqiBuilder_ == null) {
        result.aqi_ = aqi_;
      } else {
        result.aqi_ = aqiBuilder_.build();
      }
      if (velocityBuilder_ == null) {
        result.velocity_ = velocity_;
      } else {
        result.velocity_ = velocityBuilder_.build();
      }
      if (airHumidityBuilder_ == null) {
        result.airHumidity_ = airHumidity_;
      } else {
        result.airHumidity_ = airHumidityBuilder_.build();
      }
      if (airPressureBuilder_ == null) {
        result.airPressure_ = airPressure_;
      } else {
        result.airPressure_ = airPressureBuilder_.build();
      }
      if (batteryBuilder_ == null) {
        result.battery_ = battery_;
      } else {
        result.battery_ = batteryBuilder_.build();
      }
      if (soilMoistureBuilder_ == null) {
        result.soilMoisture_ = soilMoisture_;
      } else {
        result.soilMoisture_ = soilMoistureBuilder_.build();
      }
      if (illuminanceBuilder_ == null) {
        result.illuminance_ = illuminance_;
      } else {
        result.illuminance_ = illuminanceBuilder_.build();
      }
      if (triggerBuilder_ == null) {
        result.trigger_ = trigger_;
      } else {
        result.trigger_ = triggerBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof pt.sharespot.iot.core.buf.model.SensorData) {
        return mergeFrom((pt.sharespot.iot.core.buf.model.SensorData)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(pt.sharespot.iot.core.buf.model.SensorData other) {
      if (other == pt.sharespot.iot.core.buf.model.SensorData.getDefaultInstance()) return this;
      if (other.hasGps()) {
        mergeGps(other.getGps());
      }
      if (other.hasTemperature()) {
        mergeTemperature(other.getTemperature());
      }
      if (other.hasMotion()) {
        mergeMotion(other.getMotion());
      }
      if (other.hasAqi()) {
        mergeAqi(other.getAqi());
      }
      if (other.hasVelocity()) {
        mergeVelocity(other.getVelocity());
      }
      if (other.hasAirHumidity()) {
        mergeAirHumidity(other.getAirHumidity());
      }
      if (other.hasAirPressure()) {
        mergeAirPressure(other.getAirPressure());
      }
      if (other.hasBattery()) {
        mergeBattery(other.getBattery());
      }
      if (other.hasSoilMoisture()) {
        mergeSoilMoisture(other.getSoilMoisture());
      }
      if (other.hasIlluminance()) {
        mergeIlluminance(other.getIlluminance());
      }
      if (other.hasTrigger()) {
        mergeTrigger(other.getTrigger());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      pt.sharespot.iot.core.buf.model.SensorData parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (pt.sharespot.iot.core.buf.model.SensorData) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private pt.sharespot.iot.core.buf.model.GPS gps_;
    private com.google.protobuf.SingleFieldBuilderV3<
        pt.sharespot.iot.core.buf.model.GPS, pt.sharespot.iot.core.buf.model.GPS.Builder, pt.sharespot.iot.core.buf.model.GPSOrBuilder> gpsBuilder_;
    /**
     * <code>.pt.sharespot.iot.core.GPS gps = 1;</code>
     * @return Whether the gps field is set.
     */
    public boolean hasGps() {
      return gpsBuilder_ != null || gps_ != null;
    }
    /**
     * <code>.pt.sharespot.iot.core.GPS gps = 1;</code>
     * @return The gps.
     */
    public pt.sharespot.iot.core.buf.model.GPS getGps() {
      if (gpsBuilder_ == null) {
        return gps_ == null ? pt.sharespot.iot.core.buf.model.GPS.getDefaultInstance() : gps_;
      } else {
        return gpsBuilder_.getMessage();
      }
    }
    /**
     * <code>.pt.sharespot.iot.core.GPS gps = 1;</code>
     */
    public Builder setGps(pt.sharespot.iot.core.buf.model.GPS value) {
      if (gpsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        gps_ = value;
        onChanged();
      } else {
        gpsBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.pt.sharespot.iot.core.GPS gps = 1;</code>
     */
    public Builder setGps(
        pt.sharespot.iot.core.buf.model.GPS.Builder builderForValue) {
      if (gpsBuilder_ == null) {
        gps_ = builderForValue.build();
        onChanged();
      } else {
        gpsBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.pt.sharespot.iot.core.GPS gps = 1;</code>
     */
    public Builder mergeGps(pt.sharespot.iot.core.buf.model.GPS value) {
      if (gpsBuilder_ == null) {
        if (gps_ != null) {
          gps_ =
            pt.sharespot.iot.core.buf.model.GPS.newBuilder(gps_).mergeFrom(value).buildPartial();
        } else {
          gps_ = value;
        }
        onChanged();
      } else {
        gpsBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.pt.sharespot.iot.core.GPS gps = 1;</code>
     */
    public Builder clearGps() {
      if (gpsBuilder_ == null) {
        gps_ = null;
        onChanged();
      } else {
        gps_ = null;
        gpsBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.pt.sharespot.iot.core.GPS gps = 1;</code>
     */
    public pt.sharespot.iot.core.buf.model.GPS.Builder getGpsBuilder() {
      
      onChanged();
      return getGpsFieldBuilder().getBuilder();
    }
    /**
     * <code>.pt.sharespot.iot.core.GPS gps = 1;</code>
     */
    public pt.sharespot.iot.core.buf.model.GPSOrBuilder getGpsOrBuilder() {
      if (gpsBuilder_ != null) {
        return gpsBuilder_.getMessageOrBuilder();
      } else {
        return gps_ == null ?
            pt.sharespot.iot.core.buf.model.GPS.getDefaultInstance() : gps_;
      }
    }
    /**
     * <code>.pt.sharespot.iot.core.GPS gps = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        pt.sharespot.iot.core.buf.model.GPS, pt.sharespot.iot.core.buf.model.GPS.Builder, pt.sharespot.iot.core.buf.model.GPSOrBuilder> 
        getGpsFieldBuilder() {
      if (gpsBuilder_ == null) {
        gpsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            pt.sharespot.iot.core.buf.model.GPS, pt.sharespot.iot.core.buf.model.GPS.Builder, pt.sharespot.iot.core.buf.model.GPSOrBuilder>(
                getGps(),
                getParentForChildren(),
                isClean());
        gps_ = null;
      }
      return gpsBuilder_;
    }

    private pt.sharespot.iot.core.buf.model.Temperature temperature_;
    private com.google.protobuf.SingleFieldBuilderV3<
        pt.sharespot.iot.core.buf.model.Temperature, pt.sharespot.iot.core.buf.model.Temperature.Builder, pt.sharespot.iot.core.buf.model.TemperatureOrBuilder> temperatureBuilder_;
    /**
     * <code>.pt.sharespot.iot.core.Temperature temperature = 2;</code>
     * @return Whether the temperature field is set.
     */
    public boolean hasTemperature() {
      return temperatureBuilder_ != null || temperature_ != null;
    }
    /**
     * <code>.pt.sharespot.iot.core.Temperature temperature = 2;</code>
     * @return The temperature.
     */
    public pt.sharespot.iot.core.buf.model.Temperature getTemperature() {
      if (temperatureBuilder_ == null) {
        return temperature_ == null ? pt.sharespot.iot.core.buf.model.Temperature.getDefaultInstance() : temperature_;
      } else {
        return temperatureBuilder_.getMessage();
      }
    }
    /**
     * <code>.pt.sharespot.iot.core.Temperature temperature = 2;</code>
     */
    public Builder setTemperature(pt.sharespot.iot.core.buf.model.Temperature value) {
      if (temperatureBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        temperature_ = value;
        onChanged();
      } else {
        temperatureBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.pt.sharespot.iot.core.Temperature temperature = 2;</code>
     */
    public Builder setTemperature(
        pt.sharespot.iot.core.buf.model.Temperature.Builder builderForValue) {
      if (temperatureBuilder_ == null) {
        temperature_ = builderForValue.build();
        onChanged();
      } else {
        temperatureBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.pt.sharespot.iot.core.Temperature temperature = 2;</code>
     */
    public Builder mergeTemperature(pt.sharespot.iot.core.buf.model.Temperature value) {
      if (temperatureBuilder_ == null) {
        if (temperature_ != null) {
          temperature_ =
            pt.sharespot.iot.core.buf.model.Temperature.newBuilder(temperature_).mergeFrom(value).buildPartial();
        } else {
          temperature_ = value;
        }
        onChanged();
      } else {
        temperatureBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.pt.sharespot.iot.core.Temperature temperature = 2;</code>
     */
    public Builder clearTemperature() {
      if (temperatureBuilder_ == null) {
        temperature_ = null;
        onChanged();
      } else {
        temperature_ = null;
        temperatureBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.pt.sharespot.iot.core.Temperature temperature = 2;</code>
     */
    public pt.sharespot.iot.core.buf.model.Temperature.Builder getTemperatureBuilder() {
      
      onChanged();
      return getTemperatureFieldBuilder().getBuilder();
    }
    /**
     * <code>.pt.sharespot.iot.core.Temperature temperature = 2;</code>
     */
    public pt.sharespot.iot.core.buf.model.TemperatureOrBuilder getTemperatureOrBuilder() {
      if (temperatureBuilder_ != null) {
        return temperatureBuilder_.getMessageOrBuilder();
      } else {
        return temperature_ == null ?
            pt.sharespot.iot.core.buf.model.Temperature.getDefaultInstance() : temperature_;
      }
    }
    /**
     * <code>.pt.sharespot.iot.core.Temperature temperature = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        pt.sharespot.iot.core.buf.model.Temperature, pt.sharespot.iot.core.buf.model.Temperature.Builder, pt.sharespot.iot.core.buf.model.TemperatureOrBuilder> 
        getTemperatureFieldBuilder() {
      if (temperatureBuilder_ == null) {
        temperatureBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            pt.sharespot.iot.core.buf.model.Temperature, pt.sharespot.iot.core.buf.model.Temperature.Builder, pt.sharespot.iot.core.buf.model.TemperatureOrBuilder>(
                getTemperature(),
                getParentForChildren(),
                isClean());
        temperature_ = null;
      }
      return temperatureBuilder_;
    }

    private pt.sharespot.iot.core.buf.model.Motion motion_;
    private com.google.protobuf.SingleFieldBuilderV3<
        pt.sharespot.iot.core.buf.model.Motion, pt.sharespot.iot.core.buf.model.Motion.Builder, pt.sharespot.iot.core.buf.model.MotionOrBuilder> motionBuilder_;
    /**
     * <code>.pt.sharespot.iot.core.Motion motion = 3;</code>
     * @return Whether the motion field is set.
     */
    public boolean hasMotion() {
      return motionBuilder_ != null || motion_ != null;
    }
    /**
     * <code>.pt.sharespot.iot.core.Motion motion = 3;</code>
     * @return The motion.
     */
    public pt.sharespot.iot.core.buf.model.Motion getMotion() {
      if (motionBuilder_ == null) {
        return motion_ == null ? pt.sharespot.iot.core.buf.model.Motion.getDefaultInstance() : motion_;
      } else {
        return motionBuilder_.getMessage();
      }
    }
    /**
     * <code>.pt.sharespot.iot.core.Motion motion = 3;</code>
     */
    public Builder setMotion(pt.sharespot.iot.core.buf.model.Motion value) {
      if (motionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        motion_ = value;
        onChanged();
      } else {
        motionBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.pt.sharespot.iot.core.Motion motion = 3;</code>
     */
    public Builder setMotion(
        pt.sharespot.iot.core.buf.model.Motion.Builder builderForValue) {
      if (motionBuilder_ == null) {
        motion_ = builderForValue.build();
        onChanged();
      } else {
        motionBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.pt.sharespot.iot.core.Motion motion = 3;</code>
     */
    public Builder mergeMotion(pt.sharespot.iot.core.buf.model.Motion value) {
      if (motionBuilder_ == null) {
        if (motion_ != null) {
          motion_ =
            pt.sharespot.iot.core.buf.model.Motion.newBuilder(motion_).mergeFrom(value).buildPartial();
        } else {
          motion_ = value;
        }
        onChanged();
      } else {
        motionBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.pt.sharespot.iot.core.Motion motion = 3;</code>
     */
    public Builder clearMotion() {
      if (motionBuilder_ == null) {
        motion_ = null;
        onChanged();
      } else {
        motion_ = null;
        motionBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.pt.sharespot.iot.core.Motion motion = 3;</code>
     */
    public pt.sharespot.iot.core.buf.model.Motion.Builder getMotionBuilder() {
      
      onChanged();
      return getMotionFieldBuilder().getBuilder();
    }
    /**
     * <code>.pt.sharespot.iot.core.Motion motion = 3;</code>
     */
    public pt.sharespot.iot.core.buf.model.MotionOrBuilder getMotionOrBuilder() {
      if (motionBuilder_ != null) {
        return motionBuilder_.getMessageOrBuilder();
      } else {
        return motion_ == null ?
            pt.sharespot.iot.core.buf.model.Motion.getDefaultInstance() : motion_;
      }
    }
    /**
     * <code>.pt.sharespot.iot.core.Motion motion = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        pt.sharespot.iot.core.buf.model.Motion, pt.sharespot.iot.core.buf.model.Motion.Builder, pt.sharespot.iot.core.buf.model.MotionOrBuilder> 
        getMotionFieldBuilder() {
      if (motionBuilder_ == null) {
        motionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            pt.sharespot.iot.core.buf.model.Motion, pt.sharespot.iot.core.buf.model.Motion.Builder, pt.sharespot.iot.core.buf.model.MotionOrBuilder>(
                getMotion(),
                getParentForChildren(),
                isClean());
        motion_ = null;
      }
      return motionBuilder_;
    }

    private pt.sharespot.iot.core.buf.model.AirQuality aqi_;
    private com.google.protobuf.SingleFieldBuilderV3<
        pt.sharespot.iot.core.buf.model.AirQuality, pt.sharespot.iot.core.buf.model.AirQuality.Builder, pt.sharespot.iot.core.buf.model.AirQualityOrBuilder> aqiBuilder_;
    /**
     * <code>.pt.sharespot.iot.core.AirQuality aqi = 4;</code>
     * @return Whether the aqi field is set.
     */
    public boolean hasAqi() {
      return aqiBuilder_ != null || aqi_ != null;
    }
    /**
     * <code>.pt.sharespot.iot.core.AirQuality aqi = 4;</code>
     * @return The aqi.
     */
    public pt.sharespot.iot.core.buf.model.AirQuality getAqi() {
      if (aqiBuilder_ == null) {
        return aqi_ == null ? pt.sharespot.iot.core.buf.model.AirQuality.getDefaultInstance() : aqi_;
      } else {
        return aqiBuilder_.getMessage();
      }
    }
    /**
     * <code>.pt.sharespot.iot.core.AirQuality aqi = 4;</code>
     */
    public Builder setAqi(pt.sharespot.iot.core.buf.model.AirQuality value) {
      if (aqiBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        aqi_ = value;
        onChanged();
      } else {
        aqiBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.pt.sharespot.iot.core.AirQuality aqi = 4;</code>
     */
    public Builder setAqi(
        pt.sharespot.iot.core.buf.model.AirQuality.Builder builderForValue) {
      if (aqiBuilder_ == null) {
        aqi_ = builderForValue.build();
        onChanged();
      } else {
        aqiBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.pt.sharespot.iot.core.AirQuality aqi = 4;</code>
     */
    public Builder mergeAqi(pt.sharespot.iot.core.buf.model.AirQuality value) {
      if (aqiBuilder_ == null) {
        if (aqi_ != null) {
          aqi_ =
            pt.sharespot.iot.core.buf.model.AirQuality.newBuilder(aqi_).mergeFrom(value).buildPartial();
        } else {
          aqi_ = value;
        }
        onChanged();
      } else {
        aqiBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.pt.sharespot.iot.core.AirQuality aqi = 4;</code>
     */
    public Builder clearAqi() {
      if (aqiBuilder_ == null) {
        aqi_ = null;
        onChanged();
      } else {
        aqi_ = null;
        aqiBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.pt.sharespot.iot.core.AirQuality aqi = 4;</code>
     */
    public pt.sharespot.iot.core.buf.model.AirQuality.Builder getAqiBuilder() {
      
      onChanged();
      return getAqiFieldBuilder().getBuilder();
    }
    /**
     * <code>.pt.sharespot.iot.core.AirQuality aqi = 4;</code>
     */
    public pt.sharespot.iot.core.buf.model.AirQualityOrBuilder getAqiOrBuilder() {
      if (aqiBuilder_ != null) {
        return aqiBuilder_.getMessageOrBuilder();
      } else {
        return aqi_ == null ?
            pt.sharespot.iot.core.buf.model.AirQuality.getDefaultInstance() : aqi_;
      }
    }
    /**
     * <code>.pt.sharespot.iot.core.AirQuality aqi = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        pt.sharespot.iot.core.buf.model.AirQuality, pt.sharespot.iot.core.buf.model.AirQuality.Builder, pt.sharespot.iot.core.buf.model.AirQualityOrBuilder> 
        getAqiFieldBuilder() {
      if (aqiBuilder_ == null) {
        aqiBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            pt.sharespot.iot.core.buf.model.AirQuality, pt.sharespot.iot.core.buf.model.AirQuality.Builder, pt.sharespot.iot.core.buf.model.AirQualityOrBuilder>(
                getAqi(),
                getParentForChildren(),
                isClean());
        aqi_ = null;
      }
      return aqiBuilder_;
    }

    private pt.sharespot.iot.core.buf.model.Velocity velocity_;
    private com.google.protobuf.SingleFieldBuilderV3<
        pt.sharespot.iot.core.buf.model.Velocity, pt.sharespot.iot.core.buf.model.Velocity.Builder, pt.sharespot.iot.core.buf.model.VelocityOrBuilder> velocityBuilder_;
    /**
     * <code>.pt.sharespot.iot.core.Velocity velocity = 5;</code>
     * @return Whether the velocity field is set.
     */
    public boolean hasVelocity() {
      return velocityBuilder_ != null || velocity_ != null;
    }
    /**
     * <code>.pt.sharespot.iot.core.Velocity velocity = 5;</code>
     * @return The velocity.
     */
    public pt.sharespot.iot.core.buf.model.Velocity getVelocity() {
      if (velocityBuilder_ == null) {
        return velocity_ == null ? pt.sharespot.iot.core.buf.model.Velocity.getDefaultInstance() : velocity_;
      } else {
        return velocityBuilder_.getMessage();
      }
    }
    /**
     * <code>.pt.sharespot.iot.core.Velocity velocity = 5;</code>
     */
    public Builder setVelocity(pt.sharespot.iot.core.buf.model.Velocity value) {
      if (velocityBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        velocity_ = value;
        onChanged();
      } else {
        velocityBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.pt.sharespot.iot.core.Velocity velocity = 5;</code>
     */
    public Builder setVelocity(
        pt.sharespot.iot.core.buf.model.Velocity.Builder builderForValue) {
      if (velocityBuilder_ == null) {
        velocity_ = builderForValue.build();
        onChanged();
      } else {
        velocityBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.pt.sharespot.iot.core.Velocity velocity = 5;</code>
     */
    public Builder mergeVelocity(pt.sharespot.iot.core.buf.model.Velocity value) {
      if (velocityBuilder_ == null) {
        if (velocity_ != null) {
          velocity_ =
            pt.sharespot.iot.core.buf.model.Velocity.newBuilder(velocity_).mergeFrom(value).buildPartial();
        } else {
          velocity_ = value;
        }
        onChanged();
      } else {
        velocityBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.pt.sharespot.iot.core.Velocity velocity = 5;</code>
     */
    public Builder clearVelocity() {
      if (velocityBuilder_ == null) {
        velocity_ = null;
        onChanged();
      } else {
        velocity_ = null;
        velocityBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.pt.sharespot.iot.core.Velocity velocity = 5;</code>
     */
    public pt.sharespot.iot.core.buf.model.Velocity.Builder getVelocityBuilder() {
      
      onChanged();
      return getVelocityFieldBuilder().getBuilder();
    }
    /**
     * <code>.pt.sharespot.iot.core.Velocity velocity = 5;</code>
     */
    public pt.sharespot.iot.core.buf.model.VelocityOrBuilder getVelocityOrBuilder() {
      if (velocityBuilder_ != null) {
        return velocityBuilder_.getMessageOrBuilder();
      } else {
        return velocity_ == null ?
            pt.sharespot.iot.core.buf.model.Velocity.getDefaultInstance() : velocity_;
      }
    }
    /**
     * <code>.pt.sharespot.iot.core.Velocity velocity = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        pt.sharespot.iot.core.buf.model.Velocity, pt.sharespot.iot.core.buf.model.Velocity.Builder, pt.sharespot.iot.core.buf.model.VelocityOrBuilder> 
        getVelocityFieldBuilder() {
      if (velocityBuilder_ == null) {
        velocityBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            pt.sharespot.iot.core.buf.model.Velocity, pt.sharespot.iot.core.buf.model.Velocity.Builder, pt.sharespot.iot.core.buf.model.VelocityOrBuilder>(
                getVelocity(),
                getParentForChildren(),
                isClean());
        velocity_ = null;
      }
      return velocityBuilder_;
    }

    private pt.sharespot.iot.core.buf.model.AirHumidity airHumidity_;
    private com.google.protobuf.SingleFieldBuilderV3<
        pt.sharespot.iot.core.buf.model.AirHumidity, pt.sharespot.iot.core.buf.model.AirHumidity.Builder, pt.sharespot.iot.core.buf.model.AirHumidityOrBuilder> airHumidityBuilder_;
    /**
     * <code>.pt.sharespot.iot.core.AirHumidity air_humidity = 6;</code>
     * @return Whether the airHumidity field is set.
     */
    public boolean hasAirHumidity() {
      return airHumidityBuilder_ != null || airHumidity_ != null;
    }
    /**
     * <code>.pt.sharespot.iot.core.AirHumidity air_humidity = 6;</code>
     * @return The airHumidity.
     */
    public pt.sharespot.iot.core.buf.model.AirHumidity getAirHumidity() {
      if (airHumidityBuilder_ == null) {
        return airHumidity_ == null ? pt.sharespot.iot.core.buf.model.AirHumidity.getDefaultInstance() : airHumidity_;
      } else {
        return airHumidityBuilder_.getMessage();
      }
    }
    /**
     * <code>.pt.sharespot.iot.core.AirHumidity air_humidity = 6;</code>
     */
    public Builder setAirHumidity(pt.sharespot.iot.core.buf.model.AirHumidity value) {
      if (airHumidityBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        airHumidity_ = value;
        onChanged();
      } else {
        airHumidityBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.pt.sharespot.iot.core.AirHumidity air_humidity = 6;</code>
     */
    public Builder setAirHumidity(
        pt.sharespot.iot.core.buf.model.AirHumidity.Builder builderForValue) {
      if (airHumidityBuilder_ == null) {
        airHumidity_ = builderForValue.build();
        onChanged();
      } else {
        airHumidityBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.pt.sharespot.iot.core.AirHumidity air_humidity = 6;</code>
     */
    public Builder mergeAirHumidity(pt.sharespot.iot.core.buf.model.AirHumidity value) {
      if (airHumidityBuilder_ == null) {
        if (airHumidity_ != null) {
          airHumidity_ =
            pt.sharespot.iot.core.buf.model.AirHumidity.newBuilder(airHumidity_).mergeFrom(value).buildPartial();
        } else {
          airHumidity_ = value;
        }
        onChanged();
      } else {
        airHumidityBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.pt.sharespot.iot.core.AirHumidity air_humidity = 6;</code>
     */
    public Builder clearAirHumidity() {
      if (airHumidityBuilder_ == null) {
        airHumidity_ = null;
        onChanged();
      } else {
        airHumidity_ = null;
        airHumidityBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.pt.sharespot.iot.core.AirHumidity air_humidity = 6;</code>
     */
    public pt.sharespot.iot.core.buf.model.AirHumidity.Builder getAirHumidityBuilder() {
      
      onChanged();
      return getAirHumidityFieldBuilder().getBuilder();
    }
    /**
     * <code>.pt.sharespot.iot.core.AirHumidity air_humidity = 6;</code>
     */
    public pt.sharespot.iot.core.buf.model.AirHumidityOrBuilder getAirHumidityOrBuilder() {
      if (airHumidityBuilder_ != null) {
        return airHumidityBuilder_.getMessageOrBuilder();
      } else {
        return airHumidity_ == null ?
            pt.sharespot.iot.core.buf.model.AirHumidity.getDefaultInstance() : airHumidity_;
      }
    }
    /**
     * <code>.pt.sharespot.iot.core.AirHumidity air_humidity = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        pt.sharespot.iot.core.buf.model.AirHumidity, pt.sharespot.iot.core.buf.model.AirHumidity.Builder, pt.sharespot.iot.core.buf.model.AirHumidityOrBuilder> 
        getAirHumidityFieldBuilder() {
      if (airHumidityBuilder_ == null) {
        airHumidityBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            pt.sharespot.iot.core.buf.model.AirHumidity, pt.sharespot.iot.core.buf.model.AirHumidity.Builder, pt.sharespot.iot.core.buf.model.AirHumidityOrBuilder>(
                getAirHumidity(),
                getParentForChildren(),
                isClean());
        airHumidity_ = null;
      }
      return airHumidityBuilder_;
    }

    private pt.sharespot.iot.core.buf.model.AirPressure airPressure_;
    private com.google.protobuf.SingleFieldBuilderV3<
        pt.sharespot.iot.core.buf.model.AirPressure, pt.sharespot.iot.core.buf.model.AirPressure.Builder, pt.sharespot.iot.core.buf.model.AirPressureOrBuilder> airPressureBuilder_;
    /**
     * <code>.pt.sharespot.iot.core.AirPressure air_pressure = 7;</code>
     * @return Whether the airPressure field is set.
     */
    public boolean hasAirPressure() {
      return airPressureBuilder_ != null || airPressure_ != null;
    }
    /**
     * <code>.pt.sharespot.iot.core.AirPressure air_pressure = 7;</code>
     * @return The airPressure.
     */
    public pt.sharespot.iot.core.buf.model.AirPressure getAirPressure() {
      if (airPressureBuilder_ == null) {
        return airPressure_ == null ? pt.sharespot.iot.core.buf.model.AirPressure.getDefaultInstance() : airPressure_;
      } else {
        return airPressureBuilder_.getMessage();
      }
    }
    /**
     * <code>.pt.sharespot.iot.core.AirPressure air_pressure = 7;</code>
     */
    public Builder setAirPressure(pt.sharespot.iot.core.buf.model.AirPressure value) {
      if (airPressureBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        airPressure_ = value;
        onChanged();
      } else {
        airPressureBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.pt.sharespot.iot.core.AirPressure air_pressure = 7;</code>
     */
    public Builder setAirPressure(
        pt.sharespot.iot.core.buf.model.AirPressure.Builder builderForValue) {
      if (airPressureBuilder_ == null) {
        airPressure_ = builderForValue.build();
        onChanged();
      } else {
        airPressureBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.pt.sharespot.iot.core.AirPressure air_pressure = 7;</code>
     */
    public Builder mergeAirPressure(pt.sharespot.iot.core.buf.model.AirPressure value) {
      if (airPressureBuilder_ == null) {
        if (airPressure_ != null) {
          airPressure_ =
            pt.sharespot.iot.core.buf.model.AirPressure.newBuilder(airPressure_).mergeFrom(value).buildPartial();
        } else {
          airPressure_ = value;
        }
        onChanged();
      } else {
        airPressureBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.pt.sharespot.iot.core.AirPressure air_pressure = 7;</code>
     */
    public Builder clearAirPressure() {
      if (airPressureBuilder_ == null) {
        airPressure_ = null;
        onChanged();
      } else {
        airPressure_ = null;
        airPressureBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.pt.sharespot.iot.core.AirPressure air_pressure = 7;</code>
     */
    public pt.sharespot.iot.core.buf.model.AirPressure.Builder getAirPressureBuilder() {
      
      onChanged();
      return getAirPressureFieldBuilder().getBuilder();
    }
    /**
     * <code>.pt.sharespot.iot.core.AirPressure air_pressure = 7;</code>
     */
    public pt.sharespot.iot.core.buf.model.AirPressureOrBuilder getAirPressureOrBuilder() {
      if (airPressureBuilder_ != null) {
        return airPressureBuilder_.getMessageOrBuilder();
      } else {
        return airPressure_ == null ?
            pt.sharespot.iot.core.buf.model.AirPressure.getDefaultInstance() : airPressure_;
      }
    }
    /**
     * <code>.pt.sharespot.iot.core.AirPressure air_pressure = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        pt.sharespot.iot.core.buf.model.AirPressure, pt.sharespot.iot.core.buf.model.AirPressure.Builder, pt.sharespot.iot.core.buf.model.AirPressureOrBuilder> 
        getAirPressureFieldBuilder() {
      if (airPressureBuilder_ == null) {
        airPressureBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            pt.sharespot.iot.core.buf.model.AirPressure, pt.sharespot.iot.core.buf.model.AirPressure.Builder, pt.sharespot.iot.core.buf.model.AirPressureOrBuilder>(
                getAirPressure(),
                getParentForChildren(),
                isClean());
        airPressure_ = null;
      }
      return airPressureBuilder_;
    }

    private pt.sharespot.iot.core.buf.model.Battery battery_;
    private com.google.protobuf.SingleFieldBuilderV3<
        pt.sharespot.iot.core.buf.model.Battery, pt.sharespot.iot.core.buf.model.Battery.Builder, pt.sharespot.iot.core.buf.model.BatteryOrBuilder> batteryBuilder_;
    /**
     * <code>.pt.sharespot.iot.core.Battery battery = 8;</code>
     * @return Whether the battery field is set.
     */
    public boolean hasBattery() {
      return batteryBuilder_ != null || battery_ != null;
    }
    /**
     * <code>.pt.sharespot.iot.core.Battery battery = 8;</code>
     * @return The battery.
     */
    public pt.sharespot.iot.core.buf.model.Battery getBattery() {
      if (batteryBuilder_ == null) {
        return battery_ == null ? pt.sharespot.iot.core.buf.model.Battery.getDefaultInstance() : battery_;
      } else {
        return batteryBuilder_.getMessage();
      }
    }
    /**
     * <code>.pt.sharespot.iot.core.Battery battery = 8;</code>
     */
    public Builder setBattery(pt.sharespot.iot.core.buf.model.Battery value) {
      if (batteryBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        battery_ = value;
        onChanged();
      } else {
        batteryBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.pt.sharespot.iot.core.Battery battery = 8;</code>
     */
    public Builder setBattery(
        pt.sharespot.iot.core.buf.model.Battery.Builder builderForValue) {
      if (batteryBuilder_ == null) {
        battery_ = builderForValue.build();
        onChanged();
      } else {
        batteryBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.pt.sharespot.iot.core.Battery battery = 8;</code>
     */
    public Builder mergeBattery(pt.sharespot.iot.core.buf.model.Battery value) {
      if (batteryBuilder_ == null) {
        if (battery_ != null) {
          battery_ =
            pt.sharespot.iot.core.buf.model.Battery.newBuilder(battery_).mergeFrom(value).buildPartial();
        } else {
          battery_ = value;
        }
        onChanged();
      } else {
        batteryBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.pt.sharespot.iot.core.Battery battery = 8;</code>
     */
    public Builder clearBattery() {
      if (batteryBuilder_ == null) {
        battery_ = null;
        onChanged();
      } else {
        battery_ = null;
        batteryBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.pt.sharespot.iot.core.Battery battery = 8;</code>
     */
    public pt.sharespot.iot.core.buf.model.Battery.Builder getBatteryBuilder() {
      
      onChanged();
      return getBatteryFieldBuilder().getBuilder();
    }
    /**
     * <code>.pt.sharespot.iot.core.Battery battery = 8;</code>
     */
    public pt.sharespot.iot.core.buf.model.BatteryOrBuilder getBatteryOrBuilder() {
      if (batteryBuilder_ != null) {
        return batteryBuilder_.getMessageOrBuilder();
      } else {
        return battery_ == null ?
            pt.sharespot.iot.core.buf.model.Battery.getDefaultInstance() : battery_;
      }
    }
    /**
     * <code>.pt.sharespot.iot.core.Battery battery = 8;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        pt.sharespot.iot.core.buf.model.Battery, pt.sharespot.iot.core.buf.model.Battery.Builder, pt.sharespot.iot.core.buf.model.BatteryOrBuilder> 
        getBatteryFieldBuilder() {
      if (batteryBuilder_ == null) {
        batteryBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            pt.sharespot.iot.core.buf.model.Battery, pt.sharespot.iot.core.buf.model.Battery.Builder, pt.sharespot.iot.core.buf.model.BatteryOrBuilder>(
                getBattery(),
                getParentForChildren(),
                isClean());
        battery_ = null;
      }
      return batteryBuilder_;
    }

    private pt.sharespot.iot.core.buf.model.SoilMoisture soilMoisture_;
    private com.google.protobuf.SingleFieldBuilderV3<
        pt.sharespot.iot.core.buf.model.SoilMoisture, pt.sharespot.iot.core.buf.model.SoilMoisture.Builder, pt.sharespot.iot.core.buf.model.SoilMoistureOrBuilder> soilMoistureBuilder_;
    /**
     * <code>.pt.sharespot.iot.core.SoilMoisture soil_moisture = 9;</code>
     * @return Whether the soilMoisture field is set.
     */
    public boolean hasSoilMoisture() {
      return soilMoistureBuilder_ != null || soilMoisture_ != null;
    }
    /**
     * <code>.pt.sharespot.iot.core.SoilMoisture soil_moisture = 9;</code>
     * @return The soilMoisture.
     */
    public pt.sharespot.iot.core.buf.model.SoilMoisture getSoilMoisture() {
      if (soilMoistureBuilder_ == null) {
        return soilMoisture_ == null ? pt.sharespot.iot.core.buf.model.SoilMoisture.getDefaultInstance() : soilMoisture_;
      } else {
        return soilMoistureBuilder_.getMessage();
      }
    }
    /**
     * <code>.pt.sharespot.iot.core.SoilMoisture soil_moisture = 9;</code>
     */
    public Builder setSoilMoisture(pt.sharespot.iot.core.buf.model.SoilMoisture value) {
      if (soilMoistureBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        soilMoisture_ = value;
        onChanged();
      } else {
        soilMoistureBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.pt.sharespot.iot.core.SoilMoisture soil_moisture = 9;</code>
     */
    public Builder setSoilMoisture(
        pt.sharespot.iot.core.buf.model.SoilMoisture.Builder builderForValue) {
      if (soilMoistureBuilder_ == null) {
        soilMoisture_ = builderForValue.build();
        onChanged();
      } else {
        soilMoistureBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.pt.sharespot.iot.core.SoilMoisture soil_moisture = 9;</code>
     */
    public Builder mergeSoilMoisture(pt.sharespot.iot.core.buf.model.SoilMoisture value) {
      if (soilMoistureBuilder_ == null) {
        if (soilMoisture_ != null) {
          soilMoisture_ =
            pt.sharespot.iot.core.buf.model.SoilMoisture.newBuilder(soilMoisture_).mergeFrom(value).buildPartial();
        } else {
          soilMoisture_ = value;
        }
        onChanged();
      } else {
        soilMoistureBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.pt.sharespot.iot.core.SoilMoisture soil_moisture = 9;</code>
     */
    public Builder clearSoilMoisture() {
      if (soilMoistureBuilder_ == null) {
        soilMoisture_ = null;
        onChanged();
      } else {
        soilMoisture_ = null;
        soilMoistureBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.pt.sharespot.iot.core.SoilMoisture soil_moisture = 9;</code>
     */
    public pt.sharespot.iot.core.buf.model.SoilMoisture.Builder getSoilMoistureBuilder() {
      
      onChanged();
      return getSoilMoistureFieldBuilder().getBuilder();
    }
    /**
     * <code>.pt.sharespot.iot.core.SoilMoisture soil_moisture = 9;</code>
     */
    public pt.sharespot.iot.core.buf.model.SoilMoistureOrBuilder getSoilMoistureOrBuilder() {
      if (soilMoistureBuilder_ != null) {
        return soilMoistureBuilder_.getMessageOrBuilder();
      } else {
        return soilMoisture_ == null ?
            pt.sharespot.iot.core.buf.model.SoilMoisture.getDefaultInstance() : soilMoisture_;
      }
    }
    /**
     * <code>.pt.sharespot.iot.core.SoilMoisture soil_moisture = 9;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        pt.sharespot.iot.core.buf.model.SoilMoisture, pt.sharespot.iot.core.buf.model.SoilMoisture.Builder, pt.sharespot.iot.core.buf.model.SoilMoistureOrBuilder> 
        getSoilMoistureFieldBuilder() {
      if (soilMoistureBuilder_ == null) {
        soilMoistureBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            pt.sharespot.iot.core.buf.model.SoilMoisture, pt.sharespot.iot.core.buf.model.SoilMoisture.Builder, pt.sharespot.iot.core.buf.model.SoilMoistureOrBuilder>(
                getSoilMoisture(),
                getParentForChildren(),
                isClean());
        soilMoisture_ = null;
      }
      return soilMoistureBuilder_;
    }

    private pt.sharespot.iot.core.buf.model.Illuminance illuminance_;
    private com.google.protobuf.SingleFieldBuilderV3<
        pt.sharespot.iot.core.buf.model.Illuminance, pt.sharespot.iot.core.buf.model.Illuminance.Builder, pt.sharespot.iot.core.buf.model.IlluminanceOrBuilder> illuminanceBuilder_;
    /**
     * <code>.pt.sharespot.iot.core.Illuminance illuminance = 10;</code>
     * @return Whether the illuminance field is set.
     */
    public boolean hasIlluminance() {
      return illuminanceBuilder_ != null || illuminance_ != null;
    }
    /**
     * <code>.pt.sharespot.iot.core.Illuminance illuminance = 10;</code>
     * @return The illuminance.
     */
    public pt.sharespot.iot.core.buf.model.Illuminance getIlluminance() {
      if (illuminanceBuilder_ == null) {
        return illuminance_ == null ? pt.sharespot.iot.core.buf.model.Illuminance.getDefaultInstance() : illuminance_;
      } else {
        return illuminanceBuilder_.getMessage();
      }
    }
    /**
     * <code>.pt.sharespot.iot.core.Illuminance illuminance = 10;</code>
     */
    public Builder setIlluminance(pt.sharespot.iot.core.buf.model.Illuminance value) {
      if (illuminanceBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        illuminance_ = value;
        onChanged();
      } else {
        illuminanceBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.pt.sharespot.iot.core.Illuminance illuminance = 10;</code>
     */
    public Builder setIlluminance(
        pt.sharespot.iot.core.buf.model.Illuminance.Builder builderForValue) {
      if (illuminanceBuilder_ == null) {
        illuminance_ = builderForValue.build();
        onChanged();
      } else {
        illuminanceBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.pt.sharespot.iot.core.Illuminance illuminance = 10;</code>
     */
    public Builder mergeIlluminance(pt.sharespot.iot.core.buf.model.Illuminance value) {
      if (illuminanceBuilder_ == null) {
        if (illuminance_ != null) {
          illuminance_ =
            pt.sharespot.iot.core.buf.model.Illuminance.newBuilder(illuminance_).mergeFrom(value).buildPartial();
        } else {
          illuminance_ = value;
        }
        onChanged();
      } else {
        illuminanceBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.pt.sharespot.iot.core.Illuminance illuminance = 10;</code>
     */
    public Builder clearIlluminance() {
      if (illuminanceBuilder_ == null) {
        illuminance_ = null;
        onChanged();
      } else {
        illuminance_ = null;
        illuminanceBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.pt.sharespot.iot.core.Illuminance illuminance = 10;</code>
     */
    public pt.sharespot.iot.core.buf.model.Illuminance.Builder getIlluminanceBuilder() {
      
      onChanged();
      return getIlluminanceFieldBuilder().getBuilder();
    }
    /**
     * <code>.pt.sharespot.iot.core.Illuminance illuminance = 10;</code>
     */
    public pt.sharespot.iot.core.buf.model.IlluminanceOrBuilder getIlluminanceOrBuilder() {
      if (illuminanceBuilder_ != null) {
        return illuminanceBuilder_.getMessageOrBuilder();
      } else {
        return illuminance_ == null ?
            pt.sharespot.iot.core.buf.model.Illuminance.getDefaultInstance() : illuminance_;
      }
    }
    /**
     * <code>.pt.sharespot.iot.core.Illuminance illuminance = 10;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        pt.sharespot.iot.core.buf.model.Illuminance, pt.sharespot.iot.core.buf.model.Illuminance.Builder, pt.sharespot.iot.core.buf.model.IlluminanceOrBuilder> 
        getIlluminanceFieldBuilder() {
      if (illuminanceBuilder_ == null) {
        illuminanceBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            pt.sharespot.iot.core.buf.model.Illuminance, pt.sharespot.iot.core.buf.model.Illuminance.Builder, pt.sharespot.iot.core.buf.model.IlluminanceOrBuilder>(
                getIlluminance(),
                getParentForChildren(),
                isClean());
        illuminance_ = null;
      }
      return illuminanceBuilder_;
    }

    private pt.sharespot.iot.core.buf.model.Trigger trigger_;
    private com.google.protobuf.SingleFieldBuilderV3<
        pt.sharespot.iot.core.buf.model.Trigger, pt.sharespot.iot.core.buf.model.Trigger.Builder, pt.sharespot.iot.core.buf.model.TriggerOrBuilder> triggerBuilder_;
    /**
     * <code>.pt.sharespot.iot.core.Trigger trigger = 11;</code>
     * @return Whether the trigger field is set.
     */
    public boolean hasTrigger() {
      return triggerBuilder_ != null || trigger_ != null;
    }
    /**
     * <code>.pt.sharespot.iot.core.Trigger trigger = 11;</code>
     * @return The trigger.
     */
    public pt.sharespot.iot.core.buf.model.Trigger getTrigger() {
      if (triggerBuilder_ == null) {
        return trigger_ == null ? pt.sharespot.iot.core.buf.model.Trigger.getDefaultInstance() : trigger_;
      } else {
        return triggerBuilder_.getMessage();
      }
    }
    /**
     * <code>.pt.sharespot.iot.core.Trigger trigger = 11;</code>
     */
    public Builder setTrigger(pt.sharespot.iot.core.buf.model.Trigger value) {
      if (triggerBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        trigger_ = value;
        onChanged();
      } else {
        triggerBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.pt.sharespot.iot.core.Trigger trigger = 11;</code>
     */
    public Builder setTrigger(
        pt.sharespot.iot.core.buf.model.Trigger.Builder builderForValue) {
      if (triggerBuilder_ == null) {
        trigger_ = builderForValue.build();
        onChanged();
      } else {
        triggerBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.pt.sharespot.iot.core.Trigger trigger = 11;</code>
     */
    public Builder mergeTrigger(pt.sharespot.iot.core.buf.model.Trigger value) {
      if (triggerBuilder_ == null) {
        if (trigger_ != null) {
          trigger_ =
            pt.sharespot.iot.core.buf.model.Trigger.newBuilder(trigger_).mergeFrom(value).buildPartial();
        } else {
          trigger_ = value;
        }
        onChanged();
      } else {
        triggerBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.pt.sharespot.iot.core.Trigger trigger = 11;</code>
     */
    public Builder clearTrigger() {
      if (triggerBuilder_ == null) {
        trigger_ = null;
        onChanged();
      } else {
        trigger_ = null;
        triggerBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.pt.sharespot.iot.core.Trigger trigger = 11;</code>
     */
    public pt.sharespot.iot.core.buf.model.Trigger.Builder getTriggerBuilder() {
      
      onChanged();
      return getTriggerFieldBuilder().getBuilder();
    }
    /**
     * <code>.pt.sharespot.iot.core.Trigger trigger = 11;</code>
     */
    public pt.sharespot.iot.core.buf.model.TriggerOrBuilder getTriggerOrBuilder() {
      if (triggerBuilder_ != null) {
        return triggerBuilder_.getMessageOrBuilder();
      } else {
        return trigger_ == null ?
            pt.sharespot.iot.core.buf.model.Trigger.getDefaultInstance() : trigger_;
      }
    }
    /**
     * <code>.pt.sharespot.iot.core.Trigger trigger = 11;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        pt.sharespot.iot.core.buf.model.Trigger, pt.sharespot.iot.core.buf.model.Trigger.Builder, pt.sharespot.iot.core.buf.model.TriggerOrBuilder> 
        getTriggerFieldBuilder() {
      if (triggerBuilder_ == null) {
        triggerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            pt.sharespot.iot.core.buf.model.Trigger, pt.sharespot.iot.core.buf.model.Trigger.Builder, pt.sharespot.iot.core.buf.model.TriggerOrBuilder>(
                getTrigger(),
                getParentForChildren(),
                isClean());
        trigger_ = null;
      }
      return triggerBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:pt.sharespot.iot.core.SensorData)
  }

  // @@protoc_insertion_point(class_scope:pt.sharespot.iot.core.SensorData)
  private static final pt.sharespot.iot.core.buf.model.SensorData DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new pt.sharespot.iot.core.buf.model.SensorData();
  }

  public static pt.sharespot.iot.core.buf.model.SensorData getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SensorData>
      PARSER = new com.google.protobuf.AbstractParser<SensorData>() {
    @java.lang.Override
    public SensorData parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SensorData(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SensorData> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SensorData> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public pt.sharespot.iot.core.buf.model.SensorData getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

