// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/message.proto

package pt.sharespot.iot.core.buf.model;

public interface SoilMoistureOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pt.sharespot.iot.core.SoilMoisture)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float relative_percentage = 1;</code>
   * @return The relativePercentage.
   */
  float getRelativePercentage();
}
