// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/sensor.proto

package pt.sharespot.iot.core.data.buf;

public interface RecordEntryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pt.sharespot.iot.core.RecordEntry)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .pt.sharespot.iot.core.Entry entries = 1;</code>
   */
  java.util.List<pt.sharespot.iot.core.data.buf.Entry> 
      getEntriesList();
  /**
   * <code>repeated .pt.sharespot.iot.core.Entry entries = 1;</code>
   */
  pt.sharespot.iot.core.data.buf.Entry getEntries(int index);
  /**
   * <code>repeated .pt.sharespot.iot.core.Entry entries = 1;</code>
   */
  int getEntriesCount();
  /**
   * <code>repeated .pt.sharespot.iot.core.Entry entries = 1;</code>
   */
  java.util.List<? extends pt.sharespot.iot.core.data.buf.EntryOrBuilder> 
      getEntriesOrBuilderList();
  /**
   * <code>repeated .pt.sharespot.iot.core.Entry entries = 1;</code>
   */
  pt.sharespot.iot.core.data.buf.EntryOrBuilder getEntriesOrBuilder(
      int index);
}
