// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/sensor.proto

package pt.sharespot.iot.core.sensor.buf;

public interface DeviceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pt.sharespot.iot.core.Device)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>.pt.sharespot.iot.core.RecordEntry records = 3;</code>
   * @return Whether the records field is set.
   */
  boolean hasRecords();
  /**
   * <code>.pt.sharespot.iot.core.RecordEntry records = 3;</code>
   * @return The records.
   */
  pt.sharespot.iot.core.sensor.buf.RecordEntry getRecords();
  /**
   * <code>.pt.sharespot.iot.core.RecordEntry records = 3;</code>
   */
  pt.sharespot.iot.core.sensor.buf.RecordEntryOrBuilder getRecordsOrBuilder();

  /**
   * <code>.pt.sharespot.iot.core.DomainOwnership domains = 4;</code>
   * @return Whether the domains field is set.
   */
  boolean hasDomains();
  /**
   * <code>.pt.sharespot.iot.core.DomainOwnership domains = 4;</code>
   * @return The domains.
   */
  pt.sharespot.iot.core.sensor.buf.DomainOwnership getDomains();
  /**
   * <code>.pt.sharespot.iot.core.DomainOwnership domains = 4;</code>
   */
  pt.sharespot.iot.core.sensor.buf.DomainOwnershipOrBuilder getDomainsOrBuilder();

  /**
   * <code>string downlink = 5;</code>
   * @return The downlink.
   */
  java.lang.String getDownlink();
  /**
   * <code>string downlink = 5;</code>
   * @return The bytes for downlink.
   */
  com.google.protobuf.ByteString
      getDownlinkBytes();

  /**
   * <code>map&lt;int32, .pt.sharespot.iot.core.DeviceCommands&gt; commands = 6;</code>
   */
  int getCommandsCount();
  /**
   * <code>map&lt;int32, .pt.sharespot.iot.core.DeviceCommands&gt; commands = 6;</code>
   */
  boolean containsCommands(
      int key);
  /**
   * Use {@link #getCommandsMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.Integer, pt.sharespot.iot.core.sensor.buf.DeviceCommands>
  getCommands();
  /**
   * <code>map&lt;int32, .pt.sharespot.iot.core.DeviceCommands&gt; commands = 6;</code>
   */
  java.util.Map<java.lang.Integer, pt.sharespot.iot.core.sensor.buf.DeviceCommands>
  getCommandsMap();
  /**
   * <code>map&lt;int32, .pt.sharespot.iot.core.DeviceCommands&gt; commands = 6;</code>
   */

  /* nullable */
pt.sharespot.iot.core.sensor.buf.DeviceCommands getCommandsOrDefault(
      int key,
      /* nullable */
pt.sharespot.iot.core.sensor.buf.DeviceCommands defaultValue);
  /**
   * <code>map&lt;int32, .pt.sharespot.iot.core.DeviceCommands&gt; commands = 6;</code>
   */

  pt.sharespot.iot.core.sensor.buf.DeviceCommands getCommandsOrThrow(
      int key);
}
