// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/sensor.proto

package pt.sharespot.iot.core.sensor.buf;

/**
 * Protobuf type {@code pt.sharespot.iot.core.Message}
 */
public final class Message extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:pt.sharespot.iot.core.Message)
    MessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Message.newBuilder() to construct.
  private Message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Message() {
    oid_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Message();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Message(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            oid_ = s;
            break;
          }
          case 18: {
            pt.sharespot.iot.core.sensor.buf.RoutingKeysBuf.Builder subBuilder = null;
            if (routingKeys_ != null) {
              subBuilder = routingKeys_.toBuilder();
            }
            routingKeys_ = input.readMessage(pt.sharespot.iot.core.sensor.buf.RoutingKeysBuf.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(routingKeys_);
              routingKeys_ = subBuilder.buildPartial();
            }

            break;
          }
          case 24: {

            hops_ = input.readInt32();
            break;
          }
          case 34: {
            pt.sharespot.iot.core.sensor.buf.Data.Builder subBuilder = null;
            if (data_ != null) {
              subBuilder = data_.toBuilder();
            }
            data_ = input.readMessage(pt.sharespot.iot.core.sensor.buf.Data.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(data_);
              data_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return pt.sharespot.iot.core.sensor.buf.Sensor.internal_static_pt_sharespot_iot_core_Message_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return pt.sharespot.iot.core.sensor.buf.Sensor.internal_static_pt_sharespot_iot_core_Message_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            pt.sharespot.iot.core.sensor.buf.Message.class, pt.sharespot.iot.core.sensor.buf.Message.Builder.class);
  }

  public static final int OID_FIELD_NUMBER = 1;
  private volatile java.lang.Object oid_;
  /**
   * <code>string oid = 1;</code>
   * @return The oid.
   */
  @java.lang.Override
  public java.lang.String getOid() {
    java.lang.Object ref = oid_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      oid_ = s;
      return s;
    }
  }
  /**
   * <code>string oid = 1;</code>
   * @return The bytes for oid.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getOidBytes() {
    java.lang.Object ref = oid_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      oid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ROUTING_KEYS_FIELD_NUMBER = 2;
  private pt.sharespot.iot.core.sensor.buf.RoutingKeysBuf routingKeys_;
  /**
   * <code>.pt.sharespot.iot.core.RoutingKeysBuf routing_keys = 2;</code>
   * @return Whether the routingKeys field is set.
   */
  @java.lang.Override
  public boolean hasRoutingKeys() {
    return routingKeys_ != null;
  }
  /**
   * <code>.pt.sharespot.iot.core.RoutingKeysBuf routing_keys = 2;</code>
   * @return The routingKeys.
   */
  @java.lang.Override
  public pt.sharespot.iot.core.sensor.buf.RoutingKeysBuf getRoutingKeys() {
    return routingKeys_ == null ? pt.sharespot.iot.core.sensor.buf.RoutingKeysBuf.getDefaultInstance() : routingKeys_;
  }
  /**
   * <code>.pt.sharespot.iot.core.RoutingKeysBuf routing_keys = 2;</code>
   */
  @java.lang.Override
  public pt.sharespot.iot.core.sensor.buf.RoutingKeysBufOrBuilder getRoutingKeysOrBuilder() {
    return getRoutingKeys();
  }

  public static final int HOPS_FIELD_NUMBER = 3;
  private int hops_;
  /**
   * <code>int32 hops = 3;</code>
   * @return The hops.
   */
  @java.lang.Override
  public int getHops() {
    return hops_;
  }

  public static final int DATA_FIELD_NUMBER = 4;
  private pt.sharespot.iot.core.sensor.buf.Data data_;
  /**
   * <code>.pt.sharespot.iot.core.Data data = 4;</code>
   * @return Whether the data field is set.
   */
  @java.lang.Override
  public boolean hasData() {
    return data_ != null;
  }
  /**
   * <code>.pt.sharespot.iot.core.Data data = 4;</code>
   * @return The data.
   */
  @java.lang.Override
  public pt.sharespot.iot.core.sensor.buf.Data getData() {
    return data_ == null ? pt.sharespot.iot.core.sensor.buf.Data.getDefaultInstance() : data_;
  }
  /**
   * <code>.pt.sharespot.iot.core.Data data = 4;</code>
   */
  @java.lang.Override
  public pt.sharespot.iot.core.sensor.buf.DataOrBuilder getDataOrBuilder() {
    return getData();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(oid_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, oid_);
    }
    if (routingKeys_ != null) {
      output.writeMessage(2, getRoutingKeys());
    }
    if (hops_ != 0) {
      output.writeInt32(3, hops_);
    }
    if (data_ != null) {
      output.writeMessage(4, getData());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(oid_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, oid_);
    }
    if (routingKeys_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getRoutingKeys());
    }
    if (hops_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, hops_);
    }
    if (data_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getData());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof pt.sharespot.iot.core.sensor.buf.Message)) {
      return super.equals(obj);
    }
    pt.sharespot.iot.core.sensor.buf.Message other = (pt.sharespot.iot.core.sensor.buf.Message) obj;

    if (!getOid()
        .equals(other.getOid())) return false;
    if (hasRoutingKeys() != other.hasRoutingKeys()) return false;
    if (hasRoutingKeys()) {
      if (!getRoutingKeys()
          .equals(other.getRoutingKeys())) return false;
    }
    if (getHops()
        != other.getHops()) return false;
    if (hasData() != other.hasData()) return false;
    if (hasData()) {
      if (!getData()
          .equals(other.getData())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + OID_FIELD_NUMBER;
    hash = (53 * hash) + getOid().hashCode();
    if (hasRoutingKeys()) {
      hash = (37 * hash) + ROUTING_KEYS_FIELD_NUMBER;
      hash = (53 * hash) + getRoutingKeys().hashCode();
    }
    hash = (37 * hash) + HOPS_FIELD_NUMBER;
    hash = (53 * hash) + getHops();
    if (hasData()) {
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static pt.sharespot.iot.core.sensor.buf.Message parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static pt.sharespot.iot.core.sensor.buf.Message parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static pt.sharespot.iot.core.sensor.buf.Message parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static pt.sharespot.iot.core.sensor.buf.Message parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static pt.sharespot.iot.core.sensor.buf.Message parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static pt.sharespot.iot.core.sensor.buf.Message parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static pt.sharespot.iot.core.sensor.buf.Message parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static pt.sharespot.iot.core.sensor.buf.Message parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static pt.sharespot.iot.core.sensor.buf.Message parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static pt.sharespot.iot.core.sensor.buf.Message parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static pt.sharespot.iot.core.sensor.buf.Message parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static pt.sharespot.iot.core.sensor.buf.Message parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(pt.sharespot.iot.core.sensor.buf.Message prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code pt.sharespot.iot.core.Message}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:pt.sharespot.iot.core.Message)
      pt.sharespot.iot.core.sensor.buf.MessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pt.sharespot.iot.core.sensor.buf.Sensor.internal_static_pt_sharespot_iot_core_Message_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pt.sharespot.iot.core.sensor.buf.Sensor.internal_static_pt_sharespot_iot_core_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pt.sharespot.iot.core.sensor.buf.Message.class, pt.sharespot.iot.core.sensor.buf.Message.Builder.class);
    }

    // Construct using pt.sharespot.iot.core.sensor.buf.Message.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      oid_ = "";

      if (routingKeysBuilder_ == null) {
        routingKeys_ = null;
      } else {
        routingKeys_ = null;
        routingKeysBuilder_ = null;
      }
      hops_ = 0;

      if (dataBuilder_ == null) {
        data_ = null;
      } else {
        data_ = null;
        dataBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return pt.sharespot.iot.core.sensor.buf.Sensor.internal_static_pt_sharespot_iot_core_Message_descriptor;
    }

    @java.lang.Override
    public pt.sharespot.iot.core.sensor.buf.Message getDefaultInstanceForType() {
      return pt.sharespot.iot.core.sensor.buf.Message.getDefaultInstance();
    }

    @java.lang.Override
    public pt.sharespot.iot.core.sensor.buf.Message build() {
      pt.sharespot.iot.core.sensor.buf.Message result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public pt.sharespot.iot.core.sensor.buf.Message buildPartial() {
      pt.sharespot.iot.core.sensor.buf.Message result = new pt.sharespot.iot.core.sensor.buf.Message(this);
      result.oid_ = oid_;
      if (routingKeysBuilder_ == null) {
        result.routingKeys_ = routingKeys_;
      } else {
        result.routingKeys_ = routingKeysBuilder_.build();
      }
      result.hops_ = hops_;
      if (dataBuilder_ == null) {
        result.data_ = data_;
      } else {
        result.data_ = dataBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof pt.sharespot.iot.core.sensor.buf.Message) {
        return mergeFrom((pt.sharespot.iot.core.sensor.buf.Message)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(pt.sharespot.iot.core.sensor.buf.Message other) {
      if (other == pt.sharespot.iot.core.sensor.buf.Message.getDefaultInstance()) return this;
      if (!other.getOid().isEmpty()) {
        oid_ = other.oid_;
        onChanged();
      }
      if (other.hasRoutingKeys()) {
        mergeRoutingKeys(other.getRoutingKeys());
      }
      if (other.getHops() != 0) {
        setHops(other.getHops());
      }
      if (other.hasData()) {
        mergeData(other.getData());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      pt.sharespot.iot.core.sensor.buf.Message parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (pt.sharespot.iot.core.sensor.buf.Message) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object oid_ = "";
    /**
     * <code>string oid = 1;</code>
     * @return The oid.
     */
    public java.lang.String getOid() {
      java.lang.Object ref = oid_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        oid_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string oid = 1;</code>
     * @return The bytes for oid.
     */
    public com.google.protobuf.ByteString
        getOidBytes() {
      java.lang.Object ref = oid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        oid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string oid = 1;</code>
     * @param value The oid to set.
     * @return This builder for chaining.
     */
    public Builder setOid(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      oid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string oid = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearOid() {
      
      oid_ = getDefaultInstance().getOid();
      onChanged();
      return this;
    }
    /**
     * <code>string oid = 1;</code>
     * @param value The bytes for oid to set.
     * @return This builder for chaining.
     */
    public Builder setOidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      oid_ = value;
      onChanged();
      return this;
    }

    private pt.sharespot.iot.core.sensor.buf.RoutingKeysBuf routingKeys_;
    private com.google.protobuf.SingleFieldBuilderV3<
        pt.sharespot.iot.core.sensor.buf.RoutingKeysBuf, pt.sharespot.iot.core.sensor.buf.RoutingKeysBuf.Builder, pt.sharespot.iot.core.sensor.buf.RoutingKeysBufOrBuilder> routingKeysBuilder_;
    /**
     * <code>.pt.sharespot.iot.core.RoutingKeysBuf routing_keys = 2;</code>
     * @return Whether the routingKeys field is set.
     */
    public boolean hasRoutingKeys() {
      return routingKeysBuilder_ != null || routingKeys_ != null;
    }
    /**
     * <code>.pt.sharespot.iot.core.RoutingKeysBuf routing_keys = 2;</code>
     * @return The routingKeys.
     */
    public pt.sharespot.iot.core.sensor.buf.RoutingKeysBuf getRoutingKeys() {
      if (routingKeysBuilder_ == null) {
        return routingKeys_ == null ? pt.sharespot.iot.core.sensor.buf.RoutingKeysBuf.getDefaultInstance() : routingKeys_;
      } else {
        return routingKeysBuilder_.getMessage();
      }
    }
    /**
     * <code>.pt.sharespot.iot.core.RoutingKeysBuf routing_keys = 2;</code>
     */
    public Builder setRoutingKeys(pt.sharespot.iot.core.sensor.buf.RoutingKeysBuf value) {
      if (routingKeysBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        routingKeys_ = value;
        onChanged();
      } else {
        routingKeysBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.pt.sharespot.iot.core.RoutingKeysBuf routing_keys = 2;</code>
     */
    public Builder setRoutingKeys(
        pt.sharespot.iot.core.sensor.buf.RoutingKeysBuf.Builder builderForValue) {
      if (routingKeysBuilder_ == null) {
        routingKeys_ = builderForValue.build();
        onChanged();
      } else {
        routingKeysBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.pt.sharespot.iot.core.RoutingKeysBuf routing_keys = 2;</code>
     */
    public Builder mergeRoutingKeys(pt.sharespot.iot.core.sensor.buf.RoutingKeysBuf value) {
      if (routingKeysBuilder_ == null) {
        if (routingKeys_ != null) {
          routingKeys_ =
            pt.sharespot.iot.core.sensor.buf.RoutingKeysBuf.newBuilder(routingKeys_).mergeFrom(value).buildPartial();
        } else {
          routingKeys_ = value;
        }
        onChanged();
      } else {
        routingKeysBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.pt.sharespot.iot.core.RoutingKeysBuf routing_keys = 2;</code>
     */
    public Builder clearRoutingKeys() {
      if (routingKeysBuilder_ == null) {
        routingKeys_ = null;
        onChanged();
      } else {
        routingKeys_ = null;
        routingKeysBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.pt.sharespot.iot.core.RoutingKeysBuf routing_keys = 2;</code>
     */
    public pt.sharespot.iot.core.sensor.buf.RoutingKeysBuf.Builder getRoutingKeysBuilder() {
      
      onChanged();
      return getRoutingKeysFieldBuilder().getBuilder();
    }
    /**
     * <code>.pt.sharespot.iot.core.RoutingKeysBuf routing_keys = 2;</code>
     */
    public pt.sharespot.iot.core.sensor.buf.RoutingKeysBufOrBuilder getRoutingKeysOrBuilder() {
      if (routingKeysBuilder_ != null) {
        return routingKeysBuilder_.getMessageOrBuilder();
      } else {
        return routingKeys_ == null ?
            pt.sharespot.iot.core.sensor.buf.RoutingKeysBuf.getDefaultInstance() : routingKeys_;
      }
    }
    /**
     * <code>.pt.sharespot.iot.core.RoutingKeysBuf routing_keys = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        pt.sharespot.iot.core.sensor.buf.RoutingKeysBuf, pt.sharespot.iot.core.sensor.buf.RoutingKeysBuf.Builder, pt.sharespot.iot.core.sensor.buf.RoutingKeysBufOrBuilder> 
        getRoutingKeysFieldBuilder() {
      if (routingKeysBuilder_ == null) {
        routingKeysBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            pt.sharespot.iot.core.sensor.buf.RoutingKeysBuf, pt.sharespot.iot.core.sensor.buf.RoutingKeysBuf.Builder, pt.sharespot.iot.core.sensor.buf.RoutingKeysBufOrBuilder>(
                getRoutingKeys(),
                getParentForChildren(),
                isClean());
        routingKeys_ = null;
      }
      return routingKeysBuilder_;
    }

    private int hops_ ;
    /**
     * <code>int32 hops = 3;</code>
     * @return The hops.
     */
    @java.lang.Override
    public int getHops() {
      return hops_;
    }
    /**
     * <code>int32 hops = 3;</code>
     * @param value The hops to set.
     * @return This builder for chaining.
     */
    public Builder setHops(int value) {
      
      hops_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 hops = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearHops() {
      
      hops_ = 0;
      onChanged();
      return this;
    }

    private pt.sharespot.iot.core.sensor.buf.Data data_;
    private com.google.protobuf.SingleFieldBuilderV3<
        pt.sharespot.iot.core.sensor.buf.Data, pt.sharespot.iot.core.sensor.buf.Data.Builder, pt.sharespot.iot.core.sensor.buf.DataOrBuilder> dataBuilder_;
    /**
     * <code>.pt.sharespot.iot.core.Data data = 4;</code>
     * @return Whether the data field is set.
     */
    public boolean hasData() {
      return dataBuilder_ != null || data_ != null;
    }
    /**
     * <code>.pt.sharespot.iot.core.Data data = 4;</code>
     * @return The data.
     */
    public pt.sharespot.iot.core.sensor.buf.Data getData() {
      if (dataBuilder_ == null) {
        return data_ == null ? pt.sharespot.iot.core.sensor.buf.Data.getDefaultInstance() : data_;
      } else {
        return dataBuilder_.getMessage();
      }
    }
    /**
     * <code>.pt.sharespot.iot.core.Data data = 4;</code>
     */
    public Builder setData(pt.sharespot.iot.core.sensor.buf.Data value) {
      if (dataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        data_ = value;
        onChanged();
      } else {
        dataBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.pt.sharespot.iot.core.Data data = 4;</code>
     */
    public Builder setData(
        pt.sharespot.iot.core.sensor.buf.Data.Builder builderForValue) {
      if (dataBuilder_ == null) {
        data_ = builderForValue.build();
        onChanged();
      } else {
        dataBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.pt.sharespot.iot.core.Data data = 4;</code>
     */
    public Builder mergeData(pt.sharespot.iot.core.sensor.buf.Data value) {
      if (dataBuilder_ == null) {
        if (data_ != null) {
          data_ =
            pt.sharespot.iot.core.sensor.buf.Data.newBuilder(data_).mergeFrom(value).buildPartial();
        } else {
          data_ = value;
        }
        onChanged();
      } else {
        dataBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.pt.sharespot.iot.core.Data data = 4;</code>
     */
    public Builder clearData() {
      if (dataBuilder_ == null) {
        data_ = null;
        onChanged();
      } else {
        data_ = null;
        dataBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.pt.sharespot.iot.core.Data data = 4;</code>
     */
    public pt.sharespot.iot.core.sensor.buf.Data.Builder getDataBuilder() {
      
      onChanged();
      return getDataFieldBuilder().getBuilder();
    }
    /**
     * <code>.pt.sharespot.iot.core.Data data = 4;</code>
     */
    public pt.sharespot.iot.core.sensor.buf.DataOrBuilder getDataOrBuilder() {
      if (dataBuilder_ != null) {
        return dataBuilder_.getMessageOrBuilder();
      } else {
        return data_ == null ?
            pt.sharespot.iot.core.sensor.buf.Data.getDefaultInstance() : data_;
      }
    }
    /**
     * <code>.pt.sharespot.iot.core.Data data = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        pt.sharespot.iot.core.sensor.buf.Data, pt.sharespot.iot.core.sensor.buf.Data.Builder, pt.sharespot.iot.core.sensor.buf.DataOrBuilder> 
        getDataFieldBuilder() {
      if (dataBuilder_ == null) {
        dataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            pt.sharespot.iot.core.sensor.buf.Data, pt.sharespot.iot.core.sensor.buf.Data.Builder, pt.sharespot.iot.core.sensor.buf.DataOrBuilder>(
                getData(),
                getParentForChildren(),
                isClean());
        data_ = null;
      }
      return dataBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:pt.sharespot.iot.core.Message)
  }

  // @@protoc_insertion_point(class_scope:pt.sharespot.iot.core.Message)
  private static final pt.sharespot.iot.core.sensor.buf.Message DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new pt.sharespot.iot.core.sensor.buf.Message();
  }

  public static pt.sharespot.iot.core.sensor.buf.Message getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Message>
      PARSER = new com.google.protobuf.AbstractParser<Message>() {
    @java.lang.Override
    public Message parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Message(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Message> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Message> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public pt.sharespot.iot.core.sensor.buf.Message getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

