// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/sensor.proto

package pt.sharespot.iot.core.sensor.buf;

public interface PHOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pt.sharespot.iot.core.PH)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.google.protobuf.FloatValue value = 1;</code>
   * @return Whether the value field is set.
   */
  boolean hasValue();
  /**
   * <code>.google.protobuf.FloatValue value = 1;</code>
   * @return The value.
   */
  com.google.protobuf.FloatValue getValue();
  /**
   * <code>.google.protobuf.FloatValue value = 1;</code>
   */
  com.google.protobuf.FloatValueOrBuilder getValueOrBuilder();
}
